pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/modelarts_pool.go

fix modelarts refresh :add modelarts created failed
- release/3.10
/cc @ioito

fix(cloudmux): add modelarts created failed

---

pkg/multicloud/openstack/openstack.go

Cherry pick of #89 on release/3.10.
#89: fix(openstack): api version

Automated cherry pick of #89: fix(openstack): api version

---

pkg/multicloud/esxi/monitor.go
pkg/multicloud/esxi/shell/monitor.go
pkg/multicloud/esxi/shell/utils.go
pkg/multicloud/esxi/storagecache.go
pkg/multicloud/esxi/virtualmachine.go

fix: esxi virtualmachine missing datastore property
- release/3.10

fix: esxi virtualmachine missing datastore property

---

pkg/multicloud/host_base.go

Cherry pick of #134 on release/3.10.
#134: fix(common): default host cpu arch is x86_64

Automated cherry pick of #134: fix(common): default host cpu arch is x86_64

---

pkg/multicloud/google/storagecache.go

Cherry pick of #181 on release/3.10.
#181: fix(google): gcp storage cache

Automated cherry pick of #181: fix(google): gcp storage cache

---

pkg/multicloud/google/storagecache.go

Cherry pick of #183 on release/3.10.
#183: fix(google): gcp storage cache

Automated cherry pick of #183: fix(google): gcp storage cache

---

pkg/multicloud/esxi/template.go

Cherry pick of #193 on release/3.10.
#193: fix(vmware): esxi template image root size

Automated cherry pick of #193: fix(vmware): esxi template image root size

---

pkg/multicloud/openstack/openstack.go

Cherry pick of #197 on release/3.10.
#197: fix(openstack): compute api version

Automated cherry pick of #197: fix(openstack): compute api version

---

pkg/multicloud/esxi/wire.go

fix: vmware wire id should be scoped by cloud account
NONE

fix: vmware wire id should be scoped by cloud account

---

pkg/multicloud/esxi/devtools.go

fix: more details when esxi get_network_by_id error
- release/3.11

fix: more details when esxi get_network_by_id error

---

pkg/multicloud/aws/organizations.go

Cherry pick of #497 on release/3.11.
#497: fix(aws): subaccount name

Automated cherry pick of #497: fix(aws): subaccount name

---

pkg/multicloud/aliyun/vpc.go
pkg/multicloud/apsara/vpc.go
pkg/multicloud/azure/instancenic.go
pkg/multicloud/azure/securitygroup.go

fix(azure): secgroup delete

---

pkg/multicloud/aws/securitygroup.go

Cherry pick of #517 on release/3.11.
#517: fix(region): aws default secgroup delete

Automated cherry pick of #517: fix(region): aws default secgroup delete

---

pkg/multicloud/proxmox/cluster.go

Cherry pick of #545 on release/3.10.
#545: fix(pve): min vm id

Automated cherry pick of #545: fix(pve): min vm id

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/aliyun.go
pkg/multicloud/aliyun/provider/provider.go
pkg/multicloud/aliyun/shell/sslcertificate.go
pkg/multicloud/aliyun/sslcertificate.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/provider/provider.go
pkg/multicloud/huawei/shell/sslcertificate.go
pkg/multicloud/huawei/sslcertificate.go
pkg/multicloud/qcloud/certificate.go
pkg/multicloud/qcloud/provider/provider.go
pkg/multicloud/qcloud/qcloud.go

证书资源方法从SRegion下改为SProvider和Client下
由于华为较特殊 一个云账号对应多个provider, huawei client 增加字段isSyncCertProject来区分出同步的那个provider

fix(region): move sslcert from Region to CloudProvider

---

pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/instance.go

Cherry pick of #673 on release/3.11.
#673: fix(huawei): skip sync huawei ipv6 eip

Automated cherry pick of #673: fix(huawei): skip sync huawei ipv6 eip

---

pkg/multicloud/huawei/port.go

Cherry pick of #688 on release/3.11.
#688: fix(huawei): skip hw networkinterface sync

Automated cherry pick of #688: fix(huawei): skip hw networkinterface sync

---

pkg/multicloud/bingocloud/bingo.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/hcso/huawei.go
pkg/multicloud/nutanix/nutanix.go
pkg/multicloud/objectstore/objectstore.go
pkg/multicloud/objectstore/xsky/xsky.go
pkg/multicloud/openstack/openstack.go
pkg/multicloud/proxmox/proxmox.go
pkg/multicloud/remotefile/remotefile.go
pkg/multicloud/zstack/zstack.go

fix: set subaccount id for non-public clouds
- release/3.11

fix: set subaccount id for non-public clouds

---

pkg/multicloud/bingocloud/bingo.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/hcso/huawei.go
pkg/multicloud/nutanix/nutanix.go
pkg/multicloud/objectstore/objectstore.go
pkg/multicloud/objectstore/xsky/xsky.go
pkg/multicloud/openstack/openstack.go
pkg/multicloud/proxmox/proxmox.go
pkg/multicloud/remotefile/remotefile.go
pkg/multicloud/zstack/zstack.go

Cherry pick of #632 on release/3.11.
#632: fix: set subaccount id for non-public clouds

Automated cherry pick of #632: fix: set subaccount id for non-public clouds

---

pkg/multicloud/qcloud/loadbalancer_backend.go

Cherry pick of #715 on release/3.11.
#715: fix(qcloud): avoid unmarshal lb backend tags error

Automated cherry pick of #715: fix(qcloud): avoid unmarshal lb backend tags error

---

pkg/multicloud/esxi/storage.go
pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #739 on release/3.11.
#739: fix(esxi): migrate vm choices usable datastore

Automated cherry pick of #739: fix(esxi): migrate vm choices usable datastore

---

pkg/multicloud/openstack/openstack.go

Cherry pick of #763 on release/3.11.
#763: fix(openstack): support https for openstack

Automated cherry pick of #763: fix(openstack): support https for openstack

---

pkg/multicloud/huawei/vpc.go

Cherry pick of #811 on release/3.11.
#811: fix(huawei): ignore invalid nat sync

Automated cherry pick of #811: fix(huawei): ignore invalid nat sync

---

pkg/multicloud/aws/image.go

Cherry pick of #857 on release/3.11.
#857: fix(aws): aws instance image info

Automated cherry pick of #857: fix(aws): aws instance image info

---

pkg/multicloud/qcloud/region.go

Cherry pick of #889 on release/3.12.
#889: fix(qcloud): vpc not found

Automated cherry pick of #889: fix(qcloud): vpc not found

---

Makefile
go.mod
go.sum
vendor/modules.txt
vendor/yunion.io/x/log/log.go

fix: cloudmux lock pkg tag at release/3.10
- release/3.10
/cc @ioito

fix: cloudmux lock pkg tag at release/3.10

---

pkg/multicloud/huawei/huawei.go

Cherry pick of #948 on release/3.11.
#948: fix(huawei): avoid empty resp panic

Automated cherry pick of #948: fix(huawei): avoid empty resp panic

---

pkg/multicloud/qcloud/qcloud.go

Cherry pick of #994 on release/3.12.
#994: fix(qcloud): nat capability sync

Automated cherry pick of #994: fix(qcloud): nat capability sync

---

pkg/multicloud/proxmox/host.go
pkg/multicloud/proxmox/instance.go

Cherry pick of #1034 on release/3.12.
#1034: fix(pve): supports cpu architecture differentiation

Automated cherry pick of #1034: fix(pve): supports cpu architecture differentiation

---

pkg/multicloud/qcloud/loadbalancer_backend.go

Cherry pick of #1038 on release/3.12.
#1038: fix(qcloud): lb backend ip sync

Automated cherry pick of #1038: fix(qcloud): lb backend ip sync

---

pkg/multicloud/objectstore/objectstore.go

Cherry pick of #970 on release/3.12.
#970: fix: ceph reuse http connection (reported by GDYT)

Automated cherry pick of #970: fix: ceph reuse http connection (reported by GDYT)

---

pkg/multicloud/openstack/securitygroup.go

Cherry pick of #1063 on release/3.12.
#1063: fix(openstack): secgroup vpc id

Automated cherry pick of #1063: fix(openstack): secgroup vpc id

---

scripts/docker_push.sh

fix: upgrade docker_push.sh go version to 1.21
- release/3.11
- release/3.12

fix: upgrade docker_push.sh go version to 1.21

---

scripts/docker_push.sh

Cherry pick of #1082 on release/3.11.7.
#1082: fix: upgrade docker_push.sh go version to 1.21

Automated cherry pick of #1082: fix: upgrade docker_push.sh go version to 1.21

---

pkg/multicloud/qcloud/loadbalancer_listener.go

Cherry pick of #1089 on release/3.12.
#1089: fix(qcloud): lb listener health check type

Automated cherry pick of #1089: fix(qcloud): lb listener health check type

---

pkg/multicloud/ucloud/instance.go

Cherry pick of #1099 on master.
#1099: fix(ucloud): avoid panic when sync vm tags

Automated cherry pick of #1099: fix(ucloud): avoid panic when sync vm tags

---

pkg/multicloud/ctyun/eip.go
pkg/multicloud/ctyun/instance.go

Cherry pick of #1102 on release/3.12.
#1102: fix(ctyun): prepaid status

Automated cherry pick of #1102: fix(ctyun): prepaid status

---

pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/storagecache.go

Cherry pick of #1106 on release/3.12.
#1106: fix(esxi): disable swap

Automated cherry pick of #1106: fix(esxi): disable swap

---

go.mod
go.sum
vendor/modules.txt

fix: update vendor v3.11.9 20241220
NONE
/cc @zexi

fix: update vendor v3.11.9 20241220

---

go.mod
go.sum
pkg/multicloud/objectstore/buckets.go
pkg/multicloud/objectstore/shell.go
vendor/modules.txt
vendor/yunion.io/x/jsonutils/jsonutils.go
vendor/yunion.io/x/s3cli/api-s3-datatypes.go

Cherry pick of #1140 on release/3.12.
#1140: fix: ignore put object acl error

Automated cherry pick of #1140: fix: ignore put object acl error

---

pkg/multicloud/qcloud/rds_mysql.go

Cherry pick of #1144 on release/3.10.
#1144: fix(qcloud): rds cpu option

Automated cherry pick of #1144: fix(qcloud): rds cpu option

---

pkg/multicloud/volcengine/volcengine.go

Cherry pick of #1149 on release/3.11.
#1149: fix(volc): volcengine account id

Automated cherry pick of #1149: fix(volc): volcengine account id

---

pkg/multicloud/objectstore/objectstore.go
pkg/multicloud/objectstore/s3cli/main.go

Cherry pick of #1151 on master.
#1151: fix: s3 cli support set sign version

Automated cherry pick of #1151: fix: s3 cli support set sign version

---

pkg/cloudprovider/objectstore.go

fix: ignore upload multipart offset
NONE

fix: ignore upload multipart offset

---

pkg/multicloud/esxi/storage.go
pkg/multicloud/esxi/template.go

Cherry pick of #1176 on release/3.11.
#1176: fix(esxi): skip not found host by storage

Automated cherry pick of #1176: fix(esxi): skip not found host by storage

---

pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/instance.go
pkg/multicloud/aliyun/shell/instance.go
pkg/multicloud/billing_base.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go
pkg/multicloud/qcloud/instance.go
pkg/multicloud/qcloud/shell/instance.go

fix(aliyun): support change vm billing type

---

pkg/multicloud/qcloud/waf.go

Cherry pick of #1195 on release/3.11.
#1195: fix(qcloud): waf instance id

Automated cherry pick of #1195: fix(qcloud): waf instance id

---

pkg/multicloud/qcloud/waf.go

Cherry pick of #1200 on release/3.11.10.
#1200: Revert "fix(qcloud): waf instance id"

Automated cherry pick of #1200: Revert "fix(qcloud): waf instance id"

---

pkg/multicloud/qcloud/waf.go

Cherry pick of #1203 on release/3.11.10.
#1203: fix(qcloud): waf domain id

Automated cherry pick of #1203: fix(qcloud): waf domain id

---

pkg/multicloud/esxi/host.go

Cherry pick of #1225 on release/3.11.
#1225: fix(esxi): ignore no default gateway host nic

Automated cherry pick of #1225: fix(esxi): ignore no default gateway host nic

---

pkg/multicloud/aws/image.go
pkg/multicloud/aws/instance.go

Cherry pick of #1241 on release/3.11.
#1241: fix(aws): avoid Invalid device name /dev/sda error

Automated cherry pick of #1241: fix(aws): avoid Invalid device name /dev/sda error

---

pkg/multicloud/qcloud/storage.go

Cherry pick of #1263 on release/3.11.
#1263: fix(qcloud): storage type hssd use system disk

Automated cherry pick of #1263: fix(qcloud): storage type hssd use system disk

---

pkg/multicloud/aws/storagecache.go

Cherry pick of #1277 on release/4.0.
#1277: fix(aws): avoid batch role create

Automated cherry pick of #1277: fix(aws): avoid batch role create

---

pkg/multicloud/aws/loadbalancerbackend.go
pkg/multicloud/aws/shell/backendgroup.go
pkg/multicloud/aws/shell/lb.go

Cherry pick of #1286 on release/3.11.
#1286: fix(aws): lb backend id

Automated cherry pick of #1286: fix(aws): lb backend id

---

pkg/cloudprovider/ssl.go

Cherry pick of #1384 on release/4.0.
#1384: fix: add zone id for ssl create

Automated cherry pick of #1384: fix: add zone id for ssl create

---

pkg/multicloud/google/eip.go

Cherry pick of #1387 on release/4.0.0.
#1387: fix(gcp): eip associate type

Automated cherry pick of #1387: fix(gcp): eip associate type

---

pkg/apis/compute/loadbalancer_const.go
pkg/cloudprovider/loadbalancerbackend.go

Cherry pick of #1419 on release/4.0.
#1419: fix: add lb backend type

Automated cherry pick of #1419: fix: add lb backend type

---

pkg/cloudprovider/cdn.go

Cherry pick of #1443 on release/4.0.
#1443: fix: add opts for cdn custom hostname

Automated cherry pick of #1443: fix: add opts for cdn custom hostname

---

pkg/multicloud/google/dbinstance.go

Cherry pick of #1478 on release/3.11.
#1478: fix(gcp): rds engine version

Automated cherry pick of #1478: fix(gcp): rds engine version

---

pkg/multicloud/aws/organizations.go

Cherry pick of #1514 on release/4.0.
#1514: fix(aws): master account id

Automated cherry pick of #1514: fix(aws): master account id

---

pkg/multicloud/qcloud/rds_sqlserver.go

Cherry pick of #1538 on release/3.11.
#1538: fix(qcloud): sync sqlserver expired time

Automated cherry pick of #1538: fix(qcloud): sync sqlserver expired time

---

pkg/multicloud/qcloud/monitor.go

Cherry pick of #1580 on release/4.0.
#1580: fix(qcloud): metric period 60s

Automated cherry pick of #1580: fix(qcloud): metric period 60s
