pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/qcloud/loadbalancer.go
pkg/multicloud/qcloud/loadbalancer_backend.go
pkg/multicloud/qcloud/loadbalancer_listener.go
pkg/multicloud/qcloud/loadbalancer_listenerrule.go

fix: remove yunion.io/x/onecloud/pkg/cloudcommon/db/lockman

---

pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

fix modelarts refresh get status
- release/3.9
cc @ioito

fix(cloudmux): modelarts refresh

---

pkg/cloudprovider/geoinfo.go

fix: geo equals

---

pkg/multicloud/remotefile/monitor.go
pkg/multicloud/remotefile/remotefile.go

fix remotefile metric 
- release/3.9
/cc @ioito

fix(cloudmux): remoteFile metric

---

pkg/multicloud/hcso/huawei.go

fix(region): hcso region cache

---

pkg/apis/compute/guest_const.go
pkg/multicloud/azure/instance.go
pkg/multicloud/google/instance.go
pkg/multicloud/hcs/instance.go
pkg/multicloud/hcso/instance.go
pkg/multicloud/huawei/instance.go
pkg/multicloud/instance_base.go

add guest power status
- release/3.9
/cc @ioito

fix(cloudmux):add guest power status

---

pkg/apis/compute/modelarts_pool.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

modelarts const status
- release/3.10
/cc @ioito

fix:modelarts status

---

pkg/multicloud/esxi/net_topology.go
pkg/multicloud/esxi/net_topology_pro.go

fix: do not probe esxi vm ip address
NONE

fix: do not probe esxi vm ip address

---

pkg/cloudprovider/modelarts_pool.go
pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/modelarts_pool.go

fix modelarts network no available bug
- release/3.10
/cc @ioito

fix(cloudmux): fix modelarts network no available bug

---

pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/instance.go
pkg/multicloud/hcs/port.go
pkg/multicloud/hcs/shell/port.go
pkg/multicloud/hcs/shell/securitygroup.go

fix(region): hcs misc fix

---

pkg/multicloud/hcs/disk.go
pkg/multicloud/hcs/instance.go

fix: hcs vm disks

---

pkg/multicloud/hcs/bucket.go
pkg/multicloud/hcs/region.go

fix(region): hcs bucket

---

pkg/multicloud/cloudpods/cloudpods.go

fix: cloudpods self manage check

---

pkg/multicloud/hcs/host.go

fix: hcs vm create

---

pkg/multicloud/hcs/natdtable.go
pkg/multicloud/hcs/port.go

fix(hcs): dnat create

---

pkg/multicloud/hcso/modelarts_sku.go
pkg/multicloud/huawei/modelarts_pool_sku.go

fix  modelarts sku glableId
- release/3.10
/cc @ioito

fix(cloudmux): fix modelarts sku glableId

---

pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/loadbalancerlistener.go
pkg/multicloud/hcs/loadbalancer.go
pkg/multicloud/hcs/shell/lb.go
pkg/multicloud/hcso/loadbalancer.go
pkg/multicloud/hcso/shell/loadbalancer.go
pkg/multicloud/huawei/loadbalancer.go
pkg/multicloud/huawei/shell/loadbalancer.go

fix: huawei aws lb

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

fix modelarts network status
- release/3.10
/cc @ioito

fix(cloudmux): fix modelarts network status

---

pkg/cloudprovider/cloudprovider.go

add cloudprovider.GetProcessorType
- release/3.10
/cc @ioito

fix(cloudmux): add cloudprovider.GetProcessorType

---

pkg/multicloud/hcs/disk.go

fix: hcs vm attach

---

pkg/multicloud/hcs/disk.go

fix: hcs vm disk attach

---

pkg/cloudprovider/loadbalancerbackendgroup.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/loadbalancerbackendgroup.go
pkg/multicloud/hcs/loadbalancer.go
pkg/multicloud/hcs/loadbalancer_backendgroup.go
pkg/multicloud/hcs/loadbalancer_listener.go
pkg/multicloud/hcs/shell/lb.go
pkg/multicloud/hcso/loadbalancer.go
pkg/multicloud/hcso/loadbalancer_backendgroup.go
pkg/multicloud/hcso/loadbalancer_listener.go
pkg/multicloud/hcso/shell/loadbalancer.go
pkg/multicloud/huawei/loadbalancer.go
pkg/multicloud/huawei/loadbalancer_backendgroup.go
pkg/multicloud/huawei/loadbalancer_listener.go
pkg/multicloud/huawei/shell/loadbalancer.go
pkg/multicloud/openstack/loadbalabcerpool.go
pkg/multicloud/openstack/loadbalbacer.go

fix: huawei elb backendgroup

---

pkg/multicloud/hcs/disk.go
pkg/multicloud/hcs/eip.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/instance.go
pkg/multicloud/hcs/job.go
pkg/multicloud/hcs/redis.go
pkg/multicloud/hcso/elasticcache_instance.go
scripts/cherry_pick_pull.sh

fix: hcs misc

---

pkg/multicloud/hcs/disk.go
pkg/multicloud/hcs/eip.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/instance.go
pkg/multicloud/hcs/job.go
pkg/multicloud/hcs/redis.go
pkg/multicloud/hcso/elasticcache_instance.go
scripts/cherry_pick_pull.sh

Cherry pick of #42 on release/3.10.
#42: fix: hcs misc

Automated cherry pick of #42: fix: hcs misc

---

pkg/multicloud/hcs/bucket.go
pkg/multicloud/hcs/image.go
pkg/multicloud/hcs/region.go
pkg/multicloud/hcs/shell/image.go
pkg/multicloud/hcs/storagecache.go

fix: hcs image import

---

pkg/multicloud/hcs/bucket.go
pkg/multicloud/hcs/image.go
pkg/multicloud/hcs/region.go
pkg/multicloud/hcs/shell/image.go
pkg/multicloud/hcs/storagecache.go

Cherry pick of #44 on release/3.10.
#44: fix: hcs image import

Automated cherry pick of #44: fix: hcs image import

---

pkg/multicloud/hcs/redis.go

fix(region): hcs redis create

---

pkg/multicloud/hcs/redis.go

Cherry pick of #46 on release/3.10.
#46: fix(region): hcs redis create

Automated cherry pick of #46: fix(region): hcs redis create

---

pkg/multicloud/hcs/disk.go

fix: hcs disk resize

---

pkg/multicloud/hcs/disk.go

Cherry pick of #48 on release/3.10.
#48: fix: hcs disk resize

Automated cherry pick of #48: fix: hcs disk resize

---

pkg/multicloud/hcs/bucket.go
pkg/multicloud/hcs/shell/bucket.go

fix: hcs bucket delete

---

pkg/multicloud/hcs/bucket.go
pkg/multicloud/hcs/shell/bucket.go

Cherry pick of #50 on release/3.10.
#50: fix: hcs bucket delete

Automated cherry pick of #50: fix: hcs bucket delete

---

pkg/multicloud/hcso/client/modules/manager_base.go

fix: hcso http retry

---

pkg/multicloud/hcso/client/modules/manager_base.go

Cherry pick of #52 on release/3.10.
#52: fix: hcso http retry

Automated cherry pick of #52: fix: hcso http retry

---

pkg/cloudprovider/resources.go
pkg/multicloud/remotefile/instance.go

add remotefile guest power status
- release/3.10
/cc @ioito

fix(cloudmux): add remotefile guest power status

---

pkg/multicloud/cloudpods/instance.go
pkg/multicloud/cloudpods/shell/instance.go

fix(cloudpods): vm vnc shell

---

pkg/multicloud/aws/instance.go

Cherry pick of #58 on release/3.10.
#58: fix: aws instance os_arch

Automated cherry pick of #58: fix: aws instance os_arch

---

pkg/apis/compute/network_const.go
pkg/multicloud/hcs/eip.go
pkg/multicloud/hcs/external_network.go
pkg/multicloud/hcs/external_vpc.go
pkg/multicloud/hcs/external_wire.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/region.go
pkg/multicloud/hcs/shell/eip.go
pkg/multicloud/hcs/shell/network.go
pkg/multicloud/hcs/shell/vpc.go
pkg/multicloud/hcs/shell/vpc_peer.go
pkg/multicloud/hcs/vpc.go
pkg/multicloud/hcs/vpc_peering.go

fix(hcs): vpc peer

---

pkg/apis/compute/network_const.go
pkg/multicloud/hcs/eip.go
pkg/multicloud/hcs/external_network.go
pkg/multicloud/hcs/external_vpc.go
pkg/multicloud/hcs/external_wire.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/region.go
pkg/multicloud/hcs/shell/eip.go
pkg/multicloud/hcs/shell/network.go
pkg/multicloud/hcs/shell/vpc.go
pkg/multicloud/hcs/shell/vpc_peer.go
pkg/multicloud/hcs/vpc.go
pkg/multicloud/hcs/vpc_peering.go

Cherry pick of #60 on release/3.10.
#60: fix(hcs): vpc peer

Automated cherry pick of #60: fix(hcs): vpc peer

---

pkg/multicloud/hcs/shell/vpc_peer.go

fix(hcs); peer shell

---

pkg/multicloud/hcs/shell/vpc_peer.go

Cherry pick of #62 on release/3.10.
#62: fix(hcs); peer shell

Automated cherry pick of #62: fix(hcs); peer shell

---

cmd/hcscli/main.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/monitor.go
pkg/multicloud/hcs/provider/provider.go
pkg/multicloud/hcso/client/auth/signer.go

fix(hcs): metric

---

cmd/hcscli/main.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcs/monitor.go
pkg/multicloud/hcs/provider/provider.go
pkg/multicloud/hcso/client/auth/signer.go

Cherry pick of #64 on release/3.10.
#64: fix(hcs): metric

Automated cherry pick of #64: fix(hcs): metric

---

pkg/multicloud/hcs/monitor.go

fix(hcs): remove debug log

---

pkg/multicloud/hcs/monitor.go

Cherry pick of #66 on release/3.10.
#66: fix(hcs): remove debug log

Automated cherry pick of #66: fix(hcs): remove debug log

---

pkg/multicloud/hcs/external_vpc.go

fix(hcs): vpc emulated

---

pkg/multicloud/hcs/external_vpc.go

Cherry pick of #68 on release/3.10.
#68: fix(hcs): vpc emulated

Automated cherry pick of #68: fix(hcs): vpc emulated

---

pkg/multicloud/hcs/eip.go
pkg/multicloud/hcs/shell/eip.go

fix(hcs): hcs eip addr

---

pkg/multicloud/hcs/eip.go
pkg/multicloud/hcs/shell/eip.go

Cherry pick of #70 on release/3.10.
#70: fix(hcs): hcs eip addr

Automated cherry pick of #70: fix(hcs): hcs eip addr

---

pkg/cloudprovider/consts.go
pkg/multicloud/aws/aws.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcso/huawei.go
pkg/multicloud/huawei/huawei.go

fix: add capability for vpc peer

---

pkg/cloudprovider/consts.go
pkg/multicloud/aws/aws.go
pkg/multicloud/hcs/hcs.go
pkg/multicloud/hcso/huawei.go
pkg/multicloud/huawei/huawei.go

Cherry pick of #72 on release/3.10.
#72: fix: add capability for vpc peer

Automated cherry pick of #72: fix: add capability for vpc peer

---

pkg/multicloud/remotefile/host.go

Cherry pick of #74 on release/3.10.
#74: fix(cloudmux):add remotefile host.wire

Automated cherry pick of #74: fix(cloudmux):add remotefile host.wire

---

pkg/apis/compute/cloudaccount_const.go

add: hcsop const

---

pkg/apis/compute/cloudaccount_const.go

Cherry pick of #76 on release/3.10.
#76: add: hcsop const

Automated cherry pick of #76: add: hcsop const

---

pkg/apis/compute/guest_const.go
pkg/apis/compute/host_const.go

Cherry pick of #78 on release/3.10.
#78: fix: add hcsop const

Automated cherry pick of #78: fix: add hcsop const

---

pkg/cloudprovider/metrics.go

fix: add wire metric type

---

pkg/cloudprovider/metrics.go

Cherry pick of #82 on release/3.10.
#82: fix: add wire metric type

Automated cherry pick of #82: fix: add wire metric type

---

pkg/multicloud/cloudpods/instance.go

fix cloudpods metric
<!--
- release/3.10
/cc @ioito

fix(cloudmux): fix cloudpods metric

---

pkg/multicloud/cloudpods/instance.go

Cherry pick of #84 on release/3.10.
#84: fix(cloudmux): fix cloudpods metric

Automated cherry pick of #84: fix(cloudmux): fix cloudpods metric

---

pkg/cloudprovider/metrics.go

fix: add wire metric

---

pkg/cloudprovider/metrics.go

Cherry pick of #87 on release/3.10.
#87: fix: add wire metric

Automated cherry pick of #87: fix: add wire metric

---

pkg/multicloud/aws/aws.go

fix(aws): account read only

---

pkg/multicloud/aws/aws.go

Cherry pick of #91 on release/3.10.
#91: fix(aws): account read only

Automated cherry pick of #91: fix(aws): account read only

---

pkg/multicloud/remotefile/remotefile.go

Cherry pick of #93 on release/3.10.
#93: fix(cloudmux): 修改remotefile的getMetric的并发bug

Automated cherry pick of #93: fix(cloudmux): 修改remotefile的getMetric的并发bug

---

pkg/multicloud/huawei/monitor.go

fix(huawei): huawei rds metric params

---

pkg/multicloud/aliyun/elasticcache_instance.go

- release/3.10
/area aliyun
/cc @zexi

fix(aliyun): redis create params

---

pkg/multicloud/huawei/monitor.go

Cherry pick of #95 on release/3.10.
#95: fix(huawei): huawei rds metric params

Automated cherry pick of #95: fix(huawei): huawei rds metric params

---

pkg/multicloud/aliyun/elasticcache_instance.go

Cherry pick of #97 on release/3.10.
#97: fix(aliyun): redis create params

Automated cherry pick of #97: fix(aliyun): redis create params

---

pkg/multicloud/hcso/huawei.go
pkg/multicloud/huawei/huawei.go

fix(huawei): api request limit

---

pkg/multicloud/hcso/huawei.go
pkg/multicloud/huawei/huawei.go

Cherry pick of #99 on release/3.10.
#99: fix(huawei): api request limit

Automated cherry pick of #99: fix(huawei): api request limit

---

pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

huawei & hcso modelarts cidr diff
<!--
- release/3.10
/cc @ioito

fix(cloudmux): modelarts cidr diff

---

pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

Cherry pick of #102 on release/3.10.
#102: fix(cloudmux): modelarts cidr diff

Automated cherry pick of #102: fix(cloudmux): modelarts cidr diff

---

pkg/multicloud/openstack/openstack.go

fix(openstack): api version

---

pkg/multicloud/openstack/openstack.go

Cherry pick of #104 on release/3.10.
#104: fix(openstack): api version

Automated cherry pick of #104: fix(openstack): api version

---

pkg/multicloud/azure/region.go

fix(azure): eip sync

---

pkg/multicloud/azure/region.go

Cherry pick of #114 on release/3.10.
#114: fix(azure): eip sync

Automated cherry pick of #114: fix(azure): eip sync

---

pkg/multicloud/esxi/virtualmachine.go

fix(vmware): add tags sync

---

pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #116 on release/3.10.
#116: fix(vmware): add tags sync

Automated cherry pick of #116: fix(vmware): add tags sync

---

pkg/multicloud/aliyun/aliyun.go
pkg/multicloud/aliyun/elastic_search.go
pkg/multicloud/aliyun/kafka.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/resource_tags.go
pkg/multicloud/aliyun/shell/resource_tag.go
pkg/multicloud/qcloud/elastic_search.go
pkg/multicloud/qcloud/kafka.go

feat(resource tag):sync resource tag

feat(resource tag):sync resource tag

---

pkg/multicloud/aliyun/project.go

fix(aliyun): resource group tags

---

pkg/multicloud/aliyun/project.go

Cherry pick of #120 on release/3.10.
#120: fix(aliyun): resource group tags

Automated cherry pick of #120: fix(aliyun): resource group tags

---

pkg/multicloud/azure/azure.go

fix(azure): project id

---

pkg/multicloud/azure/azure.go

Cherry pick of #122 on release/3.10.
#122: fix(azure): project id

Automated cherry pick of #122: fix(azure): project id

---

pkg/multicloud/esxi/monitor.go
pkg/multicloud/esxi/shell/monitor.go
pkg/multicloud/esxi/shell/utils.go
pkg/multicloud/esxi/storagecache.go
pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #124 on release/3.10.
#124: fix: esxi virtualmachine missing datastore property

Automated cherry pick of #124: fix: esxi virtualmachine missing datastore property

---

pkg/multicloud/aliyun/elasticcache_instance.go

Cherry pick of #126 on release/3.10.
#126: fix(aliyun): redis create params

Automated cherry pick of #126: fix(aliyun): redis create params

---

pkg/cloudprovider/waitstatus.go
pkg/multicloud/qcloud/cdn.go

- release/3.10
/area qcloud
/cc @zexi

fix(qcloud): cdn domain create

---

pkg/cloudprovider/waitstatus.go
pkg/multicloud/qcloud/cdn.go

Cherry pick of #128 on release/3.10.
#128: fix(qcloud): cdn domain create

Automated cherry pick of #128: fix(qcloud): cdn domain create

---

pkg/multicloud/aliyun/zone.go

- release/3.10
/area aliyun
/cc @zexi

fix(aliyun): system disk storage type

---

pkg/apis/compute/loadbalancer_const.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/loadbalancerbackend.go
pkg/multicloud/aws/loadbalancerbackendgroup.go
pkg/multicloud/aws/loadbalancerlistener.go
pkg/multicloud/aws/loadbalancerlistenerrule.go
pkg/multicloud/aws/region.go
pkg/multicloud/aws/shell/backendgroup.go
pkg/multicloud/aws/shell/lb.go
pkg/multicloud/aws/shell/listener.go

fix(aws): optimized lb

---

pkg/apis/compute/loadbalancer_const.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/loadbalancerbackend.go
pkg/multicloud/aws/loadbalancerbackendgroup.go
pkg/multicloud/aws/loadbalancerlistener.go
pkg/multicloud/aws/loadbalancerlistenerrule.go
pkg/multicloud/aws/region.go
pkg/multicloud/aws/shell/backendgroup.go
pkg/multicloud/aws/shell/lb.go
pkg/multicloud/aws/shell/listener.go

Cherry pick of #132 on release/3.10.
#132: fix(aws): optimized lb

Automated cherry pick of #132: fix(aws): optimized lb

---

pkg/multicloud/aliyun/zone.go

Cherry pick of #130 on release/3.10.
#130: fix(aliyun): system disk storage type

Automated cherry pick of #130: fix(aliyun): system disk storage type

---

pkg/multicloud/host_base.go

fix(common): default host cpu arch is x86_64

---

pkg/multicloud/google/securitygroup.go

fix(google): secgroup create

---

pkg/multicloud/google/securitygroup.go

Cherry pick of #137 on release/3.10.
#137: fix(google): secgroup create

Automated cherry pick of #137: fix(google): secgroup create

---

pkg/multicloud/qcloud/region.go
pkg/multicloud/qcloud/shell/elasticcache.go

fix(qcloud): skip unsupport memcache

---

pkg/multicloud/bingocloud/instance.go

Cherry pick of #141 on release/3.10.
#141: feat(bingocloud)：implemented some instance interfaces

Automated cherry pick of #141: feat(bingocloud)：implemented some instance interfaces

---

pkg/multicloud/aliyun/instance.go

fix(aliyun): vnc os name

---

pkg/multicloud/aliyun/instance.go

Cherry pick of #143 on release/3.10.
#143: fix(aliyun): vnc os name

Automated cherry pick of #143: fix(aliyun): vnc os name

---

pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/virtualmachine.go

fix(vmware): vm migrate

---

pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #145 on release/3.10.
#145: fix(vmware): vm migrate

Automated cherry pick of #145: fix(vmware): vm migrate

---

pkg/multicloud/esxi/vdisk.go

fix(vmware): disk storage id

---

pkg/multicloud/esxi/vdisk.go

Cherry pick of #147 on release/3.10.
#147: fix(vmware): disk storage id

Automated cherry pick of #147: fix(vmware): disk storage id

---

pkg/multicloud/qcloud/loadbalancer.go

Cherry pick of #149 on release/3.10.
#149: fix(qcloud): lb limit offset

Automated cherry pick of #149: fix(qcloud): lb limit offset

---

pkg/multicloud/huawei/natgateway.go

fix(huawei): nat eip sync

---

pkg/multicloud/huawei/natgateway.go

Cherry pick of #151 on release/3.10.
#151: fix(huawei): nat eip sync

Automated cherry pick of #151: fix(huawei): nat eip sync

---

pkg/multicloud/openstack/instance.go

- release/3.10
/area openstack

fix(openstack): vm refresh

---

pkg/multicloud/openstack/instance.go

Cherry pick of #154 on release/3.10.
#154: fix(openstack): vm refresh

Automated cherry pick of #154: fix(openstack): vm refresh

---

pkg/multicloud/qcloud/loadbalancer.go
pkg/multicloud/qcloud/loadbalancer_listener.go
pkg/multicloud/qcloud/loadbalancer_listenerrule.go
pkg/multicloud/qcloud/shell/loadbalancer.go

fix(qcloud): qcloud lb listener

---

pkg/multicloud/qcloud/loadbalancer.go
pkg/multicloud/qcloud/loadbalancer_listener.go
pkg/multicloud/qcloud/loadbalancer_listenerrule.go
pkg/multicloud/qcloud/shell/loadbalancer.go

Cherry pick of #156 on release/3.10.
#156: fix(qcloud): qcloud lb listener

Automated cherry pick of #156: fix(qcloud): qcloud lb listener

---

pkg/multicloud/esxi/manager.go

fix(esxi): timeout

---

pkg/multicloud/esxi/manager.go

Cherry pick of #158 on release/3.10.
#158: fix(esxi): timeout

Automated cherry pick of #158: fix(esxi): timeout

---

pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/storage.go
pkg/multicloud/esxi/virtualmachine.go

fix(esxi): rebuild root

---

pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/storage.go
pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #160 on release/3.10.
#160: fix(esxi): rebuild root

Automated cherry pick of #160: fix(esxi): rebuild root

---

pkg/cloudprovider/cloudprovider.go
pkg/multicloud/azure/provider/provider.go
pkg/multicloud/huawei/provider/provider.go

fix(huawei): clirc region

---

pkg/cloudprovider/cloudprovider.go
pkg/multicloud/azure/provider/provider.go
pkg/multicloud/huawei/provider/provider.go

Cherry pick of #162 on release/3.10.
#162: fix(huawei): clirc region

Automated cherry pick of #162: fix(huawei): clirc region

---

pkg/multicloud/aliyun/image.go
pkg/multicloud/aliyun/storagecache.go

fix(aliyun): aliyun shared image sync

---

pkg/multicloud/aliyun/image.go
pkg/multicloud/aliyun/storagecache.go

Cherry pick of #164 on release/3.10.
#164: fix(aliyun): aliyun shared image sync

Automated cherry pick of #164: fix(aliyun): aliyun shared image sync

---

pkg/cloudprovider/errors.go
pkg/cloudprovider/securitygroup.go
pkg/multicloud/bingocloud/bingo.go
pkg/multicloud/bingocloud/cluster.go
pkg/multicloud/bingocloud/disk.go
pkg/multicloud/bingocloud/eip.go
pkg/multicloud/bingocloud/host.go
pkg/multicloud/bingocloud/image.go
pkg/multicloud/bingocloud/instance.go
pkg/multicloud/bingocloud/instance_snapshot.go
pkg/multicloud/bingocloud/instance_type.go
pkg/multicloud/bingocloud/instancenic.go
pkg/multicloud/bingocloud/monitor.go
pkg/multicloud/bingocloud/network.go
pkg/multicloud/bingocloud/node.go
pkg/multicloud/bingocloud/region.go
pkg/multicloud/bingocloud/securitygroup.go
pkg/multicloud/bingocloud/snapshot.go
pkg/multicloud/bingocloud/storage.go
pkg/multicloud/bingocloud/utils.go
pkg/multicloud/bingocloud/vpc.go
pkg/multicloud/bingocloud/wire.go
pkg/multicloud/bingocloud/zone.go

- CreateVM
- Sku
- Eip
- Snapshot
- InstanceSnapshot
- SecurityGroup
支持品高云创建虚拟机，以及相关快照管理、安全组同步的操作。
- release/3.10

feat(bingocloud)：implemented some instance interfaces

---

pkg/cloudprovider/errors.go
pkg/cloudprovider/securitygroup.go
pkg/multicloud/bingocloud/bingo.go
pkg/multicloud/bingocloud/cluster.go
pkg/multicloud/bingocloud/disk.go
pkg/multicloud/bingocloud/eip.go
pkg/multicloud/bingocloud/host.go
pkg/multicloud/bingocloud/image.go
pkg/multicloud/bingocloud/instance.go
pkg/multicloud/bingocloud/instance_snapshot.go
pkg/multicloud/bingocloud/instance_type.go
pkg/multicloud/bingocloud/instancenic.go
pkg/multicloud/bingocloud/monitor.go
pkg/multicloud/bingocloud/network.go
pkg/multicloud/bingocloud/node.go
pkg/multicloud/bingocloud/region.go
pkg/multicloud/bingocloud/securitygroup.go
pkg/multicloud/bingocloud/snapshot.go
pkg/multicloud/bingocloud/storage.go
pkg/multicloud/bingocloud/utils.go
pkg/multicloud/bingocloud/vpc.go
pkg/multicloud/bingocloud/wire.go
pkg/multicloud/bingocloud/zone.go

Cherry pick of #168 on release/3.10.
#168: feat(bingocloud)：implemented some instance interfaces

Automated cherry pick of #168: feat(bingocloud)：implemented some instance interfaces

---

pkg/cloudprovider/cdn.go
pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/cdn.go
pkg/multicloud/cdn_domain_base.go
pkg/multicloud/qcloud/cdn.go

fix(qcloud): cdn attr sync

---

pkg/cloudprovider/cdn.go
pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/cdn.go
pkg/multicloud/cdn_domain_base.go
pkg/multicloud/qcloud/cdn.go

Cherry pick of #171 on release/3.10.
#171: fix(qcloud): cdn attr sync

Automated cherry pick of #171: fix(qcloud): cdn attr sync

---

pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/cdn.go
pkg/multicloud/qcloud/cdn.go

fix(qcloud): cdn project id

---

pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/cdn.go
pkg/multicloud/qcloud/cdn.go

Cherry pick of #173 on release/3.10.
#173: fix(qcloud): cdn project id

Automated cherry pick of #173: fix(qcloud): cdn project id

---

pkg/multicloud/huawei/huawei.go

fix(huawei): metric skip read only check

---

pkg/multicloud/huawei/huawei.go

Cherry pick of #175 on release/3.10.
#175: fix(huawei): metric skip read only check

Automated cherry pick of #175: fix(huawei): metric skip read only check

---

pkg/multicloud/aws/aws.go

fix(aws): s3 skip req check

---

pkg/multicloud/aws/aws.go

Cherry pick of #177 on release/3.10.
#177: fix(aws): s3 skip req check

Automated cherry pick of #177: fix(aws): s3 skip req check

---

pkg/multicloud/huawei/huawei.go

fix(huawei): req check

---

pkg/multicloud/huawei/huawei.go

Cherry pick of #179 on release/3.10.
#179: fix(huawei): req check

Automated cherry pick of #179: fix(huawei): req check

---

pkg/multicloud/google/storagecache.go

fix(google): gcp storage cache

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/google/latitude_and_longitude.go
pkg/multicloud/google/storage.go

fix(gcp): google storage id

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/google/latitude_and_longitude.go
pkg/multicloud/google/storage.go

Cherry pick of #185 on release/3.10.
#185: fix(gcp): google storage id

Automated cherry pick of #185: fix(gcp): google storage id

---

pkg/multicloud/apsara/apsara.go
pkg/multicloud/apsara/monitor.go

fix(apsara): metric list

---

pkg/multicloud/apsara/apsara.go
pkg/multicloud/apsara/monitor.go

Cherry pick of #187 on release/3.10.
#187: fix(apsara): metric list

Automated cherry pick of #187: fix(apsara): metric list

---

pkg/multicloud/aliyun/loadbalancer.go

fix(aliyun): lb tags

---

pkg/multicloud/aliyun/loadbalancer.go

Cherry pick of #189 on release/3.10.
#189: fix(aliyun): lb tags

Automated cherry pick of #189: fix(aliyun): lb tags

---

pkg/multicloud/azure/instance.go

fix(azure): rebuild root

---

pkg/multicloud/azure/instance.go

Cherry pick of #191 on release/3.10.
#191: fix(azure): rebuild root

Automated cherry pick of #191: fix(azure): rebuild root

---

pkg/multicloud/esxi/template.go

fix(vmware): esxi template image root size

---

pkg/multicloud/openstack/openstack.go

fix(openstack): compute api version

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/monitor.go
pkg/multicloud/hcso/shell/monitor.go

add HCSO monitor

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/monitor.go
pkg/multicloud/hcso/shell/monitor.go

Cherry pick of #201 on release/3.10.
#201: add HCSO monitor

Automated cherry pick of #201: add HCSO monitor

---

pkg/multicloud/apsara/organization.go

fix(apsara): projects

---

pkg/multicloud/apsara/organization.go

Cherry pick of #203 on release/3.10.
#203: fix(apsara): projects

Automated cherry pick of #203: fix(apsara): projects

---

pkg/multicloud/hcso/monitor.go

fix hcso rds monitor

---

pkg/multicloud/hcso/monitor.go

Cherry pick of #205 on release/3.10.
#205: fix hcso rds monitor

Automated cherry pick of #205: fix hcso rds monitor

---

pkg/multicloud/hcso/monitor.go

addHcsoEcsMemDisk

---

pkg/multicloud/aws/dnshostedzone.go

fix(aws): dns zone name

---

pkg/multicloud/aws/dnshostedzone.go

Cherry pick of #211 on release/3.10.
#211: fix(aws): dns zone name

Automated cherry pick of #211: fix(aws): dns zone name

---

pkg/multicloud/bingocloud/account.go
pkg/multicloud/bingocloud/bingo.go
pkg/multicloud/bingocloud/disk.go
pkg/multicloud/bingocloud/instance.go
pkg/multicloud/bingocloud/instance_snapshot.go
pkg/multicloud/bingocloud/provider/provider.go
pkg/multicloud/bingocloud/quotas.go
pkg/multicloud/bingocloud/region.go
pkg/multicloud/bingocloud/securitygroup.go
pkg/multicloud/bingocloud/snapshot.go
pkg/multicloud/bingocloud/storage.go

Cherry pick of #195 on release/3.10.
#195: Feature/implement bingocloud

Automated cherry pick of #195: Feature/implement bingocloud

---

pkg/multicloud/remotefile/region.go

fix(remote): fixGetIBucketById

---

pkg/multicloud/remotefile/region.go

Cherry pick of #213 on release/3.10.
#213: fix(remote): fixGetIBucketById

Automated cherry pick of #213: fix(remote): fixGetIBucketById

---

pkg/multicloud/aliyun/disk.go
pkg/multicloud/apsara/disk.go

fix(aliyun): disk snapshot sync

---

pkg/multicloud/aliyun/disk.go
pkg/multicloud/apsara/disk.go

Cherry pick of #215 on release/3.10.
#215: fix(aliyun): disk snapshot sync

Automated cherry pick of #215: fix(aliyun): disk snapshot sync

---

pkg/multicloud/ctyun/ctyun.go
pkg/multicloud/jdcloud/balance.go

Cherry pick of #217 on release/3.10.
#217: fix jdcloud and ctyun accountConnectTest

Automated cherry pick of #217: fix jdcloud and ctyun accountConnectTest

---

pkg/multicloud/hcs/hcs.go

Cherry pick of #220 on release/3.10.
#220: fix(hcs): hcs url

Automated cherry pick of #220: fix(hcs): hcs url

---

pkg/multicloud/hcs/hcs.go

fix(hcs): auth url

---

pkg/multicloud/hcs/hcs.go

Cherry pick of #222 on release/3.10.
#222: fix(hcs): auth url

Automated cherry pick of #222: fix(hcs): auth url

---

pkg/multicloud/hcs/hcs.go

fix(hcs): avoid panic

---

pkg/multicloud/hcs/hcs.go

Cherry pick of #224 on release/3.10.
#224: fix(hcs): avoid panic

Automated cherry pick of #224: fix(hcs): avoid panic

---

pkg/cloudprovider/metrics.go
pkg/multicloud/aliyun/monitor.go
pkg/multicloud/apsara/monitor.go

fix(apsara): add metric

---

pkg/cloudprovider/metrics.go
pkg/multicloud/aliyun/monitor.go
pkg/multicloud/apsara/monitor.go

Cherry pick of #226 on release/3.10.
#226: fix(apsara): add metric

Automated cherry pick of #226: fix(apsara): add metric

---

pkg/cloudprovider/resources.go
pkg/multicloud/bingocloud/instance_type.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/google/loadbalancer_backend.go
pkg/multicloud/google/loadbalancer_backendgroup.go
pkg/multicloud/google/loadbalancer_listener.go
pkg/multicloud/google/loadbalancer_listenerrule.go
pkg/multicloud/google/network.go
pkg/multicloud/google/resourcebase.go
pkg/multicloud/remotefile/instance.go
pkg/multicloud/remotefile/projects.go
pkg/multicloud/remotefile/resource.go
pkg/multicloud/resource_base.go

- release/3.10
/cc @ioito @zexi  @swordqiu

add ICloudResource GetDescription

---

pkg/cloudprovider/resources.go
pkg/multicloud/bingocloud/instance_type.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/google/loadbalancer_backend.go
pkg/multicloud/google/loadbalancer_backendgroup.go
pkg/multicloud/google/loadbalancer_listener.go
pkg/multicloud/google/loadbalancer_listenerrule.go
pkg/multicloud/google/network.go
pkg/multicloud/google/resourcebase.go
pkg/multicloud/remotefile/instance.go
pkg/multicloud/remotefile/projects.go
pkg/multicloud/remotefile/resource.go
pkg/multicloud/resource_base.go

Cherry pick of #219 on release/3.10.
#219: add ICloudResource GetDescription

Automated cherry pick of #219: add ICloudResource GetDescription

---

pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

- release/3.10
/cc @ioito @zexi @swordqiu

fix(hcsocli): fix modelarts refresh bug

---

pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

Cherry pick of #232 on release/3.10.
#232: fix(hcsocli): fix modelarts refresh bug

Automated cherry pick of #232: fix(hcsocli): fix modelarts refresh bug

---

pkg/cloudprovider/metrics.go
pkg/multicloud/hcso/monitor.go

fix(hcsocli): add slb monitor

---

pkg/cloudprovider/metrics.go
pkg/multicloud/hcso/monitor.go

Cherry pick of #234 on release/3.10.
#234: fix(hcsocli): add slb monitor

Automated cherry pick of #234: fix(hcsocli): add slb monitor

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

- release/3.10
/cc @ioito  @zexi

fix(hcsocli): fix hcso\huawei modelarts getStatus and refresh

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

Cherry pick of #236 on release/3.10.
#236: fix(hcsocli): fix hcso\huawei modelarts getStatus and refresh

Automated cherry pick of #236: fix(hcsocli): fix hcso\huawei modelarts getStatus and refresh

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

- release/3.10
/cc @ioito @zexi @swordqiu

fix(hcsocli): request akSign

---

pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go

Cherry pick of #238 on release/3.10.
#238: fix(hcsocli): request akSign

Automated cherry pick of #238: fix(hcsocli): request akSign

---

pkg/multicloud/apsara/monitor.go

fix(apsara): bucket size metric

---

pkg/multicloud/apsara/monitor.go

Cherry pick of #240 on release/3.10.
#240: fix(apsara): bucket size metric

Automated cherry pick of #240: fix(apsara): bucket size metric

---

pkg/multicloud/apsara/monitor.go

fix(apsara): process number

---

pkg/multicloud/esxi/monitor.go
pkg/multicloud/esxi/shell/monitor.go

fix(esxi): vm disk usage

---

pkg/multicloud/esxi/monitor.go
pkg/multicloud/esxi/shell/monitor.go

Cherry pick of #244 on release/3.10.
#244: fix(esxi): vm disk usage

Automated cherry pick of #244: fix(esxi): vm disk usage

---

pkg/cloudprovider/metrics.go
pkg/multicloud/bingocloud/monitor.go

fix(bingo): metric

---

pkg/cloudprovider/metrics.go
pkg/multicloud/bingocloud/monitor.go

Cherry pick of #246 on release/3.10.
#246: fix(bingo): metric

Automated cherry pick of #246: fix(bingo): metric

---

pkg/cloudprovider/errors.go
pkg/multicloud/aliyun/provider/provider.go

fix(aliyun): aksk error

---

pkg/cloudprovider/errors.go
pkg/multicloud/aliyun/provider/provider.go

Cherry pick of #248 on release/3.10.
#248: fix(aliyun): aksk error

Automated cherry pick of #248: fix(aliyun): aksk error

---

pkg/multicloud/openstack/openstack.go

- release/3.10
/area openstack

fix(openstack): create keypair

---

pkg/multicloud/openstack/openstack.go

Cherry pick of #252 on release/3.10.
#252: fix(openstack): create keypair

Automated cherry pick of #252: fix(openstack): create keypair

---

pkg/multicloud/openstack/instancenic.go

- release/3.10
/area openstack

fix(openstack): openstack vm ip

---

pkg/multicloud/openstack/instancenic.go

Cherry pick of #254 on release/3.10.
#254: fix(openstack): openstack vm ip

Automated cherry pick of #254: fix(openstack): openstack vm ip

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/resources.go
pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/hcso/shell/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go
pkg/multicloud/huawei/shell/modelarts_pool.go
pkg/multicloud/region_base.go

<!--
- release/3.10
/cc @ioito

fix(hcsocli): fixModelartsRefreshForCreate

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/resources.go
pkg/multicloud/hcso/hcso.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/hcso/shell/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go
pkg/multicloud/huawei/shell/modelarts_pool.go
pkg/multicloud/region_base.go

Cherry pick of #258 on release/3.10.
#258: fix(hcsocli): fixModelartsRefreshForCreate

Automated cherry pick of #258: fix(hcsocli): fixModelartsRefreshForCreate

---

pkg/multicloud/esxi/ovf.go
pkg/multicloud/esxi/storage.go

fix(esxi): inject ovf file

---

pkg/multicloud/esxi/ovf.go
pkg/multicloud/esxi/storage.go

Cherry pick of #262 on release/3.10.
#262: fix(esxi): inject ovf file

Automated cherry pick of #262: fix(esxi): inject ovf file

---

pkg/cloudprovider/cloudprovider.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go
pkg/multicloud/region_base.go

<!--
- release/3.10
/cc @ioito

fix(hcsocli): add modelarts get status message

---

pkg/cloudprovider/cloudprovider.go
pkg/multicloud/hcso/modelarts.go
pkg/multicloud/huawei/modelarts_pool.go
pkg/multicloud/region_base.go

Cherry pick of #264 on release/3.10.
#264: fix(hcsocli): add modelarts get status message

Automated cherry pick of #264: fix(hcsocli): add modelarts get status message

---

pkg/multicloud/remotefile/region.go

fix: remotefile

---

pkg/multicloud/remotefile/region.go

Cherry pick of #266 on release/3.10.
#266: fix: remotefile

Automated cherry pick of #266: fix: remotefile

---

pkg/cloudprovider/metrics.go
pkg/multicloud/azure/monitor.go

fix(azure): support switch pull disk usage metric

---

pkg/cloudprovider/metrics.go
pkg/multicloud/azure/monitor.go

Cherry pick of #268 on release/3.10.
#268: fix(azure): support switch pull disk usage metric

Automated cherry pick of #268: fix(azure): support switch pull disk usage metric

---

pkg/multicloud/proxmox/host.go
pkg/multicloud/proxmox/instance.go

fix(proxmox): misc fix

---

pkg/multicloud/proxmox/host.go
pkg/multicloud/proxmox/instance.go

Cherry pick of #270 on release/3.10.
#270: fix(proxmox): misc fix

Automated cherry pick of #270: fix(proxmox): misc fix

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/aws/latitude_and_longitude.go
pkg/multicloud/aws/region.go

fix(aws): aws region meta

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/aws/latitude_and_longitude.go
pkg/multicloud/aws/region.go

Cherry pick of #272 on release/3.10.
#272: fix(aws): aws region meta

Automated cherry pick of #272: fix(aws): aws region meta

---

pkg/multicloud/aws/elasticache_instance.go
pkg/multicloud/aws/region.go

fix(aws): redis tags

---

pkg/multicloud/aws/elasticache_instance.go
pkg/multicloud/aws/region.go

Cherry pick of #277 on release/3.10.
#277: fix(aws): redis tags

Automated cherry pick of #277: fix(aws): redis tags

---

pkg/multicloud/proxmox/instance.go

fix(proxmox): panic

---

pkg/multicloud/proxmox/instance.go

Cherry pick of #279 on release/3.10.
#279: fix(proxmox): panic

Automated cherry pick of #279: fix(proxmox): panic

---

pkg/multicloud/azure/securitygroup.go

fix(region): avoid div zero

---

pkg/multicloud/azure/securitygroup.go

Cherry pick of #281 on release/3.10.
#281: fix(region): avoid div zero

Automated cherry pick of #281: fix(region): avoid div zero

---

pkg/multicloud/jdcloud/host.go
pkg/multicloud/jdcloud/region.go
pkg/multicloud/jdcloud/zone.go

- release/3.10
/area region
/cc @zexi

fix(jdcloud): sync jdcloud host name

---

pkg/multicloud/jdcloud/host.go
pkg/multicloud/jdcloud/region.go
pkg/multicloud/jdcloud/zone.go

Cherry pick of #283 on release/3.10.
#283: fix(jdcloud): sync jdcloud host name

Automated cherry pick of #283: fix(jdcloud): sync jdcloud host name

---

pkg/apis/compute/kube_cluster.go
pkg/cloudprovider/kube_cluster.go
pkg/cloudprovider/resources.go
pkg/cloudprovider/waitstatus.go
pkg/multicloud/aliyun/kube_cluster.go
pkg/multicloud/aliyun/kube_node_pools.go
pkg/multicloud/aws/aws.go
pkg/multicloud/aws/aws_invoke.go
pkg/multicloud/aws/aws_request.go
pkg/multicloud/aws/eks.go
pkg/multicloud/aws/eks_node_group.go
pkg/multicloud/aws/iam_role.go
pkg/multicloud/aws/region.go
pkg/multicloud/aws/shell/eks.go
pkg/multicloud/aws/shell/eks_nodegroup.go
pkg/multicloud/aws/shell/iam_role.go
pkg/multicloud/azure/kube_cluster.go
pkg/multicloud/azure/kube_node_pools.go
pkg/multicloud/qcloud/kube_clusters.go
pkg/multicloud/qcloud/kube_node_pools.go
pkg/multicloud/region_base.go

fix(aws): support eks

---

pkg/multicloud/aws/eks.go

fix(aws): eks kubeconfig

---

pkg/multicloud/aws/aws.go

fix(aws): capability

---

pkg/multicloud/aws/dbinstance.go
pkg/multicloud/aws/elasticache_instance.go
pkg/multicloud/aws/instance.go
pkg/multicloud/aws/utils.go

fix(aws): tag index

---

pkg/multicloud/aws/dbinstance.go
pkg/multicloud/aws/elasticache_instance.go
pkg/multicloud/aws/instance.go
pkg/multicloud/aws/utils.go

Cherry pick of #289 on release/3.10.
#289: fix(aws): tag index

Automated cherry pick of #289: fix(aws): tag index

---

pkg/cloudprovider/network.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/network.go
pkg/multicloud/aws/wire.go

fix(aws): network public ip

---

pkg/cloudprovider/network.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/network.go
pkg/multicloud/aws/wire.go

Cherry pick of #291 on release/3.10.
#291: fix(aws): network public ip

Automated cherry pick of #291: fix(aws): network public ip

---

pkg/multicloud/remotefile/disk.go
pkg/multicloud/remotefile/instance.go

fix(remotefile): fix GetIDisks storage

---

pkg/multicloud/remotefile/disk.go
pkg/multicloud/remotefile/instance.go

Cherry pick of #293 on release/3.10.
#293: fix(remotefile): fix GetIDisks storage

Automated cherry pick of #293: fix(remotefile): fix GetIDisks storage

---

pkg/cloudprovider/images.go
pkg/cloudprovider/network.go
pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/image.go
pkg/multicloud/aliyun/ramimage.go
pkg/multicloud/aliyun/storagecache.go
pkg/multicloud/aliyun/task.go
pkg/multicloud/apsara/storagecache.go
pkg/multicloud/bingocloud/image.go
pkg/multicloud/bingocloud/storagecache.go
pkg/multicloud/ctyun/storagecache.go
pkg/multicloud/ecloud/storagecache.go
pkg/multicloud/esxi/storagecache.go
pkg/multicloud/google/storagecache.go
pkg/multicloud/hcso/storagecache.go
pkg/multicloud/huawei/storagecache.go
pkg/multicloud/image_base.go
pkg/multicloud/jdcloud/storagecache.go
pkg/multicloud/nutanix/storagecache.go
pkg/multicloud/openstack/storagecache.go
pkg/multicloud/proxmox/storagecache.go
pkg/multicloud/qcloud/storagecache.go
pkg/multicloud/ucloud/storagecache.go
pkg/multicloud/zstack/storagecache.go

fix(aliyun): image export

---

pkg/cloudprovider/kube_cluster.go
pkg/multicloud/aws/eks.go

fix(aws): node group key

---

pkg/multicloud/aliyun/ramimage.go

fix(aliyun): export image role

---

pkg/multicloud/aliyun/shell/image.go

fix(aliyun): cli build

---

pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/network.go
pkg/multicloud/aws/vpc.go

fix(aws): network api

---

pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/network.go
pkg/multicloud/aws/vpc.go

Cherry pick of #299 on release/3.10.
#299: fix(aws): network api

Automated cherry pick of #299: fix(aws): network api

---

pkg/multicloud/aliyun/aliyun.go

fix(aliyun): aliyun balance api

---

pkg/multicloud/aliyun/aliyun.go

Cherry pick of #301 on release/3.10.
#301: fix(aliyun): aliyun balance api

Automated cherry pick of #301: fix(aliyun): aliyun balance api

---

pkg/cloudprovider/kube_cluster.go
pkg/multicloud/aliyun/aliyun.go
pkg/multicloud/aliyun/kube_cluster.go
pkg/multicloud/aliyun/kube_node.go
pkg/multicloud/aliyun/kube_node_pools.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/shell/kube_cluster.go

fix(aliyun): k8s create

---

pkg/multicloud/aliyun/dns_domain_record.go

fix(aliyun): dns record page size

---

pkg/multicloud/aliyun/dns_domain_record.go

Cherry pick of #305 on release/3.10.
#305: fix(aliyun): dns record page size

Automated cherry pick of #305: fix(aliyun): dns record page size

---

pkg/multicloud/apsara/apsara.go

fix(apsaracli): change apsaraClient action type

---

pkg/multicloud/apsara/apsara.go

Cherry pick of #307 on release/3.10.
#307: fix(apsaracli): change apsaraClient action type

Automated cherry pick of #307: fix(apsaracli): change apsaraClient action type

---

pkg/multicloud/aliyun/aliyun.go

fix(aliyun): api retry

---

pkg/cloudprovider/resources.go
pkg/multicloud/apsara/instancetype.go
pkg/multicloud/apsara/region.go
pkg/multicloud/bingocloud/instance_type.go
pkg/multicloud/hcso/instancetype.go
pkg/multicloud/openstack/flavor.go
pkg/multicloud/zstack/offering.go

fix: gpu count

---

pkg/multicloud/proxmox/instance.go

fix(pve): boot order

---

pkg/multicloud/aliyun/kube_cluster.go

fix(aliyun): kube node pool with public ip

---

pkg/multicloud/aliyun/elasticcache_instance.go
pkg/multicloud/aliyun/utils.go
pkg/multicloud/apsara/elasticcache_instance.go
pkg/multicloud/apsara/utils.go

fix(aliyun): elastic cache list

---

pkg/multicloud/aliyun/elasticcache_instance.go
pkg/multicloud/aliyun/utils.go
pkg/multicloud/apsara/elasticcache_instance.go
pkg/multicloud/apsara/utils.go

Cherry pick of #318 on release/3.10.
#318: fix(aliyun): elastic cache list

Automated cherry pick of #318: fix(aliyun): elastic cache list

---

pkg/multicloud/zstack/instancenic.go

fix(zstack): nic ip

---

pkg/multicloud/zstack/instancenic.go

Cherry pick of #320 on release/3.10.
#320: fix(zstack): nic ip

Automated cherry pick of #320: fix(zstack): nic ip

---

pkg/multicloud/aliyun/kube_cluster.go

fix(aliyun): k8s snat

---

pkg/multicloud/aliyun/kube_node_pools.go

fix(aliyun): force delete node pool

---

pkg/multicloud/aliyun/kube_cluster.go

fix: aliyun node pool disk type

---

pkg/multicloud/openstack/shell/snapshot.go
pkg/multicloud/openstack/snapshot.go

fix(openstack): snapshot refresh

---

pkg/multicloud/openstack/shell/snapshot.go
pkg/multicloud/openstack/snapshot.go

Cherry pick of #325 on release/3.10.
#325: fix(openstack): snapshot refresh

Automated cherry pick of #325: fix(openstack): snapshot refresh

---

pkg/multicloud/esxi/virtualmachine.go

fix(esxi): migrate without storage

---

pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #329 on release/3.10.
#329: fix(esxi): migrate without storage

Automated cherry pick of #329: fix(esxi): migrate without storage

---

pkg/multicloud/azure/azure.go

fix(azure): map read

---

pkg/multicloud/azure/azure.go

Cherry pick of #331 on release/3.10.
#331: fix(azure): map read

Automated cherry pick of #331: fix(azure): map read

---

pkg/apis/compute/storage_const.go
pkg/multicloud/aliyun/disk.go
pkg/multicloud/aliyun/instance.go
pkg/multicloud/aliyun/storage.go
pkg/multicloud/aliyun/zone.go

fix: support aliyun cloud essd pl0

---

pkg/apis/compute/storage_const.go
pkg/multicloud/aliyun/disk.go
pkg/multicloud/aliyun/instance.go
pkg/multicloud/aliyun/storage.go
pkg/multicloud/aliyun/zone.go

Cherry pick of #334 on release/3.10.
#334: fix: support aliyun cloud essd pl0

Automated cherry pick of #334: fix: support aliyun cloud essd pl0

---

pkg/multicloud/esxi/virtualmachine.go

fix(esxi): hostname

---

pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #336 on release/3.10.
#336: fix(esxi): hostname

Automated cherry pick of #336: fix(esxi): hostname

---

pkg/multicloud/aliyun/eip.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/shell/eip.go

fix(aliyun): eip bgp pro

---

pkg/multicloud/aliyun/eip.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/shell/eip.go

Cherry pick of #338 on release/3.10.
#338: fix(aliyun): eip bgp pro

Automated cherry pick of #338: fix(aliyun): eip bgp pro

---

pkg/multicloud/huawei/monitor.go

fix(huawei): metric

---

pkg/multicloud/huawei/monitor.go

Cherry pick of #344 on release/3.10.
#344: fix(huawei): metric

Automated cherry pick of #344: fix(huawei): metric

---

pkg/multicloud/hcso/huawei.go
pkg/multicloud/hcso/instance.go
pkg/multicloud/hcso/project.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/instance.go
pkg/multicloud/huawei/project.go

fix(hcsocli): add defaultRegion for climc

---

pkg/multicloud/hcso/huawei.go
pkg/multicloud/hcso/instance.go
pkg/multicloud/hcso/project.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/instance.go
pkg/multicloud/huawei/project.go

Cherry pick of #342 on release/3.10.
#342: fix(hcsocli): add defaultRegion for climc

Automated cherry pick of #342: fix(hcsocli): add defaultRegion for climc

---

pkg/multicloud/esxi/shell/images.go
pkg/multicloud/esxi/storagecache.go

fix(esxi): local storage image

---

pkg/multicloud/esxi/shell/images.go
pkg/multicloud/esxi/storagecache.go

Cherry pick of #347 on release/3.10.
#347: fix(esxi): local storage image

Automated cherry pick of #347: fix(esxi): local storage image

---

pkg/multicloud/qcloud/qcloud.go

fix(qcloud): remove debug log

---

pkg/multicloud/qcloud/qcloud.go

Cherry pick of #349 on release/3.10.
#349: fix(qcloud): remove debug log

Automated cherry pick of #349: fix(qcloud): remove debug log

---

pkg/multicloud/esxi/provider/provider.go
scripts/cherry_pick_pull.sh

fix: update esxi credential with host
- release/3.10

fix: update esxi credential with host

---

pkg/multicloud/aws/aws.go
pkg/multicloud/aws/elasticache_instance.go
pkg/multicloud/aws/elasticache_instancetype.go
pkg/multicloud/aws/elasticache_memcached.go
pkg/multicloud/aws/elasticache_parameter.go
pkg/multicloud/aws/elasticache_snapshot.go
pkg/multicloud/aws/elasticache_user.go
pkg/multicloud/aws/region.go
pkg/multicloud/aws/shell/elasticache.go

fix: refactor aws redis

---

pkg/multicloud/aws/dnshostedzone.go

fix(aws): dns zone sync

---

pkg/multicloud/aws/dnshostedzone.go

Cherry pick of #353 on release/3.10.
#353: fix(aws): dns zone sync

Automated cherry pick of #353: fix(aws): dns zone sync

---

pkg/multicloud/aliyun/networkinterfaces.go
pkg/multicloud/aliyun/shell/networkinterface.go

fix(aliyun): eni sync

---

pkg/multicloud/aliyun/networkinterfaces.go
pkg/multicloud/aliyun/shell/networkinterface.go

Cherry pick of #355 on release/3.10.
#355: fix(aliyun): eni sync

Automated cherry pick of #355: fix(aliyun): eni sync

---

cmd/cmx/shell/balance.go
pkg/cloudprovider/cloudprovider.go
pkg/multicloud/aliyun/provider/provider.go
pkg/multicloud/apsara/provider/provider.go
pkg/multicloud/aws/provider/provider.go
pkg/multicloud/azure/provider/provider.go
pkg/multicloud/bingocloud/provider/provider.go
pkg/multicloud/ctyun/provider/provider.go
pkg/multicloud/ecloud/provider/provider.go
pkg/multicloud/esxi/provider/provider.go
pkg/multicloud/google/provider/provider.go
pkg/multicloud/hcso/provider/provider.go
pkg/multicloud/huawei/provider/provider.go
pkg/multicloud/jdcloud/provider/provider.go
pkg/multicloud/nutanix/provider/provider.go
pkg/multicloud/objectstore/provider/provider.go
pkg/multicloud/openstack/provider/provider.go
pkg/multicloud/proxmox/provider/provider.go
pkg/multicloud/qcloud/provider/provider.go
pkg/multicloud/qcloud/qcloud.go
pkg/multicloud/remotefile/provider/provider.go
pkg/multicloud/ucloud/provider/provider.go
pkg/multicloud/zstack/provider/provider.go

fix: show currency for balance

---

cmd/cmx/shell/balance.go
pkg/cloudprovider/cloudprovider.go
pkg/multicloud/aliyun/provider/provider.go
pkg/multicloud/apsara/provider/provider.go
pkg/multicloud/aws/provider/provider.go
pkg/multicloud/azure/provider/provider.go
pkg/multicloud/bingocloud/provider/provider.go
pkg/multicloud/ctyun/provider/provider.go
pkg/multicloud/ecloud/provider/provider.go
pkg/multicloud/esxi/provider/provider.go
pkg/multicloud/google/provider/provider.go
pkg/multicloud/hcso/provider/provider.go
pkg/multicloud/huawei/provider/provider.go
pkg/multicloud/jdcloud/provider/provider.go
pkg/multicloud/nutanix/provider/provider.go
pkg/multicloud/objectstore/provider/provider.go
pkg/multicloud/openstack/provider/provider.go
pkg/multicloud/proxmox/provider/provider.go
pkg/multicloud/qcloud/provider/provider.go
pkg/multicloud/qcloud/qcloud.go
pkg/multicloud/remotefile/provider/provider.go
pkg/multicloud/ucloud/provider/provider.go
pkg/multicloud/zstack/provider/provider.go

Cherry pick of #357 on release/3.10.
#357: fix: show currency for balance

Automated cherry pick of #357: fix: show currency for balance

---

pkg/multicloud/aws/securitygroup.go

fix(aws): secgroup rule

---

pkg/multicloud/aws/securitygroup.go

Cherry pick of #359 on release/3.10.
#359: fix(aws): secgroup rule

Automated cherry pick of #359: fix(aws): secgroup rule

---

pkg/multicloud/apsara/apsara.go

fix(apsara): apsara https

---

pkg/multicloud/apsara/apsara.go

Cherry pick of #362 on release/3.10.
#362: fix(apsara): apsara https

Automated cherry pick of #362: fix(apsara): apsara https

---

pkg/multicloud/apsara/apsara.go
pkg/multicloud/apsara/bucket.go
pkg/multicloud/apsara/region.go
pkg/multicloud/azure/azure.go

fix: apsara bucket list

---

pkg/multicloud/apsara/apsara.go
pkg/multicloud/apsara/bucket.go
pkg/multicloud/apsara/region.go
pkg/multicloud/azure/azure.go

Cherry pick of #364 on release/3.10.
#364: fix: apsara bucket list

Automated cherry pick of #364: fix: apsara bucket list

---

pkg/multicloud/cmx/shell/balance.go

Cherry pick of #367 on release/3.10.
#367: fix: get_balance return params error

Automated cherry pick of #367: fix: get_balance return params error

---

pkg/multicloud/cmx/shell/balance.go

fix: get_balance return params error
- release/3.10

fix: get_balance return params error

---

pkg/apis/compute/host_const.go
pkg/cloudprovider/resources.go
pkg/multicloud/esxi/hostnic.go

fix: inic add vlanId method
NONE

fix: inic add vlanId method

---

cmd/ksyuncli/main.go
pkg/apis/compute/cloudaccount_const.go
pkg/multicloud/ksyun/ksyun.go
pkg/multicloud/ksyun/ksyuncli/main.go
pkg/multicloud/ksyun/region.go
pkg/multicloud/ksyun/shell/printutils.go
pkg/multicloud/ksyun/shell/region.go

feat: support ksyun

---

pkg/apis/compute/guest_const.go
pkg/apis/compute/host_const.go
pkg/apis/const.go

fix: add ksyun const

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/ksyun/ksyun.go
pkg/multicloud/ksyun/provider/provider.go
pkg/multicloud/ksyun/region.go
pkg/multicloud/loader/loader.go

fix(ksyun): add region code

---

cmd/cucli/main.go
pkg/apis/compute/cloudaccount_const.go
pkg/apis/compute/guest_const.go
pkg/apis/compute/host_const.go
pkg/multicloud/cucloud/cucli/main.go
pkg/multicloud/cucloud/cucloud.go
pkg/multicloud/cucloud/provider/provider.go
pkg/multicloud/cucloud/region.go
pkg/multicloud/cucloud/shell/balance.go
pkg/multicloud/cucloud/shell/printutil.go
pkg/multicloud/cucloud/shell/region.go
pkg/multicloud/loader/loader.go

fix(cucloud): add china union cloud

---

cmd/qingcli/main.go
pkg/apis/compute/cloudaccount_const.go
pkg/apis/compute/guest_const.go
pkg/apis/compute/host_const.go
pkg/multicloud/loader/loader.go
pkg/multicloud/qingcloud/provider/provider.go
pkg/multicloud/qingcloud/qingcli/main.go
pkg/multicloud/qingcloud/qingcloud.go
pkg/multicloud/qingcloud/region.go
pkg/multicloud/qingcloud/shell/printutil.go
pkg/multicloud/qingcloud/shell/region.go
pkg/multicloud/qingcloud/shell/zone.go
pkg/multicloud/qingcloud/zone.go

feat: support qingcloud

---

.github/workflows/docker_build_push.yml

fix: update docker yml

---

.github/workflows/docker_build_push.yml

Cherry pick of #377 on release/3.10.
#377: fix: update docker yml

Automated cherry pick of #377: fix: update docker yml

---

.github/workflows/docker_build_push.yml

fix: docker username

---

.github/workflows/docker_build_push.yml

Cherry pick of #379 on release/3.10.
#379: fix: docker username

Automated cherry pick of #379: fix: docker username

---

.github/workflows/docker_build_push.yml

fix: workflow username

---

.github/workflows/docker_build_push.yml

fix: workflow secret

---

.github/workflows/docker_build_push.yml

Cherry pick of #383 on release/3.10.
#383: fix: workflow secret

Automated cherry pick of #383: fix: workflow secret

---

.github/workflows/docker_build_push.yml

fix: tls timeout

---

.github/workflows/docker_build_push.yml

Cherry pick of #385 on release/3.10.
#385: fix: tls timeout

Automated cherry pick of #385: fix: tls timeout

---

scripts/docker_push.sh

Cherry pick of #387 on release/3.10.
#387: fix: docker push

Automated cherry pick of #387: fix: docker push

---

pkg/multicloud/aws/aws_request.go
pkg/multicloud/aws/eip.go

fix: aws eip retry

---

pkg/multicloud/aws/aws_request.go
pkg/multicloud/aws/eip.go

Cherry pick of #391 on release/3.10.
#391: fix: aws eip retry

Automated cherry pick of #391: fix: aws eip retry

---

pkg/cloudprovider/eip.go
pkg/multicloud/aliyun/eip.go
pkg/multicloud/aliyun/shell/eip.go
pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/region.go
pkg/multicloud/huawei/shell/eip.go
pkg/multicloud/openstack/region.go
pkg/multicloud/qcloud/eip.go
pkg/multicloud/qcloud/shell/eip.go
pkg/multicloud/zstack/region.go

fix: eip tags

---

pkg/cloudprovider/eip.go
pkg/multicloud/aliyun/eip.go
pkg/multicloud/aliyun/shell/eip.go
pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/region.go
pkg/multicloud/huawei/shell/eip.go
pkg/multicloud/openstack/region.go
pkg/multicloud/qcloud/eip.go
pkg/multicloud/qcloud/shell/eip.go
pkg/multicloud/zstack/region.go

Cherry pick of #393 on release/3.10.
#393: fix: eip tags

Automated cherry pick of #393: fix: eip tags

---

pkg/multicloud/qcloud/project.go

fix(qcloud): skip disabled project

---

pkg/multicloud/qcloud/project.go

Cherry pick of #395 on release/3.10.
#395: fix(qcloud): skip disabled project

Automated cherry pick of #395: fix(qcloud): skip disabled project

---

pkg/multicloud/qcloud/zone.go

Cherry pick of #398 on release/3.10.
#398: fix: tencent cloud storage

Automated cherry pick of #398: fix: tencent cloud storage

---

pkg/multicloud/qingcloud/qingcloud.go

fix(region): qingcloud error

---

pkg/multicloud/esxi/datacenter.go
pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/esxi/storage.go
pkg/multicloud/esxi/vdisk.go
pkg/multicloud/esxi/virtualmachine.go

fix: esxi log

---

pkg/multicloud/esxi/datacenter.go
pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/esxi/storage.go
pkg/multicloud/esxi/vdisk.go
pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #403 on release/3.10.
#403: fix: esxi log

Automated cherry pick of #403: fix: esxi log

---

pkg/multicloud/aws/aws_request.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/shell/lb.go
pkg/multicloud/aws/tag_base.go

fix: aws system tags

---

pkg/multicloud/aws/aws_request.go
pkg/multicloud/aws/loadbalancer.go
pkg/multicloud/aws/shell/lb.go
pkg/multicloud/aws/tag_base.go

Cherry pick of #405 on release/3.10.
#405: fix: aws system tags

Automated cherry pick of #405: fix: aws system tags

---

pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/virtualmachine.go

- release/3.10
/area region
/cc @zexi

fix(esxi): vmware name and tag sync

---

pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #407 on release/3.10.
#407: fix(esxi): vmware name and tag sync

Automated cherry pick of #407: fix(esxi): vmware name and tag sync

---

pkg/multicloud/aws/disk.go
pkg/multicloud/aws/instance.go
pkg/multicloud/aws/shell/instance.go

fix(aws): detach disk

---

pkg/multicloud/aws/disk.go
pkg/multicloud/aws/instance.go
pkg/multicloud/aws/shell/instance.go

Cherry pick of #412 on release/3.10.
#412: fix(aws): detach disk

Automated cherry pick of #412: fix(aws): detach disk

---

pkg/multicloud/qingcloud/qingcloud.go

fix(qingcloud): 500 code

---

pkg/cloudprovider/errors.go
pkg/multicloud/azure/azure.go

fix(azure): bucket error

---

pkg/cloudprovider/errors.go
pkg/multicloud/azure/azure.go

Cherry pick of #415 on release/3.10.
#415: fix(azure): bucket error

Automated cherry pick of #415: fix(azure): bucket error

---

pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/network.go
pkg/multicloud/esxi/shell/host.go
pkg/multicloud/esxi/tags.go
pkg/multicloud/esxi/virtualmachine.go

fix: vmware dvporgroup support
NONE

fix: vmware dvporgroup support

---

pkg/multicloud/esxi/virtualmachine.go

fix: esxi vm nics should consider exists even if no ip
NONE

fix: esxi vm nics should consider exists even if no ip

---

pkg/multicloud/aws/host.go
pkg/multicloud/aws/instance.go
pkg/multicloud/aws/shell/disk.go

fix(aws): support gp3 throughput

---

pkg/multicloud/aws/aws.go

fix(aws): bucket forbidden

---

pkg/multicloud/aws/aws.go

Cherry pick of #422 on release/3.10.
#422: fix(aws): bucket forbidden

Automated cherry pick of #422: fix(aws): bucket forbidden

---

pkg/multicloud/esxi/shell/images.go
pkg/multicloud/esxi/storagecache.go

fix(region): avoid duplicate image sync

---

pkg/multicloud/esxi/shell/images.go
pkg/multicloud/esxi/storagecache.go

Cherry pick of #426 on release/3.10.
#426: fix(region): avoid duplicate image sync

Automated cherry pick of #426: fix(region): avoid duplicate image sync

---

pkg/multicloud/openstack/instance.go

fix(openstack): set vm tags

---

pkg/multicloud/google/google.go

fix(google): skip invalid google project

---

pkg/multicloud/google/google.go

Cherry pick of #431 on release/3.10.
#431: fix(google): skip invalid google project

Automated cherry pick of #431: fix(google): skip invalid google project

---

pkg/multicloud/aliyun/instance.go
pkg/multicloud/aws/dbinstance.go
pkg/multicloud/aws/shell/dbinstance.go

fix(aliyun,aws):Support resource desc

---

pkg/multicloud/google/securitygroup.go

fix(google): skip google invalid rule

---

pkg/multicloud/google/securitygroup.go

Cherry pick of #434 on release/3.10.
#434: fix(google): skip google invalid rule

Automated cherry pick of #434: fix(google): skip google invalid rule

---

pkg/multicloud/qcloud/qcloud.go

fix(qcloud): fix empty zone

---

pkg/multicloud/qcloud/qcloud.go

Cherry pick of #436 on release/3.10.
#436: fix(qcloud): fix empty zone

Automated cherry pick of #436: fix(qcloud): fix empty zone

---

pkg/multicloud/huawei/enterpriseprojects.go

fix(huawei): enterprise project

---

pkg/multicloud/huawei/enterpriseprojects.go

Cherry pick of #439 on release/3.10.
#439: fix(huawei): enterprise project

Automated cherry pick of #439: fix(huawei): enterprise project

---

pkg/multicloud/aws/storage.go

fix(aws): storage emulated

---

pkg/multicloud/aws/storage.go

Cherry pick of #442 on release/3.10.
#442: fix(aws): storage emulated

Automated cherry pick of #442: fix(aws): storage emulated

---

pkg/multicloud/aws/storage.go

fix: aws storage

---

pkg/multicloud/huawei/huawei.go

fix(region): skip invalid project

---

pkg/multicloud/huawei/huawei.go

Cherry pick of #445 on release/3.10.
#445: fix(region): skip invalid project

Automated cherry pick of #445: fix(region): skip invalid project

---

pkg/multicloud/esxi/virtualmachine.go

- release/3.10
/area region
/cc @zexi

fix(esxi): linux hostname

---

pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #448 on release/3.11.
#448: fix(esxi): linux hostname

Automated cherry pick of #448: fix(esxi): linux hostname

---

pkg/multicloud/aws/disk.go

fix(aws): disk type

---

pkg/multicloud/aws/disk.go

Cherry pick of #451 on release/3.11.
#451: fix(aws): disk type

Automated cherry pick of #451: fix(aws): disk type

---

pkg/multicloud/esxi/host.go

fix(vmware): remove clone template old nic

---

pkg/multicloud/esxi/host.go

Cherry pick of #454 on release/3.11.
#454: fix(vmware): remove clone template old nic

Automated cherry pick of #454: fix(vmware): remove clone template old nic

---

pkg/multicloud/aws/instance.go

fix(aws): avoid nil panic

---

pkg/multicloud/azure/cloudgroup.go

fix: azure cloud group

---

pkg/multicloud/azure/cloudgroup.go

Cherry pick of #467 on release/3.11.
#467: fix: azure cloud group

Automated cherry pick of #467: fix: azure cloud group

---

pkg/multicloud/aws/instance.go

fix: aws userdata

---

pkg/multicloud/aws/instance.go

Cherry pick of #470 on release/3.11.
#470: fix: aws userdata

Automated cherry pick of #470: fix: aws userdata

---

pkg/multicloud/ctyun/provider/provider.go

fix(ctyun): remove ctyun env parameter

---

pkg/multicloud/ctyun/provider/provider.go

Cherry pick of #472 on release/3.11.
#472: fix(ctyun): remove ctyun env parameter

Automated cherry pick of #472: fix(ctyun): remove ctyun env parameter

---

pkg/multicloud/ctyun/ctyun.go

fix: ctyun sign time in shanghai

---

pkg/multicloud/ctyun/ctyun.go

Cherry pick of #475 on release/3.11.
#475: fix: ctyun sign time in shanghai

Automated cherry pick of #475: fix: ctyun sign time in shanghai

---

pkg/multicloud/ctyun/ctyun.go

fix(ctyun): invalid access key error

---

pkg/multicloud/ctyun/ctyun.go

Cherry pick of #478 on release/3.11.
#478: fix(ctyun): invalid access key error

Automated cherry pick of #478: fix(ctyun): invalid access key error

---

pkg/multicloud/esxi/compact_ips.go
pkg/multicloud/esxi/manager.go
pkg/multicloud/esxi/tags.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/esxi/wire.go

fix: vmware sync wires revisit
- release/3.11

fix: vmware sync wires revisit

---

pkg/multicloud/aws/loadbalancer.go

fix(aws): aws lb panic

---

pkg/multicloud/aws/loadbalancer.go

Cherry pick of #486 on release/3.11.
#486: fix(aws): aws lb panic

Automated cherry pick of #486: fix(aws): aws lb panic

---

pkg/multicloud/esxi/devtools.go

Cherry pick of #488 on release/3.11.
#488: fix: more details when esxi get_network_by_id error

Automated cherry pick of #488: fix: more details when esxi get_network_by_id error

---

pkg/multicloud/aws/eip.go

fix(aws): eip not found error

---

pkg/multicloud/aws/eip.go

Cherry pick of #492 on release/3.11.
#492: fix(aws): eip not found error

Automated cherry pick of #492: fix(aws): eip not found error

---

pkg/multicloud/aws/organizations.go

fix(aws): subaccount name

---

pkg/multicloud/aliyun/instance.go

fix(aliyun): cloud_auto enable burst

---

pkg/multicloud/aliyun/instance.go

Cherry pick of #495 on release/3.11.
#495: fix(aliyun): cloud_auto enable burst

Automated cherry pick of #495: fix(aliyun): cloud_auto enable burst

---

pkg/multicloud/aliyun/secgrouprule.go
pkg/multicloud/apsara/secgrouprule.go
pkg/multicloud/huawei/secgrouprule.go
pkg/multicloud/qcloud/securitygroup.go

fix: secgroup rule create

---

pkg/multicloud/aliyun/secgrouprule.go
pkg/multicloud/apsara/secgrouprule.go
pkg/multicloud/huawei/secgrouprule.go
pkg/multicloud/qcloud/securitygroup.go

Cherry pick of #501 on release/3.11.
#501: fix: secgroup rule create

Automated cherry pick of #501: fix: secgroup rule create

---

pkg/multicloud/esxi/virtualmachine.go

fix(esxi): single esxi host not support tags

---

pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #503 on release/3.11.
#503: fix(esxi): single esxi host not support tags

Automated cherry pick of #503: fix(esxi): single esxi host not support tags

---

pkg/multicloud/aliyun/secgrouprule.go
pkg/multicloud/aliyun/securitygroup.go
pkg/multicloud/ctyun/secrules.go
pkg/multicloud/ctyun/securitygroup.go
pkg/multicloud/qcloud/secgrouprule.go

fix: secgroup rule update

---

pkg/multicloud/aliyun/secgrouprule.go
pkg/multicloud/aliyun/securitygroup.go
pkg/multicloud/ctyun/secrules.go
pkg/multicloud/ctyun/securitygroup.go
pkg/multicloud/qcloud/secgrouprule.go

Cherry pick of #506 on release/3.11.
#506: fix: secgroup rule update

Automated cherry pick of #506: fix: secgroup rule update

---

pkg/multicloud/aliyun/disk.go
pkg/multicloud/aliyun/storage.go

fix: aliyun disk burst

---

pkg/multicloud/aliyun/disk.go
pkg/multicloud/aliyun/storage.go

Cherry pick of #508 on release/3.11.
#508: fix: aliyun disk burst

Automated cherry pick of #508: fix: aliyun disk burst

---

pkg/multicloud/instance_base.go
pkg/multicloud/volcengine/disk.go
pkg/multicloud/volcengine/eip.go
pkg/multicloud/volcengine/host.go
pkg/multicloud/volcengine/image.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/instancenic.go
pkg/multicloud/volcengine/keypairs.go
pkg/multicloud/volcengine/natdtable.go
pkg/multicloud/volcengine/natgateway.go
pkg/multicloud/volcengine/natstable.go
pkg/multicloud/volcengine/network.go
pkg/multicloud/volcengine/networkinterfaces.go
pkg/multicloud/volcengine/project.go
pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/routetable.go
pkg/multicloud/volcengine/securitygroup.go
pkg/multicloud/volcengine/shell/instance.go
pkg/multicloud/volcengine/shell/keypair.go
pkg/multicloud/volcengine/shell/storage.go
pkg/multicloud/volcengine/storage.go
pkg/multicloud/volcengine/user.go
pkg/multicloud/volcengine/volcengine.go
pkg/multicloud/volcengine/zone.go

fix: volc vm create

---

pkg/multicloud/instance_base.go
pkg/multicloud/volcengine/disk.go
pkg/multicloud/volcengine/eip.go
pkg/multicloud/volcengine/host.go
pkg/multicloud/volcengine/image.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/instancenic.go
pkg/multicloud/volcengine/keypairs.go
pkg/multicloud/volcengine/natdtable.go
pkg/multicloud/volcengine/natgateway.go
pkg/multicloud/volcengine/natstable.go
pkg/multicloud/volcengine/network.go
pkg/multicloud/volcengine/networkinterfaces.go
pkg/multicloud/volcengine/project.go
pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/routetable.go
pkg/multicloud/volcengine/securitygroup.go
pkg/multicloud/volcengine/shell/instance.go
pkg/multicloud/volcengine/shell/keypair.go
pkg/multicloud/volcengine/shell/storage.go
pkg/multicloud/volcengine/storage.go
pkg/multicloud/volcengine/user.go
pkg/multicloud/volcengine/volcengine.go
pkg/multicloud/volcengine/zone.go

Cherry pick of #510 on release/3.11.
#510: fix: volc vm create

Automated cherry pick of #510: fix: volc vm create

---

pkg/multicloud/esxi/virtualmachine.go

fix: esxi vm delete

---

pkg/multicloud/esxi/virtualmachine.go

Cherry pick of #512 on release/3.11.
#512: fix: esxi vm delete

Automated cherry pick of #512: fix: esxi vm delete

---

pkg/multicloud/aliyun/vpc.go
pkg/multicloud/apsara/vpc.go
pkg/multicloud/azure/instancenic.go
pkg/multicloud/azure/securitygroup.go

Cherry pick of #515 on release/3.11.
#515: fix(azure): secgroup delete

Automated cherry pick of #515: fix(azure): secgroup delete

---

pkg/multicloud/aws/securitygroup.go

fix(region): aws default secgroup delete

---

pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/securitygroup.go
pkg/multicloud/volcengine/shell/secgroup.go

fix(volc): security group delete

---

pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/securitygroup.go
pkg/multicloud/volcengine/shell/secgroup.go

Cherry pick of #519 on release/3.11.
#519: fix(volc): security group delete

Automated cherry pick of #519: fix(volc): security group delete

---

pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/host.go
pkg/multicloud/aliyun/instance.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/shell/instance.go
pkg/multicloud/apsara/region.go
pkg/multicloud/aws/region.go
pkg/multicloud/azure/host.go
pkg/multicloud/azure/region.go
pkg/multicloud/bingocloud/region.go
pkg/multicloud/ctyun/region.go
pkg/multicloud/ecloud/region.go
pkg/multicloud/esxi/fakeregion.go
pkg/multicloud/google/region.go
pkg/multicloud/hcso/region.go
pkg/multicloud/huawei/region.go
pkg/multicloud/jdcloud/region.go
pkg/multicloud/nutanix/region.go
pkg/multicloud/openstack/region.go
pkg/multicloud/proxmox/instance.go
pkg/multicloud/proxmox/region.go
pkg/multicloud/qcloud/region.go
pkg/multicloud/region_base.go
pkg/multicloud/remotefile/region.go
pkg/multicloud/ucloud/region.go
pkg/multicloud/volcengine/host.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/shell/instance.go
pkg/multicloud/zstack/region.go

Cherry pick of #522 on release/3.11.
#522: fix: add interface for region get vms

Automated cherry pick of #522: fix: add interface for region get vms

---

pkg/multicloud/volcengine/disk.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/shell/disk.go
pkg/multicloud/volcengine/storage.go

fix: volc misc fix

---

pkg/multicloud/volcengine/disk.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/region.go
pkg/multicloud/volcengine/shell/disk.go
pkg/multicloud/volcengine/storage.go

Cherry pick of #526 on release/3.11.
#526: fix: volc misc fix

Automated cherry pick of #526: fix: volc misc fix

---

pkg/multicloud/aliyun/bucket.go
pkg/multicloud/aws/bucket.go
pkg/multicloud/huawei/bucket.go

fix: fix GetBucketPolicyErr

---

pkg/multicloud/aliyun/bucket.go
pkg/multicloud/aws/bucket.go
pkg/multicloud/huawei/bucket.go

Cherry pick of #521 on release/3.11.
#521: fix: fix GetBucketPolicyErr

Automated cherry pick of #521: fix: fix GetBucketPolicyErr

---

pkg/cloudprovider/instance.go
pkg/multicloud/volcengine/instance.go

fix(volc): vnc

---

pkg/cloudprovider/instance.go
pkg/multicloud/volcengine/instance.go

Cherry pick of #528 on release/3.11.
#528: fix(volc): vnc

Automated cherry pick of #528: fix(volc): vnc

---

pkg/multicloud/volcengine/bucket.go
pkg/multicloud/volcengine/objects.go
pkg/multicloud/volcengine/provider/provider.go

fix(volc): bucket opts

---

pkg/multicloud/volcengine/bucket.go
pkg/multicloud/volcengine/objects.go
pkg/multicloud/volcengine/provider/provider.go

Cherry pick of #530 on release/3.11.
#530: fix(volc): bucket opts

Automated cherry pick of #530: fix(volc): bucket opts

---

pkg/multicloud/volcengine/image.go
pkg/multicloud/volcengine/shell/image.go
pkg/multicloud/volcengine/storagecache.go

fix: volc private image

---

pkg/multicloud/volcengine/image.go
pkg/multicloud/volcengine/shell/image.go
pkg/multicloud/volcengine/storagecache.go

Cherry pick of #532 on release/3.11.
#532: fix: volc private image

Automated cherry pick of #532: fix: volc private image

---

pkg/multicloud/huawei/loadbalancer.go

Cherry pick of #534 on release/3.11.
#534: fix(huawei): lb project

Automated cherry pick of #534: fix(huawei): lb project

---

pkg/multicloud/volcengine/bucket.go

fix: volc bucket storage class

---

pkg/multicloud/volcengine/bucket.go

Cherry pick of #537 on release/3.11.
#537: fix: volc bucket storage class

Automated cherry pick of #537: fix: volc bucket storage class

---

pkg/cloudprovider/metrics.go
pkg/multicloud/volcengine/monitor.go
pkg/multicloud/volcengine/network.go
pkg/multicloud/volcengine/provider/provider.go
pkg/multicloud/volcengine/shell/monitor.go
pkg/multicloud/volcengine/volcengine.go

fix: volc metric

---

pkg/cloudprovider/metrics.go
pkg/multicloud/volcengine/monitor.go
pkg/multicloud/volcengine/network.go
pkg/multicloud/volcengine/provider/provider.go
pkg/multicloud/volcengine/shell/monitor.go
pkg/multicloud/volcengine/volcengine.go

Cherry pick of #539 on release/3.11.
#539: fix: volc metric

Automated cherry pick of #539: fix: volc metric

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/consts.go
pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/aliyun.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/shell/sslcertificate.go
pkg/multicloud/aliyun/sslcertificate.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/shell/sslcertificate.go
pkg/multicloud/huawei/sslcertificate.go
pkg/multicloud/qcloud/certificate.go
pkg/multicloud/qcloud/qcloud.go
pkg/multicloud/qcloud/shell/certificate.go
pkg/multicloud/region_base.go

加入一个新的资源类型 证书资源
加入腾讯云&华为云&阿里云的证书资源同步和list api

feat(region): qcloud&aliyun&huawei add sslcertificate resource sync

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/consts.go
pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/aliyun.go
pkg/multicloud/aliyun/region.go
pkg/multicloud/aliyun/shell/sslcertificate.go
pkg/multicloud/aliyun/sslcertificate.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/shell/sslcertificate.go
pkg/multicloud/huawei/sslcertificate.go
pkg/multicloud/qcloud/certificate.go
pkg/multicloud/qcloud/qcloud.go
pkg/multicloud/qcloud/shell/certificate.go
pkg/multicloud/region_base.go

Cherry pick of #541 on release/3.11.
#541: feat(region): qcloud&aliyun&huawei add sslcertificate resource sync

Automated cherry pick of #541: feat(region): qcloud&aliyun&huawei add sslcertificate resource sync

---

pkg/multicloud/proxmox/cluster.go

fix(pve): min vm id

---

pkg/multicloud/proxmox/host.go
pkg/multicloud/proxmox/instance.go

fix(pve): search pve vm with timeout

---

pkg/multicloud/proxmox/host.go
pkg/multicloud/proxmox/instance.go

Cherry pick of #548 on release/3.11.
#548: fix(pve): search pve vm with timeout

Automated cherry pick of #548: fix(pve): search pve vm with timeout

---

pkg/multicloud/proxmox/instance.go

fix(pve): vnc

---

pkg/multicloud/proxmox/instance.go

Cherry pick of #551 on release/3.11.
#551: fix(pve): vnc

Automated cherry pick of #551: fix(pve): vnc

---

pkg/multicloud/proxmox/instance.go

Cherry pick of #554 on release/3.11.
#554: fix(pve): vnc

Automated cherry pick of #554: fix(pve): vnc

---

pkg/multicloud/aliyun/elasticcache_instance.go

fix(aliyun): avoid panic when get redis cache mod

---

pkg/multicloud/aliyun/elasticcache_instance.go

Cherry pick of #558 on release/3.11.
#558: fix(aliyun): avoid panic when get redis cache mod

Automated cherry pick of #558: fix(aliyun): avoid panic when get redis cache mod

---

pkg/multicloud/qcloud/certificate.go
pkg/multicloud/qcloud/region.go
pkg/multicloud/qcloud/shell/certificate.go
pkg/multicloud/qcloud/shell/loadbalancer.go

fix(qcloud): ssl

---

pkg/multicloud/proxmox/instance.go

fix(pve): vm ip with ipv4

---

pkg/multicloud/proxmox/instance.go

Cherry pick of #562 on release/3.11.
#562: fix(pve): vm ip with ipv4

Automated cherry pick of #562: fix(pve): vm ip with ipv4

---

pkg/multicloud/volcengine/image.go

fix(volc): save image

---

pkg/multicloud/volcengine/image.go

Cherry pick of #565 on release/3.11.
#565: fix(volc): save image

Automated cherry pick of #565: fix(volc): save image

---

pkg/apis/compute/disk_const.go
pkg/cloudprovider/instance.go
pkg/cloudprovider/resources.go
pkg/multicloud/disk_base.go
pkg/multicloud/esxi/devtools.go
pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/vdisk.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/remotefile/disk.go

fix(esxi): preallocation vdisk

---

pkg/apis/compute/disk_const.go
pkg/cloudprovider/instance.go
pkg/cloudprovider/resources.go
pkg/multicloud/disk_base.go
pkg/multicloud/esxi/devtools.go
pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/shell/virtualmachine.go
pkg/multicloud/esxi/vdisk.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/remotefile/disk.go

Cherry pick of #567 on release/3.11.
#567: fix(esxi): preallocation vdisk

Automated cherry pick of #567: fix(esxi): preallocation vdisk

---

pkg/multicloud/azure/region.go

fix(azure): vm refresh panic

---

pkg/multicloud/azure/region.go

Cherry pick of #569 on release/3.11.
#569: fix(azure): vm refresh panic

Automated cherry pick of #569: fix(azure): vm refresh panic

---

pkg/multicloud/aws/dbinstance.go

fix(awscli): fix aws dbinstance desc tag

---

pkg/multicloud/google/instance.go

fix(gcp): delete keypair

---

pkg/multicloud/google/instance.go

Cherry pick of #574 on release/3.11.
#574: fix(gcp): delete keypair

Automated cherry pick of #574: fix(gcp): delete keypair

---

pkg/multicloud/aws/dbinstance.go

Cherry pick of #576 on release/3.11.
#576: fix(awscli): fix aws dbinstance desc tag

Automated cherry pick of #576: fix(awscli): fix aws dbinstance desc tag

---

pkg/apis/compute/storage_const.go
pkg/multicloud/oracle/boot-disk.go
pkg/multicloud/oracle/disk.go
pkg/multicloud/oracle/eip.go
pkg/multicloud/oracle/host.go
pkg/multicloud/oracle/image.go
pkg/multicloud/oracle/instance.go
pkg/multicloud/oracle/instancenic.go
pkg/multicloud/oracle/network.go
pkg/multicloud/oracle/oracle.go
pkg/multicloud/oracle/region.go
pkg/multicloud/oracle/security-group-rule.go
pkg/multicloud/oracle/security-group.go
pkg/multicloud/oracle/shell/boot-disk.go
pkg/multicloud/oracle/shell/disk.go
pkg/multicloud/oracle/shell/eip.go
pkg/multicloud/oracle/shell/image.go
pkg/multicloud/oracle/shell/network.go
pkg/multicloud/oracle/shell/security-group.go
pkg/multicloud/oracle/shell/vpc.go
pkg/multicloud/oracle/shell/zone.go
pkg/multicloud/oracle/storage.go
pkg/multicloud/oracle/storagecache.go
pkg/multicloud/oracle/tag.go
pkg/multicloud/oracle/vpc.go
pkg/multicloud/oracle/wire.go
pkg/multicloud/oracle/zone.go

fix(oracle): sync

---

pkg/apis/compute/storage_const.go
pkg/multicloud/oracle/boot-disk.go
pkg/multicloud/oracle/disk.go
pkg/multicloud/oracle/eip.go
pkg/multicloud/oracle/host.go
pkg/multicloud/oracle/image.go
pkg/multicloud/oracle/instance.go
pkg/multicloud/oracle/instancenic.go
pkg/multicloud/oracle/network.go
pkg/multicloud/oracle/oracle.go
pkg/multicloud/oracle/region.go
pkg/multicloud/oracle/security-group-rule.go
pkg/multicloud/oracle/security-group.go
pkg/multicloud/oracle/shell/boot-disk.go
pkg/multicloud/oracle/shell/disk.go
pkg/multicloud/oracle/shell/eip.go
pkg/multicloud/oracle/shell/image.go
pkg/multicloud/oracle/shell/network.go
pkg/multicloud/oracle/shell/security-group.go
pkg/multicloud/oracle/shell/vpc.go
pkg/multicloud/oracle/shell/zone.go
pkg/multicloud/oracle/storage.go
pkg/multicloud/oracle/storagecache.go
pkg/multicloud/oracle/tag.go
pkg/multicloud/oracle/vpc.go
pkg/multicloud/oracle/wire.go
pkg/multicloud/oracle/zone.go

Cherry pick of #578 on release/3.11.
#578: fix(oracle): sync

Automated cherry pick of #578: fix(oracle): sync

---

pkg/cloudprovider/dnszone.go
pkg/multicloud/aliyun/dns_domain_record.go
pkg/multicloud/aws/aws.go
pkg/multicloud/aws/aws_request.go
pkg/multicloud/aws/cdn.go
pkg/multicloud/aws/provider/provider.go
pkg/multicloud/aws/region.go
pkg/multicloud/aws/shell/cdn.go
pkg/multicloud/huawei/cdn.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/provider/provider.go
pkg/multicloud/huawei/shell/cdn.go

- AWS和华为云加入CDN资源同步
- DNS Record增加两个阿里云相关资源的细化区域映射

feat(region): aws&huawei add cdn resource sync

---

pkg/multicloud/qcloud/loadbalancer.go

fix(qcloud): lb ip addr

---

pkg/multicloud/qcloud/loadbalancer.go

Cherry pick of #580 on release/3.11.
#580: fix(qcloud): lb ip addr

Automated cherry pick of #580: fix(qcloud): lb ip addr

---

pkg/multicloud/qcloud/loadbalancer.go

fix(qcloud): lb domain name

---

pkg/multicloud/qcloud/loadbalancer.go

Cherry pick of #583 on release/3.11.
#583: fix(qcloud): lb domain name

Automated cherry pick of #583: fix(qcloud): lb domain name

---

pkg/multicloud/aliyun/tag_base.go
pkg/multicloud/tag_base.go

fix(region): k8s tag

---

pkg/multicloud/aliyun/tag_base.go
pkg/multicloud/tag_base.go

Cherry pick of #586 on release/3.11.
#586: fix(region): k8s tag

Automated cherry pick of #586: fix(region): k8s tag

---

pkg/cloudprovider/instance.go
pkg/cloudprovider/resources.go
pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/instance_base.go
pkg/multicloud/remotefile/instance.go

fix(esxi): cpu sockets

---

pkg/cloudprovider/instance.go
pkg/cloudprovider/resources.go
pkg/multicloud/esxi/host.go
pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/instance_base.go
pkg/multicloud/remotefile/instance.go

Cherry pick of #589 on release/3.11.
#589: fix(esxi): cpu sockets

Automated cherry pick of #589: fix(esxi): cpu sockets

---

pkg/multicloud/zstack/disk.go
pkg/multicloud/zstack/host.go
pkg/multicloud/zstack/storage.go

fix(zstack): shared block storage

---

pkg/multicloud/zstack/disk.go
pkg/multicloud/zstack/host.go
pkg/multicloud/zstack/storage.go

Cherry pick of #591 on release/3.11.
#591: fix(zstack): shared block storage

Automated cherry pick of #591: fix(zstack): shared block storage

---

pkg/multicloud/apsara/dbinstance.go
pkg/multicloud/apsara/host.go
pkg/multicloud/apsara/region.go
pkg/multicloud/apsara/storage.go
pkg/multicloud/apsara/vpc.go

fix(apsara): 避免死循环

---

pkg/multicloud/apsara/dbinstance.go
pkg/multicloud/apsara/host.go
pkg/multicloud/apsara/region.go
pkg/multicloud/apsara/storage.go
pkg/multicloud/apsara/vpc.go

Cherry pick of #595 on release/3.11.
#595: fix(apsara): 避免死循环

Automated cherry pick of #595: fix(apsara): 避免死循环

---

pkg/multicloud/huawei/cdn.go
pkg/multicloud/huawei/clouduser.go
pkg/multicloud/huawei/dbinstance.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/modelarts_pool.go
pkg/multicloud/huawei/modelarts_pool_sku.go
pkg/multicloud/huawei/monitor.go
pkg/multicloud/huawei/region.go
pkg/multicloud/huawei/sslcertificate.go

fix(huawei): api pretty

---

pkg/multicloud/aws/aws.go
pkg/multicloud/aws/aws_invoke.go
pkg/multicloud/aws/container.go
pkg/multicloud/aws/dynamodb.go
pkg/multicloud/aws/kinesis.go
pkg/multicloud/aws/lambda.go
pkg/multicloud/aws/region.go
pkg/multicloud/aws/shell/contanier.go
pkg/multicloud/aws/shell/dynamodb.go
pkg/multicloud/aws/shell/kinesis.go
pkg/multicloud/aws/shell/lambda.go
pkg/multicloud/huawei/functiongraph.go
pkg/multicloud/huawei/gaussdb_mysql.go
pkg/multicloud/huawei/gaussdb_nosql.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/shell/functions.go
pkg/multicloud/huawei/shell/gaussdb_mysql.go
pkg/multicloud/huawei/shell/gaussdb_nosql.go

fix: add extra api

---

pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/esxi/vnic.go

feature: support esxi subips
- release/3.11

feature: support esxi subips

---

pkg/multicloud/esxi/virtualmachine.go
pkg/multicloud/esxi/vnic.go

Cherry pick of #593 on release/3.11.
#593: feature: support esxi subips

Automated cherry pick of #593: feature: support esxi subips

---

pkg/multicloud/huawei/gaussdb_mysql.go
pkg/multicloud/huawei/gaussdb_nosql.go
pkg/multicloud/qcloud/certificate.go
pkg/multicloud/qcloud/instancenic.go
pkg/multicloud/remotefile/instancenic.go

fix(qcloud): mac addr

---

pkg/multicloud/qcloud/certificate.go
pkg/multicloud/qcloud/instancenic.go
pkg/multicloud/remotefile/instancenic.go

Cherry pick of #599 on release/3.11.
#599: fix(qcloud): mac addr

Automated cherry pick of #599: fix(qcloud): mac addr

---

pkg/multicloud/huawei/instance.go
pkg/multicloud/huawei/instancenic.go

Cherry pick of #607 on release/3.11.
#607: [WIP]fix(huawei): nic

Automated cherry pick of #607: fix(huawei): nic

---

pkg/multicloud/apsara/apsara.go

Cherry pick of #615 on release/3.11.
#615: fix(apsara): avoid apsara read only error

Automated cherry pick of #615: fix(apsara): avoid apsara read only error

---

pkg/cloudprovider/instance.go

Cherry pick of #618 on release/3.11.
#618: fix: add bios options for create vm

Automated cherry pick of #618: fix: add bios options for create vm

---

pkg/cloudprovider/images.go
pkg/cloudprovider/instance.go

Cherry pick of #621 on release/3.11.
#621: fix: image uefi

Automated cherry pick of #621: fix: image uefi

---

pkg/multicloud/volcengine/provider/provider.go
pkg/multicloud/volcengine/shell/balance.go
pkg/multicloud/volcengine/volcengine.go

fix(volc): support balance api

---

pkg/multicloud/google/google.go
pkg/multicloud/google/instance.go

Cherry pick of #629 on release/3.10.
#629: fix(gcp): create resource with requestId

Automated cherry pick of #629: fix(gcp): create resource with requestId

---

pkg/multicloud/google/instance.go

fix(gcp): allow password login

---

pkg/multicloud/google/instance.go

Cherry pick of #634 on release/3.11.
#634: fix(gcp): allow password login

Automated cherry pick of #634: fix(gcp): allow password login

---

pkg/multicloud/google/disk.go
pkg/multicloud/google/instance.go

fix(gcp): rebuild root with sys disk size

---

pkg/multicloud/google/disk.go
pkg/multicloud/google/instance.go

Cherry pick of #637 on release/3.11.
#637: fix(gcp): rebuild root with sys disk size

Automated cherry pick of #637: fix(gcp): rebuild root with sys disk size

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/google/latitude_and_longitude.go
pkg/multicloud/google/securitygroup.go

fix(gcp): avoid duplicate rule name used

---

pkg/apis/compute/cloudregions_const.go
pkg/apis/compute/regiondata.go
pkg/multicloud/google/latitude_and_longitude.go
pkg/multicloud/google/securitygroup.go

Cherry pick of #640 on release/3.11.
#640: fix(gcp): avoid duplicate rule name used

Automated cherry pick of #640: fix(gcp): avoid duplicate rule name used

---

pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/loadbalancer.go
pkg/multicloud/huawei/loadbalancer_acl.go
pkg/multicloud/huawei/loadbalancer_backend.go
pkg/multicloud/huawei/loadbalancer_backendgroup.go
pkg/multicloud/huawei/loadbalancer_cert.go
pkg/multicloud/huawei/loadbalancer_listener.go
pkg/multicloud/huawei/loadbalancer_listener_rule.go
pkg/multicloud/huawei/monitor.go

fix(huawei): remove useless code

---

pkg/multicloud/aws/aws_invoke.go

fix(aws): price api method

---

pkg/multicloud/aws/aws_invoke.go

Cherry pick of #651 on release/3.11.
#651: fix(aws): price api method

Automated cherry pick of #651: fix(aws): price api method

---

pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/loadbalancer.go
pkg/multicloud/huawei/shell/eip.go

fix(huawei): upgrade huawei eip and elb api

---

pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/loadbalancer.go
pkg/multicloud/huawei/shell/eip.go

Cherry pick of #649 on release/3.11.
#649: fix(huawei): upgrade huawei eip and elb api

Automated cherry pick of #649: fix(huawei): upgrade huawei eip and elb api

---

pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/shell/sslcertificate.go
pkg/multicloud/huawei/sslcertificate.go

fix(huawei): ssl certificate endpoint

---

pkg/multicloud/huawei/huawei.go
pkg/multicloud/huawei/shell/sslcertificate.go
pkg/multicloud/huawei/sslcertificate.go

Cherry pick of #653 on release/3.11.
#653: fix(huawei): ssl certificate endpoint

Automated cherry pick of #653: fix(huawei): ssl certificate endpoint

---

pkg/multicloud/aws/dnsrecord.go
pkg/multicloud/volcengine/network.go

fix(aws): dns record sync

---

pkg/multicloud/aws/dnsrecord.go
pkg/multicloud/volcengine/network.go

Cherry pick of #659 on release/3.11.
#659: fix(aws): dns record sync

Automated cherry pick of #659: fix(aws): dns record sync

---

pkg/multicloud/volcengine/disk.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/shell/disk.go
pkg/multicloud/volcengine/storage.go

fix(volc): disk list

---

pkg/multicloud/volcengine/disk.go
pkg/multicloud/volcengine/instance.go
pkg/multicloud/volcengine/shell/disk.go
pkg/multicloud/volcengine/storage.go

Cherry pick of #664 on release/3.11.
#664: fix(volc): disk list

Automated cherry pick of #664: fix(volc): disk list

---

pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/host.go
pkg/multicloud/apsara/host.go
pkg/multicloud/aws/host.go
pkg/multicloud/azure/host.go
pkg/multicloud/bingocloud/node.go
pkg/multicloud/ctyun/host.go
pkg/multicloud/ecloud/host.go
pkg/multicloud/esxi/host.go
pkg/multicloud/google/host.go
pkg/multicloud/hcso/host.go
pkg/multicloud/huawei/host.go
pkg/multicloud/jdcloud/host.go
pkg/multicloud/nutanix/host.go
pkg/multicloud/openstack/hypervisor.go
pkg/multicloud/oracle/host.go
pkg/multicloud/proxmox/host.go
pkg/multicloud/qcloud/host.go
pkg/multicloud/remotefile/host.go
pkg/multicloud/ucloud/host.go
pkg/multicloud/volcengine/host.go
pkg/multicloud/zstack/host.go

fix: change storage size to int64

---

pkg/cloudprovider/resources.go
pkg/multicloud/aliyun/host.go
pkg/multicloud/apsara/host.go
pkg/multicloud/aws/host.go
pkg/multicloud/azure/host.go
pkg/multicloud/bingocloud/node.go
pkg/multicloud/ctyun/host.go
pkg/multicloud/ecloud/host.go
pkg/multicloud/esxi/host.go
pkg/multicloud/google/host.go
pkg/multicloud/hcso/host.go
pkg/multicloud/huawei/host.go
pkg/multicloud/jdcloud/host.go
pkg/multicloud/nutanix/host.go
pkg/multicloud/openstack/hypervisor.go
pkg/multicloud/oracle/host.go
pkg/multicloud/proxmox/host.go
pkg/multicloud/qcloud/host.go
pkg/multicloud/remotefile/host.go
pkg/multicloud/ucloud/host.go
pkg/multicloud/volcengine/host.go
pkg/multicloud/zstack/host.go

Cherry pick of #666 on release/3.11.
#666: fix: change storage size to int64

Automated cherry pick of #666: fix: change storage size to int64

---

pkg/multicloud/huawei/eip.go
pkg/multicloud/huawei/instance.go

fix(huawei): skip sync huawei ipv6 eip

---

pkg/multicloud/google/instance.go

这个 PR 解决了 [Cloudpods Issue 19069](https://github.com/yunionio/cloudpods/issues/19069)。

feat(region): support custom user data in Google Cloud VM rebuild

---

pkg/multicloud/huawei/huawei.go

fix(huawei): init owner id

---

pkg/multicloud/huawei/huawei.go

Cherry pick of #678 on release/3.11.
#678: fix(huawei): init owner id

Automated cherry pick of #678: fix(huawei): init owner id

---

pkg/multicloud/huawei/loadbalancer.go

fix(huawei): skip ipv6 eip
