pkg/multicloud/huawei/loadbalancer.go
Cherry pick of #680 on release/3.11.
#680: fix(huawei): skip ipv6 eip
=> Automated cherry pick of #680: fix(huawei): skip ipv6 eip

pkg/multicloud/zstack/securitygroup.go
=> fix(zstack): secgroup rule create

pkg/multicloud/zstack/securitygroup.go
Cherry pick of #682 on release/3.11.
#682: fix(zstack): secgroup rule create
=> Automated cherry pick of #682: fix(zstack): secgroup rule create

pkg/cloudprovider/access_group.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/access_group_rule.go, pkg/multicloud/aliyun/access_groups.go, pkg/multicloud/aliyun/shell/access_groups.go
=> fix(aliyun): access group

pkg/cloudprovider/access_group.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/access_group_rule.go, pkg/multicloud/aliyun/access_groups.go, pkg/multicloud/aliyun/shell/access_groups.go
Cherry pick of #684 on release/3.11.
#684: fix(aliyun): access group
=> Automated cherry pick of #684: fix(aliyun): access group

pkg/multicloud/volcengine/network.go
=> fix(volc): network ip range

pkg/multicloud/volcengine/network.go
Cherry pick of #686 on release/3.11.
#686: fix(volc): network ip range
=> Automated cherry pick of #686: fix(volc): network ip range

pkg/multicloud/huawei/port.go
=> fix(huawei): skip hw networkinterface sync

pkg/multicloud/azure/instance.go
=> fix(azure): avid panic

pkg/multicloud/azure/instance.go
Cherry pick of #694 on release/3.11.
#694: fix(azure): avid panic
=> Automated cherry pick of #694: fix(azure): avid panic

pkg/multicloud/huawei/dbinstance.go
=> fix(huawei): rds create params

pkg/multicloud/huawei/dbinstance.go
Cherry pick of #691 on release/3.11.
#691: fix(huawei): rds create params
=> Automated cherry pick of #691: fix(huawei): rds create params

pkg/multicloud/qcloud/elasticcache_instance.go
=> fix: qcloud redis wan addr

pkg/multicloud/qcloud/elasticcache_instance.go
Cherry pick of #697 on release/3.11.
#697: fix: qcloud redis wan addr
=> Automated cherry pick of #697: fix: qcloud redis wan addr

pkg/multicloud/huawei/huawei.go, pkg/multicloud/qcloud/elasticcache_instance.go
=> fix: huawei monitor api

pkg/multicloud/huawei/huawei.go, pkg/multicloud/qcloud/elasticcache_instance.go
Cherry pick of #699 on release/3.11.
#699: fix: huawei monitor api
=> Automated cherry pick of #699: fix: huawei monitor api

pkg/multicloud/huawei/elasticcache_instance.go
=> fix(huawei): redis create

pkg/multicloud/huawei/elasticcache_instance.go
Cherry pick of #701 on release/3.11.
#701: fix(huawei): redis create
=> Automated cherry pick of #701: fix(huawei): redis create

pkg/multicloud/huawei/instance.go, pkg/multicloud/qcloud/monitor.go
=> fix(region): hw refresh

pkg/multicloud/huawei/instance.go, pkg/multicloud/qcloud/monitor.go
Cherry pick of #703 on release/3.11.
#703: fix(region): hw refresh
=> Automated cherry pick of #703: fix(region): hw refresh

pkg/multicloud/huawei/huawei.go
=> fix(huawei): eip disassociate

pkg/multicloud/huawei/huawei.go
Cherry pick of #705 on release/3.11.
#705: fix(huawei): eip disassociate
=> Automated cherry pick of #705: fix(huawei): eip disassociate

pkg/multicloud/aliyun/securitygroup.go
=> fix(aliyun): sec rule create

pkg/multicloud/aliyun/securitygroup.go
Cherry pick of #707 on release/3.11.
#707: fix(aliyun): sec rule create
=> Automated cherry pick of #707: fix(aliyun): sec rule create

pkg/multicloud/proxmox/instance.go
=> fix(pve): show vm error

pkg/multicloud/proxmox/instance.go
Cherry pick of #709 on release/3.11.
#709: fix(pve): show vm error
=> Automated cherry pick of #709: fix(pve): show vm error

pkg/multicloud/proxmox/instance.go
=> fix: avoid json marshal error

pkg/multicloud/proxmox/instance.go
Cherry pick of #712 on release/3.11.
#712: fix: avoid json marshal error
=> Automated cherry pick of #712: fix: avoid json marshal error

pkg/multicloud/qcloud/loadbalancer_backend.go
=> fix(qcloud): avoid unmarshal lb backend tags error

pkg/multicloud/huawei/region.go
=> fix(region): huawei object storage capability

pkg/multicloud/huawei/region.go
Cherry pick of #718 on release/3.11.
#718: fix(region): huawei object storage capability
=> Automated cherry pick of #718: fix(region): huawei object storage capability

pkg/multicloud/aliyun/bucket.go, pkg/multicloud/aws/bucket.go, pkg/multicloud/huawei/bucket.go
=> fix(bucket): ignore not found err for getPolicy

pkg/multicloud/aliyun/bucket.go, pkg/multicloud/aws/bucket.go, pkg/multicloud/huawei/bucket.go
Cherry pick of #720 on release/3.11.
#720: fix(bucket): ignore not found err for getPolicy
=> Automated cherry pick of #720: fix(bucket): ignore not found err for getPolicy

pkg/multicloud/huawei/elasticcache_instance.go
=> fix(huawei): redis spec

pkg/multicloud/huawei/elasticcache_instance.go
Cherry pick of #722 on release/3.11.
#722: fix(huawei): redis spec
=> Automated cherry pick of #722: fix(huawei): redis spec

pkg/multicloud/aws/image.go, pkg/multicloud/aws/shell/image.go, pkg/multicloud/aws/storagecache.go
=> fix(aws): image import

pkg/multicloud/aws/image.go, pkg/multicloud/aws/shell/image.go, pkg/multicloud/aws/storagecache.go
Cherry pick of #724 on release/3.11.
#724: fix(aws): image import
=> Automated cherry pick of #724: fix(aws): image import

pkg/multicloud/google/secgrouprules.go
=> fix(google): sec rule update

pkg/multicloud/google/secgrouprules.go
Cherry pick of #728 on release/3.11.
#728: fix(google): sec rule update
=> Automated cherry pick of #728: fix(google): sec rule update

pkg/multicloud/aliyun/dbinstance.go, pkg/multicloud/aliyun/dbinstance_backup.go
=> fix(aliyun): optimized aliyun rds backup sync

pkg/multicloud/aliyun/dbinstance.go, pkg/multicloud/aliyun/dbinstance_backup.go
Cherry pick of #730 on release/3.11.
#730: fix(aliyun): optimized aliyun rds backup sync
=> Automated cherry pick of #730: fix(aliyun): optimized aliyun rds backup sync

pkg/multicloud/proxmox/proxmox.go, pkg/multicloud/proxmox/storage.go
=> fix(proxmox): details error info

pkg/multicloud/proxmox/proxmox.go, pkg/multicloud/proxmox/storage.go
Cherry pick of #732 on release/3.11.
#732: fix(proxmox): details error info
=> Automated cherry pick of #732: fix(proxmox): details error info

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/vswitch.go, pkg/multicloud/apsara/vswitch.go, pkg/multicloud/aws/network.go, pkg/multicloud/azure/network.go, pkg/multicloud/bingocloud/network.go, pkg/multicloud/ctyun/network.go, pkg/multicloud/ecloud/network.go, pkg/multicloud/esxi/fakevpc.go, pkg/multicloud/google/network.go, pkg/multicloud/hcso/network.go, pkg/multicloud/huawei/network.go, pkg/multicloud/jdcloud/network.go, pkg/multicloud/network_base.go, pkg/multicloud/nutanix/network.go, pkg/multicloud/openstack/network.go, pkg/multicloud/oracle/network.go, pkg/multicloud/proxmox/network.go, pkg/multicloud/qcloud/network.go, pkg/multicloud/remotefile/network.go, pkg/multicloud/ucloud/network.go, pkg/multicloud/volcengine/network.go, pkg/multicloud/vpc_base.go, pkg/multicloud/zstack/network.go
=> fix: add ipv6 interface

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/vswitch.go, pkg/multicloud/apsara/vswitch.go, pkg/multicloud/aws/network.go, pkg/multicloud/azure/network.go, pkg/multicloud/bingocloud/network.go, pkg/multicloud/ctyun/network.go, pkg/multicloud/ecloud/network.go, pkg/multicloud/esxi/fakevpc.go, pkg/multicloud/google/network.go, pkg/multicloud/hcso/network.go, pkg/multicloud/huawei/network.go, pkg/multicloud/jdcloud/network.go, pkg/multicloud/network_base.go, pkg/multicloud/nutanix/network.go, pkg/multicloud/openstack/network.go, pkg/multicloud/oracle/network.go, pkg/multicloud/proxmox/network.go, pkg/multicloud/qcloud/network.go, pkg/multicloud/remotefile/network.go, pkg/multicloud/ucloud/network.go, pkg/multicloud/volcengine/network.go, pkg/multicloud/vpc_base.go, pkg/multicloud/zstack/network.go
Cherry pick of #735 on release/3.11.
#735: fix: add ipv6 interface
=> Automated cherry pick of #735: fix: add ipv6 interface

pkg/cloudprovider/resources.go, pkg/multicloud/bingocloud/instancenic.go, pkg/multicloud/network_base.go, pkg/multicloud/remotefile/instancenic.go, pkg/multicloud/remotefile/network.go
=> fix: add vm ipv6 addr

pkg/cloudprovider/resources.go, pkg/multicloud/bingocloud/instancenic.go, pkg/multicloud/network_base.go, pkg/multicloud/remotefile/instancenic.go, pkg/multicloud/remotefile/network.go
Cherry pick of #737 on release/3.11.
#737: fix: add vm ipv6 addr
=> Automated cherry pick of #737: fix: add vm ipv6 addr

pkg/cloudprovider/resources.go
Cherry pick of #742 on release/3.11.
#742: fix: avoid panic
=> Automated cherry pick of #742: fix: avoid panic

go.mod, go.sum, pkg/multicloud/aliyun/instance.go, pkg/multicloud/aliyun/instancenic.go, pkg/multicloud/aliyun/networkinterfaces.go, pkg/multicloud/aliyun/vpc.go, pkg/multicloud/aliyun/vswitch.go, vendor/modules.txt, vendor/yunion.io/x/pkg/util/netutils/ipv6.go, vendor/yunion.io/x/pkg/util/netutils/macutils.go, vendor/yunion.io/x/pkg/util/netutils/netutils.go, vendor/yunion.io/x/pkg/util/regutils/regutils.go, vendor/yunion.io/x/pkg/util/secrules/cut.go, vendor/yunion.io/x/pkg/util/secrules/secrules.go, vendor/yunion.io/x/pkg/util/secrules/secruleset.go, vendor/yunion.io/x/pkg/util/sortutils/doc.go, vendor/yunion.io/x/pkg/util/sortutils/sortutils.go, vendor/yunion.io/x/pkg/utils/misc.go
=> fix(aliyun): support aliyun ipv6

pkg/multicloud/huawei/instance.go, pkg/multicloud/huawei/instancenic.go, pkg/multicloud/huawei/network.go
=> fix(huawei): ipv6 sync

pkg/multicloud/huawei/instance.go, pkg/multicloud/huawei/instancenic.go, pkg/multicloud/huawei/network.go
Cherry pick of #746 on release/3.11.
#746: fix(huawei): ipv6 sync
=> Automated cherry pick of #746: fix(huawei): ipv6 sync

pkg/multicloud/aws/instance.go, pkg/multicloud/aws/instancenic.go, pkg/multicloud/aws/network.go, pkg/multicloud/aws/networkinterface.go, pkg/multicloud/aws/vpc.go
Cherry pick of #748 on release/3.11.
#748: fix: support aws ipv6 sync
=> Automated cherry pick of #748: fix: support aws ipv6 sync

pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/instancenic.go, pkg/multicloud/qcloud/network.go, pkg/multicloud/qcloud/networkinterface.go, pkg/multicloud/qcloud/vpc.go
=> fix: qcloud ipv6 sync

pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/instancenic.go, pkg/multicloud/qcloud/network.go, pkg/multicloud/qcloud/networkinterface.go, pkg/multicloud/qcloud/vpc.go
Cherry pick of #750 on release/3.11.
#750: fix: qcloud ipv6 sync
=> Automated cherry pick of #750: fix: qcloud ipv6 sync

pkg/multicloud/aliyun/vswitch.go, pkg/multicloud/aws/network.go, pkg/multicloud/huawei/network.go
=> fix: support set tags for network

pkg/multicloud/volcengine/instance.go, pkg/multicloud/volcengine/instancenic.go, pkg/multicloud/volcengine/network.go, pkg/multicloud/volcengine/networkinterfaces.go, pkg/multicloud/volcengine/shell/networkinterface.go, pkg/multicloud/volcengine/vpc.go
=> fix(region): volc ipv6 sync

pkg/multicloud/volcengine/instance.go, pkg/multicloud/volcengine/instancenic.go, pkg/multicloud/volcengine/network.go, pkg/multicloud/volcengine/networkinterfaces.go, pkg/multicloud/volcengine/shell/networkinterface.go, pkg/multicloud/volcengine/vpc.go
Cherry pick of #752 on release/3.11.
#752: fix(region): volc ipv6 sync
=> Automated cherry pick of #752: fix(region): volc ipv6 sync

pkg/multicloud/aliyun/vswitch.go, pkg/multicloud/aws/network.go, pkg/multicloud/huawei/network.go
Cherry pick of #754 on release/3.11.
#754: fix: support set tags for network
=> Automated cherry pick of #754: fix: support set tags for network

pkg/multicloud/aws/shell/product.go, pkg/multicloud/aws/sku.go
=> fix: aws product list

pkg/multicloud/aws/shell/product.go, pkg/multicloud/aws/sku.go
Cherry pick of #756 on release/3.11.
#756: fix: aws product list
=> Automated cherry pick of #756: fix: aws product list

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/instance.go, pkg/multicloud/qcloud/disk.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/shell/disk.go
=> fix(qcloud): delete vm with disks

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/instance.go, pkg/multicloud/qcloud/disk.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/shell/disk.go
Cherry pick of #758 on release/3.11.
#758: fix(qcloud): delete vm with disks
=> Automated cherry pick of #758: fix(qcloud): delete vm with disks

pkg/multicloud/aliyun/tag_base.go
=> fix(aliyun): systag

pkg/multicloud/aliyun/tag_base.go
Cherry pick of #761 on release/3.11.
#761: fix(aliyun): systag
=> Automated cherry pick of #761: fix(aliyun): systag

pkg/multicloud/esxi/storage.go, pkg/multicloud/esxi/virtualmachine.go
=> fix(esxi): migrate vm choices usable datastore

pkg/multicloud/openstack/openstack.go
=> fix(openstack): support https for openstack

pkg/apis/compute/cloudregions_const.go, pkg/apis/compute/regiondata.go, pkg/multicloud/aws/latitude_and_longitude.go, pkg/multicloud/azure/geographicinfo.go, pkg/multicloud/google/latitude_and_longitude.go
=> fix(azure): region code

pkg/apis/compute/cloudregions_const.go, pkg/apis/compute/regiondata.go, pkg/multicloud/aws/latitude_and_longitude.go, pkg/multicloud/azure/geographicinfo.go, pkg/multicloud/google/latitude_and_longitude.go
Cherry pick of #767 on release/3.11.
#767: fix(azure): region code
=> Automated cherry pick of #767: fix(azure): region code

pkg/multicloud/qcloud/natgateway.go
=> fix(qcloud): nat status

pkg/multicloud/qcloud/natgateway.go
Cherry pick of #770 on release/3.10.
#770: fix(qcloud): nat status
=> Automated cherry pick of #770: fix(qcloud): nat status

pkg/multicloud/volcengine/disk.go, pkg/multicloud/volcengine/network.go, pkg/multicloud/volcengine/region.go, pkg/multicloud/volcengine/shell/network.go, pkg/multicloud/volcengine/shell/snapshot.go, pkg/multicloud/volcengine/snapshot.go, pkg/multicloud/volcengine/wire.go
=> fix(volc): support snapshot

pkg/multicloud/volcengine/disk.go, pkg/multicloud/volcengine/network.go, pkg/multicloud/volcengine/region.go, pkg/multicloud/volcengine/shell/network.go, pkg/multicloud/volcengine/shell/snapshot.go, pkg/multicloud/volcengine/snapshot.go, pkg/multicloud/volcengine/wire.go
Cherry pick of #766 on release/3.11.
#766: fix(volc): support snapshot
=> Automated cherry pick of #766: fix(volc): support snapshot

pkg/cloudprovider/loadbalanceracl.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/loadbalanceracl.go, pkg/multicloud/aliyun/loadbalancerservercertificate.go, pkg/multicloud/apsara/loadbalanceracl.go, pkg/multicloud/apsara/loadbalancerservercertificate.go, pkg/multicloud/aws/loadbalancercert.go, pkg/multicloud/azure/loadbalancercert.go, pkg/multicloud/google/loadbalancer_cert.go, pkg/multicloud/google/resourcebase.go, pkg/multicloud/hcso/loadbalancer_acl.go, pkg/multicloud/hcso/loadbalancer_cert.go, pkg/multicloud/hcso/region.go, pkg/multicloud/huawei/loadbalancer_acl.go, pkg/multicloud/huawei/loadbalancer_cert.go, pkg/multicloud/huawei/region.go, pkg/multicloud/huawei/shell/lbcert.go, pkg/multicloud/openstack/loadbalanceracl.go, pkg/multicloud/qcloud/certificate.go
Cherry pick of #774 on release/3.11.
#774: refactor: acl and cert
=> Automated cherry pick of #774: refactor: acl and cert

pkg/cloudprovider/resources.go, pkg/multicloud/aws/loadbalancer.go, pkg/multicloud/azure/loadbalancer.go, pkg/multicloud/google/loadbalancer.go, pkg/multicloud/hcso/loadbalancer.go, pkg/multicloud/huawei/loadbalancer.go, pkg/multicloud/loadbalancer_base.go, pkg/multicloud/qcloud/loadbalancer.go, pkg/multicloud/remotefile/loadbalancer.go
=> fix: 同步lb安全组信息

vendor/modules.txt, vendor/yunion.io/x/jsonutils/unmarshal.go, vendor/yunion.io/x/pkg/util/cloudinit/cloudconfig.go, vendor/yunion.io/x/pkg/util/netutils/ipv6.go, vendor/yunion.io/x/pkg/util/netutils/macutils.go, vendor/yunion.io/x/pkg/util/netutils/netutils.go, vendor/yunion.io/x/pkg/util/printutils/printjson.go, vendor/yunion.io/x/pkg/util/regutils/regutils.go, vendor/yunion.io/x/pkg/util/shellutils/edit.go, vendor/yunion.io/x/pkg/utils/misc.go, vendor/yunion.io/x/structarg/structarg.go
=> fix: vendor update

pkg/multicloud/aliyun/secgrouprule.go, pkg/multicloud/aliyun/securitygroup.go, pkg/multicloud/aws/securitygroup.go, pkg/multicloud/ctyun/secrules.go, pkg/multicloud/huawei/secgrouprule.go, pkg/multicloud/qcloud/securitygroup.go
=> fix: support ipv6 for secgroup

pkg/multicloud/aliyun/secgrouprule.go, pkg/multicloud/aliyun/securitygroup.go, pkg/multicloud/aws/securitygroup.go, pkg/multicloud/ctyun/secrules.go, pkg/multicloud/huawei/secgrouprule.go, pkg/multicloud/qcloud/securitygroup.go
Cherry pick of #780 on release/3.11.
#780: fix: support ipv6 for secgroup
=> Automated cherry pick of #780: fix: support ipv6 for secgroup

pkg/multicloud/aws/lambda.go
=> fix: aws lambda

cmd/cephfscli/main.go, pkg/apis/compute/cloudaccount_const.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/filesystem.go, pkg/multicloud/cephfs/cephfs.go, pkg/multicloud/cephfs/cephfscli/main.go, pkg/multicloud/cephfs/client.go, pkg/multicloud/cephfs/dirs.go, pkg/multicloud/cephfs/provider/provider.go, pkg/multicloud/cephfs/shell/cephfs.go, pkg/multicloud/cephfs/shell/printutils.go, pkg/multicloud/huawei/sfs-turbo.go, pkg/multicloud/loader/loader.go
=> feat: support cephfs

pkg/apis/compute/natgateway.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/natgateway.go, pkg/multicloud/apsara/natgateway.go, pkg/multicloud/aws/natgateway.go, pkg/multicloud/hcso/natgateway.go, pkg/multicloud/huawei/eip.go, pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/nat.go, pkg/multicloud/huawei/nat_dtable.go, pkg/multicloud/huawei/nat_stable.go, pkg/multicloud/huawei/natdtable.go, pkg/multicloud/huawei/natgateway.go, pkg/multicloud/huawei/natstable.go, pkg/multicloud/huawei/shell/natgateway.go, pkg/multicloud/huawei/shell/natstable.go, pkg/multicloud/huawei/vpc.go, pkg/multicloud/qcloud/natgateway.go, pkg/multicloud/volcengine/natgateway.go
=> fix(huawei): 支持公网NAT

pkg/multicloud/apsara/dbinstance.go, pkg/multicloud/apsara/disk.go, pkg/multicloud/apsara/eip.go, pkg/multicloud/apsara/elasticcache_instance.go, pkg/multicloud/apsara/instance.go, pkg/multicloud/apsara/natgateway.go
Cherry pick of #787 on release/3.11.
#787: fix(apsara): remove expire time for apsara
=> Automated cherry pick of #787: fix(apsara): remove expire time for apsara

pkg/multicloud/ctyun/disk.go, pkg/multicloud/ctyun/image.go
=> fix(ctyun): image list page size

pkg/multicloud/ctyun/disk.go, pkg/multicloud/ctyun/image.go
Cherry pick of #790 on release/3.11.
#790: fix(ctyun): image list page size
=> Automated cherry pick of #790: fix(ctyun): image list page size

pkg/multicloud/azure/azure.go, pkg/multicloud/huawei/loadbalancer_backend.go, pkg/multicloud/huawei/loadbalancer_backendgroup.go
=> fix(huawei): avoid sync lb backend panic

pkg/multicloud/azure/azure.go, pkg/multicloud/huawei/loadbalancer_backend.go, pkg/multicloud/huawei/loadbalancer_backendgroup.go
Cherry pick of #793 on release/3.11.
#793: fix(huawei): avoid sync lb backend panic
=> Automated cherry pick of #793: fix(huawei): avoid sync lb backend panic

pkg/multicloud/ctyun/price.go, pkg/multicloud/ctyun/shell/price.go
=> fix(ctyun): add price query

pkg/multicloud/azure/eip.go
=> fix(azure): eip associate type

pkg/multicloud/azure/eip.go
Cherry pick of #797 on release/3.11.
#797: fix(azure): eip associate type
=> Automated cherry pick of #797: fix(azure): eip associate type

pkg/multicloud/ctyun/monitor.go, pkg/multicloud/ctyun/provider/provider.go, pkg/multicloud/ctyun/shell/monitor.go
=> fix(ctyun): metric support

pkg/multicloud/ctyun/monitor.go, pkg/multicloud/ctyun/provider/provider.go, pkg/multicloud/ctyun/shell/monitor.go
Cherry pick of #800 on release/3.11.
#800: fix(ctyun): metric support
=> Automated cherry pick of #800: fix(ctyun): metric support

pkg/multicloud/azure/network.go, pkg/multicloud/azure/vpc.go
=> fix(azure): subnet prefix addr

pkg/multicloud/azure/network.go, pkg/multicloud/azure/vpc.go
Cherry pick of #802 on release/3.11.
#802: fix(azure): subnet prefix addr
=> Automated cherry pick of #802: fix(azure): subnet prefix addr

pkg/multicloud/huawei/disk.go
=> fix(huawei): avoid panic when sync huawei disk

pkg/multicloud/huawei/disk.go
Cherry pick of #805 on release/3.11.
#805: fix(huawei): avoid panic when sync huawei disk
=> Automated cherry pick of #805: fix(huawei): avoid panic when sync huawei disk

pkg/multicloud/qcloud/natgateway.go
=> fix(qcloud): nat field changed

pkg/multicloud/qcloud/natgateway.go
Cherry pick of #808 on release/3.11.
#808: fix(qcloud): nat field changed
=> Automated cherry pick of #808: fix(qcloud): nat field changed

pkg/multicloud/huawei/vpc.go
=> fix(huawei): ignore invalid nat sync

pkg/multicloud/esxi/host.go
=> fix(exsi): vmware vm version

pkg/multicloud/esxi/host.go
Cherry pick of #814 on release/3.11.
#814: fix(exsi): vmware vm version
=> Automated cherry pick of #814: fix(exsi): vmware vm version

pkg/multicloud/esxi/host.go
=> fix(esxi): vmware clone vm upgrade

pkg/multicloud/esxi/host.go
Cherry pick of #817 on release/3.11.
#817: fix(esxi): vmware clone vm upgrade
=> Automated cherry pick of #817: fix(esxi): vmware clone vm upgrade

pkg/multicloud/esxi/host.go
=> fix(vmware): support create vm with desc

pkg/multicloud/esxi/host.go
Cherry pick of #820 on release/3.11.
#820: fix(vmware): support create vm with desc
=> Automated cherry pick of #820: fix(vmware): support create vm with desc

pkg/multicloud/esxi/host.go
=> fix(vmware): desc

pkg/multicloud/esxi/host.go
Cherry pick of #823 on release/3.11.
#823: fix(vmware): desc
=> Automated cherry pick of #823: fix(vmware): desc

pkg/multicloud/ksyun/shell/balance.go
=> fix(ksyun): add balance-show for ksyun

pkg/multicloud/esxi/virtualmachine.go
=> fix(vmware): desc sync

pkg/multicloud/esxi/virtualmachine.go
Cherry pick of #827 on release/3.11.
#827: fix(vmware): desc sync
=> Automated cherry pick of #827: fix(vmware): desc sync

pkg/multicloud/aliyun/instance.go
=> fix(aliyun): prepaid vm delete

pkg/multicloud/aliyun/instance.go
Cherry pick of #829 on release/3.11.
#829: fix(aliyun): prepaid vm delete
=> Automated cherry pick of #829: fix(aliyun): prepaid vm delete

pkg/multicloud/azure/azure.go, pkg/multicloud/azure/azure_v2.go, pkg/multicloud/azure/cloudgroup.go, pkg/multicloud/azure/clouduser.go, pkg/multicloud/azure/enrollment_account.go, pkg/multicloud/azure/saml_provider.go, pkg/multicloud/azure/shell/cloudpolicy.go, pkg/multicloud/azure/shell/clouduser.go
=> fix(azure): graph api

pkg/multicloud/azure/azure.go, pkg/multicloud/azure/azure_v2.go, pkg/multicloud/azure/cloudgroup.go, pkg/multicloud/azure/clouduser.go, pkg/multicloud/azure/enrollment_account.go, pkg/multicloud/azure/saml_provider.go, pkg/multicloud/azure/shell/cloudpolicy.go, pkg/multicloud/azure/shell/clouduser.go
Cherry pick of #832 on release/3.11.
#832: fix(azure): graph api
=> Automated cherry pick of #832: fix(azure): graph api

pkg/multicloud/nutanix/nutanix.go, pkg/multicloud/nutanix/provider/provider.go, pkg/multicloud/proxmox/provider/provider.go, pkg/multicloud/proxmox/proxmox.go
=> fix: region prefix

pkg/multicloud/nutanix/nutanix.go, pkg/multicloud/nutanix/provider/provider.go, pkg/multicloud/proxmox/provider/provider.go, pkg/multicloud/proxmox/proxmox.go
Cherry pick of #834 on release/3.11.
#834: fix: region prefix
=> Automated cherry pick of #834: fix: region prefix

pkg/multicloud/huawei/huawei.go
=> fix(huawei): role list

pkg/multicloud/huawei/huawei.go
Cherry pick of #837 on release/3.11.
#837: fix(huawei): role list
=> Automated cherry pick of #837: fix(huawei): role list

pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/saml_provider.go
=> fix(qcloud): saml auth

pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/saml_provider.go
Cherry pick of #839 on release/3.11.
#839: fix(qcloud): saml auth
=> Automated cherry pick of #839: fix(qcloud): saml auth

pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/saml_provider.go
=> fix(huawei): saml provider

pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/saml_provider.go
Cherry pick of #842 on release/3.11.
#842: fix(huawei): saml provider
=> Automated cherry pick of #842: fix(huawei): saml provider

pkg/multicloud/huawei/cloudgroup.go, pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/roles.go, pkg/multicloud/huawei/shell/role.go
=> fix(huawei): role sync

pkg/multicloud/huawei/cloudgroup.go, pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/roles.go, pkg/multicloud/huawei/shell/role.go
Cherry pick of #845 on release/3.11.
#845: fix(huawei): role sync
=> Automated cherry pick of #845: fix(huawei): role sync

pkg/cloudprovider/cloudprovider.go, pkg/multicloud/aliyun/provider/provider.go, pkg/multicloud/aws/provider/provider.go, pkg/multicloud/azure/azure.go, pkg/multicloud/azure/provider/provider.go, pkg/multicloud/google/provider/provider.go, pkg/multicloud/hcso/huawei.go, pkg/multicloud/hcso/provider/provider.go, pkg/multicloud/huawei/provider/provider.go, pkg/multicloud/qcloud/provider/provider.go
=> fix: remove useless code

pkg/cloudprovider/cloudprovider.go, pkg/multicloud/aliyun/provider/provider.go, pkg/multicloud/aws/provider/provider.go, pkg/multicloud/azure/azure.go, pkg/multicloud/azure/provider/provider.go, pkg/multicloud/google/provider/provider.go, pkg/multicloud/hcso/huawei.go, pkg/multicloud/hcso/provider/provider.go, pkg/multicloud/huawei/provider/provider.go, pkg/multicloud/qcloud/provider/provider.go
Cherry pick of #847 on release/3.11.
#847: fix: remove useless code
=> Automated cherry pick of #847: fix: remove useless code

pkg/cloudprovider/resources.go, pkg/cloudprovider/saml.go, pkg/multicloud/aliyun/ram_role.go, pkg/multicloud/aws/iam_role.go, pkg/multicloud/qcloud/cam_role.go, pkg/multicloud/volcengine/group.go, pkg/multicloud/volcengine/policy.go, pkg/multicloud/volcengine/project.go, pkg/multicloud/volcengine/provider/provider.go, pkg/multicloud/volcengine/role.go, pkg/multicloud/volcengine/saml_provider.go, pkg/multicloud/volcengine/shell/group.go, pkg/multicloud/volcengine/shell/policy.go, pkg/multicloud/volcengine/shell/role.go, pkg/multicloud/volcengine/shell/saml_provider.go, pkg/multicloud/volcengine/shell/user.go, pkg/multicloud/volcengine/user.go, pkg/multicloud/volcengine/volcengine.go
Cherry pick of #849 on release/3.11.
#849: fix(volc): iam support
=> Automated cherry pick of #849: fix(volc): iam support

pkg/multicloud/hcso/huawei.go, pkg/multicloud/nutanix/nutanix.go, pkg/multicloud/openstack/openstack.go, pkg/multicloud/proxmox/proxmox.go, pkg/multicloud/remotefile/region.go, pkg/multicloud/remotefile/remotefile.go
=> fix: provider prefix

pkg/multicloud/hcso/huawei.go, pkg/multicloud/nutanix/nutanix.go, pkg/multicloud/openstack/openstack.go, pkg/multicloud/proxmox/proxmox.go, pkg/multicloud/remotefile/region.go, pkg/multicloud/remotefile/remotefile.go
Cherry pick of #853 on release/3.11.
#853: fix: provider prefix
=> Automated cherry pick of #853: fix: provider prefix

pkg/multicloud/aws/image.go
=> fix(aws): aws instance image info

pkg/multicloud/qcloud/host.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/region.go, pkg/multicloud/qcloud/shell/network.go, pkg/multicloud/qcloud/shell/vpc.go, pkg/multicloud/qcloud/vpc.go, pkg/multicloud/qcloud/wire.go, pkg/multicloud/qcloud/zone.go
=> fix(qcloud): remove cache from qcloud

pkg/multicloud/aws/securitygroup.go
=> fix(aws): optimized aws rule create

pkg/multicloud/aws/securitygroup.go
Cherry pick of #859 on release/3.12.
#859: fix(aws): optimized aws rule create
=> Automated cherry pick of #859: fix(aws): optimized aws rule create

pkg/multicloud/ksyun/disks.go, pkg/multicloud/ksyun/eip.go, pkg/multicloud/ksyun/group.go, pkg/multicloud/ksyun/host.go, pkg/multicloud/ksyun/instancenic.go, pkg/multicloud/ksyun/instances.go, pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/network.go, pkg/multicloud/ksyun/policy.go, pkg/multicloud/ksyun/region.go, pkg/multicloud/ksyun/secgroup_rules.go, pkg/multicloud/ksyun/securitygroup.go, pkg/multicloud/ksyun/shell/disks.go, pkg/multicloud/ksyun/shell/eip.go, pkg/multicloud/ksyun/shell/instances.go, pkg/multicloud/ksyun/shell/network.go, pkg/multicloud/ksyun/shell/securitygroup.go, pkg/multicloud/ksyun/shell/storage.go, pkg/multicloud/ksyun/shell/vpc.go, pkg/multicloud/ksyun/shell/zone.go, pkg/multicloud/ksyun/storages.go, pkg/multicloud/ksyun/tag_base.go, pkg/multicloud/ksyun/user.go, pkg/multicloud/ksyun/vpc.go, pkg/multicloud/ksyun/wire.go, pkg/multicloud/ksyun/zone.go
=> feat(ksyun): support ecs list

pkg/multicloud/ksyun/disks.go, pkg/multicloud/ksyun/eip.go, pkg/multicloud/ksyun/group.go, pkg/multicloud/ksyun/host.go, pkg/multicloud/ksyun/instancenic.go, pkg/multicloud/ksyun/instances.go, pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/network.go, pkg/multicloud/ksyun/policy.go, pkg/multicloud/ksyun/region.go, pkg/multicloud/ksyun/secgroup_rules.go, pkg/multicloud/ksyun/securitygroup.go, pkg/multicloud/ksyun/shell/disks.go, pkg/multicloud/ksyun/shell/eip.go, pkg/multicloud/ksyun/shell/instances.go, pkg/multicloud/ksyun/shell/network.go, pkg/multicloud/ksyun/shell/securitygroup.go, pkg/multicloud/ksyun/shell/storage.go, pkg/multicloud/ksyun/shell/vpc.go, pkg/multicloud/ksyun/shell/zone.go, pkg/multicloud/ksyun/storages.go, pkg/multicloud/ksyun/tag_base.go, pkg/multicloud/ksyun/user.go, pkg/multicloud/ksyun/vpc.go, pkg/multicloud/ksyun/wire.go, pkg/multicloud/ksyun/zone.go
Cherry pick of #786 on release/3.12.
#786: feat(ksyun): support ecs list
=> Automated cherry pick of #786: feat(ksyun): support ecs list

pkg/multicloud/aws/image.go
=> fix(aws): image description

pkg/multicloud/aws/image.go
Cherry pick of #864 on release/3.12.
#864: fix(aws): image description
=> Automated cherry pick of #864: fix(aws): image description

pkg/multicloud/ksyun/zone.go
=> fix(ksyun): GetIStorages addr err

pkg/multicloud/ksyun/zone.go
Cherry pick of #867 on release/3.12.
#867: fix(ksyun): GetIStorages addr err
=> Automated cherry pick of #867: fix(ksyun): GetIStorages addr err

pkg/multicloud/qcloud/host.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/region.go, pkg/multicloud/qcloud/shell/network.go, pkg/multicloud/qcloud/shell/vpc.go, pkg/multicloud/qcloud/vpc.go, pkg/multicloud/qcloud/wire.go, pkg/multicloud/qcloud/zone.go
Cherry pick of #856 on release/3.11.
#856: fix(qcloud): remove cache from qcloud
=> Automated cherry pick of #856: fix(qcloud): remove cache from qcloud

pkg/multicloud/apsara/vpc.go
=> fix: avoid panic

pkg/multicloud/apsara/vpc.go
Cherry pick of #875 on release/3.12.
#875: fix: avoid panic
=> Automated cherry pick of #875: fix: avoid panic

pkg/multicloud/qcloud/vpc.go
=> fix(qcloud): avoid panic

pkg/multicloud/ksyun/disks.go, pkg/multicloud/ksyun/eip.go, pkg/multicloud/ksyun/instances.go, pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/network.go, pkg/multicloud/ksyun/project.go, pkg/multicloud/ksyun/provider/provider.go, pkg/multicloud/ksyun/region.go, pkg/multicloud/ksyun/securitygroup.go, pkg/multicloud/ksyun/shell/project.go, pkg/multicloud/ksyun/shell/tag.go, pkg/multicloud/ksyun/tag.go, pkg/multicloud/ksyun/vpc.go
=> fix(ksyun): instance list

pkg/multicloud/ksyun/disks.go, pkg/multicloud/ksyun/eip.go, pkg/multicloud/ksyun/instances.go, pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/network.go, pkg/multicloud/ksyun/project.go, pkg/multicloud/ksyun/provider/provider.go, pkg/multicloud/ksyun/region.go, pkg/multicloud/ksyun/securitygroup.go, pkg/multicloud/ksyun/shell/project.go, pkg/multicloud/ksyun/shell/tag.go, pkg/multicloud/ksyun/tag.go, pkg/multicloud/ksyun/vpc.go
Cherry pick of #883 on release/3.12.
#883: fix(ksyun): instance list
=> Automated cherry pick of #883: fix(ksyun): instance list

pkg/multicloud/oracle/disk.go, pkg/multicloud/oracle/oracle.go
=> fix(oracle): root account

pkg/multicloud/oracle/disk.go, pkg/multicloud/oracle/oracle.go
Cherry pick of #886 on release/3.12.
#886: fix(oracle): root account
=> Automated cherry pick of #886: fix(oracle): root account

pkg/multicloud/qcloud/region.go
=> fix(qcloud): vpc not found

pkg/multicloud/esxi/manager.go, pkg/multicloud/ksyun/wire.go
=> fix(ksyun): sync ksyun networks

pkg/multicloud/esxi/manager.go, pkg/multicloud/ksyun/wire.go
Cherry pick of #892 on release/3.12.
#892: fix(ksyun): sync ksyun networks
=> Automated cherry pick of #892: fix(ksyun): sync ksyun networks

pkg/multicloud/huawei/dbinstance.go, pkg/multicloud/huawei/disk.go, pkg/multicloud/huawei/eip.go, pkg/multicloud/huawei/elasticcache_instance.go, pkg/multicloud/huawei/instance.go
=> fix(huawei): support delete prepaid resource

pkg/multicloud/huawei/dbinstance.go, pkg/multicloud/huawei/disk.go, pkg/multicloud/huawei/eip.go, pkg/multicloud/huawei/elasticcache_instance.go, pkg/multicloud/huawei/instance.go
Cherry pick of #896 on release/3.12.
#896: fix(huawei): support delete prepaid resource
=> Automated cherry pick of #896: fix(huawei): support delete prepaid resource

pkg/multicloud/oracle/boot-disk.go, pkg/multicloud/oracle/disk.go, pkg/multicloud/oracle/eip.go, pkg/multicloud/oracle/instance.go, pkg/multicloud/oracle/monitor.go, pkg/multicloud/oracle/network.go, pkg/multicloud/oracle/oracle.go, pkg/multicloud/oracle/provider/provider.go, pkg/multicloud/oracle/region.go, pkg/multicloud/oracle/security-group.go, pkg/multicloud/oracle/shell/monitor.go
=> fix(oracle): support monitor

pkg/multicloud/oracle/boot-disk.go, pkg/multicloud/oracle/disk.go, pkg/multicloud/oracle/eip.go, pkg/multicloud/oracle/instance.go, pkg/multicloud/oracle/monitor.go, pkg/multicloud/oracle/network.go, pkg/multicloud/oracle/oracle.go, pkg/multicloud/oracle/provider/provider.go, pkg/multicloud/oracle/region.go, pkg/multicloud/oracle/security-group.go, pkg/multicloud/oracle/shell/monitor.go
Cherry pick of #899 on release/3.12.
#899: fix(oracle): support monitor
=> Automated cherry pick of #899: fix(oracle): support monitor

pkg/multicloud/oracle/monitor.go, pkg/multicloud/oracle/oracle.go
Cherry pick of #902 on release/3.12.
#902: fix(oracle): avoid collect metric read only error
=> Automated cherry pick of #902: fix(oracle): avoid collect metric read only error

pkg/multicloud/ksyun/instances.go
=> fix(ksyun): support get instance ExpiredTime

pkg/multicloud/ksyun/instances.go
Cherry pick of #905 on release/3.12.
#905: fix(ksyun): support get instance ExpiredTime
=> Automated cherry pick of #905: fix(ksyun): support get instance ExpiredTime

pkg/cloudprovider/cdn.go
=> fix: api gen

pkg/cloudprovider/cdn.go
Cherry pick of #908 on release/3.12.
#908: fix: api gen
=> Automated cherry pick of #908: fix: api gen

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/aliyun/project.go, pkg/multicloud/apsara/project.go, pkg/multicloud/azure/azure.go, pkg/multicloud/google/google.go, pkg/multicloud/nutanix/provider/provider.go, pkg/multicloud/project_base.go
=> fix(project): sync provider project

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/aliyun/project.go, pkg/multicloud/apsara/project.go, pkg/multicloud/azure/azure.go, pkg/multicloud/google/google.go, pkg/multicloud/nutanix/provider/provider.go, pkg/multicloud/project_base.go
Cherry pick of #912 on release/3.12.
#912: fix(project): sync provider project
=> Automated cherry pick of #912: fix(project): sync provider project

pkg/multicloud/aws/instance.go, pkg/multicloud/azure/instance.go, pkg/multicloud/ecloud/instance.go, pkg/multicloud/esxi/virtualmachine.go, pkg/multicloud/google/instance.go, pkg/multicloud/nutanix/instance.go, pkg/multicloud/oracle/instance.go, pkg/multicloud/proxmox/instance.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/ucloud/instance.go, pkg/multicloud/zstack/instance.go
=> fix: sync hostname

pkg/multicloud/aws/instance.go, pkg/multicloud/azure/instance.go, pkg/multicloud/ecloud/instance.go, pkg/multicloud/esxi/virtualmachine.go, pkg/multicloud/google/instance.go, pkg/multicloud/nutanix/instance.go, pkg/multicloud/oracle/instance.go, pkg/multicloud/proxmox/instance.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/ucloud/instance.go, pkg/multicloud/zstack/instance.go
Cherry pick of #914 on release/3.12.
#914: fix: sync hostname
=> Automated cherry pick of #914: fix: sync hostname

pkg/cloudprovider/instance.go, pkg/multicloud/aliyun/instance.go, pkg/multicloud/huawei/instance.go
=> fix: update hostname

pkg/cloudprovider/instance.go, pkg/multicloud/aliyun/instance.go, pkg/multicloud/huawei/instance.go
Cherry pick of #917 on release/3.12.
#917: fix: update hostname
=> Automated cherry pick of #917: fix: update hostname

pkg/cloudprovider/resources.go, pkg/multicloud/esxi/host.go, pkg/multicloud/host_base.go
Cherry pick of #922 on release/3.12.
#922: fix(cloudpods): baremetal storage info
=> Automated cherry pick of #922: fix(cloudpods): baremetal storage info

pkg/apis/compute/storage_const.go
=> fix(zstack): shared storage

pkg/apis/compute/storage_const.go
Cherry pick of #928 on release/3.12.
#928: fix(zstack): shared storage
=> Automated cherry pick of #928: fix(zstack): shared storage

Makefile
Cherry pick of #936 on release/3.11.
#936: fix: go mod vendor
=> Automated cherry pick of #936: fix: go mod vendor

pkg/multicloud/azure/shell/web_app.go, pkg/multicloud/azure/web_app.go
=> fix(azure): web app attr

pkg/multicloud/azure/shell/web_app.go, pkg/multicloud/azure/web_app.go
Cherry pick of #942 on release/3.12.
#942: fix(azure): web app attr
=> Automated cherry pick of #942: fix(azure): web app attr

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aws/waf.go, pkg/multicloud/azure/waf.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/region.go, pkg/multicloud/qcloud/shell/waf.go, pkg/multicloud/qcloud/waf.go
Cherry pick of #945 on release/3.12.
#945: fix(qcloud): qcloud waf
=> Automated cherry pick of #945: fix(qcloud): qcloud waf

pkg/multicloud/huawei/huawei.go
=> fix(huawei): avoid empty resp panic

pkg/multicloud/huawei/huawei.go
Cherry pick of #948 on release/3.12.
#948: fix(huawei): avoid empty resp panic
=> Automated cherry pick of #948: fix(huawei): avoid empty resp panic

pkg/multicloud/cephfs/dirs.go, pkg/multicloud/cephfs/shell/cephfs.go
=> fix(cephfs): delete cephfs dir

pkg/multicloud/cephfs/dirs.go, pkg/multicloud/cephfs/shell/cephfs.go
Cherry pick of #954 on release/3.12.
#954: fix(cephfs): delete cephfs dir
=> Automated cherry pick of #954: fix(cephfs): delete cephfs dir

pkg/multicloud/qcloud/bucket.go, pkg/multicloud/qcloud/organization.go, pkg/multicloud/qcloud/provider/provider.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/qcloudcli/main.go, pkg/multicloud/qcloud/shell/organization.go, pkg/multicloud/qcloud/storagecache.go
=> fix(qcloud): support organization

pkg/multicloud/qcloud/bucket.go, pkg/multicloud/qcloud/organization.go, pkg/multicloud/qcloud/provider/provider.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/qcloudcli/main.go, pkg/multicloud/qcloud/shell/organization.go, pkg/multicloud/qcloud/storagecache.go
Cherry pick of #956 on release/3.12.
#956: fix(qcloud): support organization
=> Automated cherry pick of #956: fix(qcloud): support organization

pkg/cloudprovider/resources.go, pkg/cloudprovider/waf.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aliyun/waf_v2_domains.go, pkg/multicloud/aws/waf.go, pkg/multicloud/azure/waf.go, pkg/multicloud/qcloud/waf.go
=> fix(qcloud): add waf upstream info

pkg/cloudprovider/resources.go, pkg/cloudprovider/waf.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aliyun/waf_v2_domains.go, pkg/multicloud/aws/waf.go, pkg/multicloud/azure/waf.go, pkg/multicloud/qcloud/waf.go
Cherry pick of #958 on release/3.11.
#958: fix(qcloud): add waf upstream info
=> Automated cherry pick of #958: fix(qcloud): add waf upstream info

pkg/cloudprovider/cloudprovider.go, pkg/multicloud/ecloud/provider/provider.go, pkg/multicloud/jdcloud/provider/provider.go, pkg/multicloud/ksyun/provider/provider.go, pkg/multicloud/oracle/provider/provider.go
=> fix(region): force account read only

pkg/cloudprovider/cloudprovider.go, pkg/multicloud/ecloud/provider/provider.go, pkg/multicloud/jdcloud/provider/provider.go, pkg/multicloud/ksyun/provider/provider.go, pkg/multicloud/oracle/provider/provider.go
Cherry pick of #964 on release/3.12.
#964: fix(region): force account read only
=> Automated cherry pick of #964: fix(region): force account read only

pkg/multicloud/esxi/datacenter.go
=> fix(esxi): avoid concurrent map read and map write

pkg/multicloud/esxi/datacenter.go
Cherry pick of #961 on release/3.12.
#961: fix(esxi): avoid concurrent map read and map write
=> Automated cherry pick of #961: fix(esxi): avoid concurrent map read and map write

pkg/multicloud/azure/web_app.go
=> fix(azure): web app ip addr

pkg/multicloud/azure/web_app.go
Cherry pick of #967 on release/3.12.
#967: fix(azure): web app ip addr
=> Automated cherry pick of #967: fix(azure): web app ip addr

pkg/multicloud/oracle/storage.go
Cherry pick of #971 on release/3.11.
#971: fix(oracle): oracle storage should be emulated
=> Automated cherry pick of #971: fix(oracle): oracle storage should be emulated

pkg/multicloud/oracle/storage.go
=> fix(oracle): oracle storage should be emulated

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aliyun/waf_v2_domains.go, pkg/multicloud/aws/waf.go, pkg/multicloud/azure/waf.go, pkg/multicloud/qcloud/waf.go
=> fix: add cc list for waf

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aliyun/waf_v2_domains.go, pkg/multicloud/aws/waf.go, pkg/multicloud/azure/waf.go, pkg/multicloud/qcloud/waf.go
Cherry pick of #975 on release/3.12.
#975: fix: add cc list for waf
=> Automated cherry pick of #975: fix: add cc list for waf

pkg/apis/compute/mongodb_const.go, pkg/multicloud/qcloud/mongodb.go
=> fix(qcloud): mongodb status

pkg/apis/compute/mongodb_const.go, pkg/multicloud/qcloud/mongodb.go
Cherry pick of #978 on release/3.12.
#978: fix(qcloud): mongodb status
=> Automated cherry pick of #978: fix(qcloud): mongodb status

pkg/cloudprovider/resources.go, pkg/multicloud/host_base.go
=> fix(cloudpods): host storage driver sync

pkg/cloudprovider/resources.go, pkg/multicloud/host_base.go
Cherry pick of #982 on release/3.12.
#982: fix(cloudpods): host storage driver sync
=> Automated cherry pick of #982: fix(cloudpods): host storage driver sync

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go
=> fix(sangfor): add sangfor const

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go
Cherry pick of #984 on release/3.12.
#984: fix(sangfor): add sangfor const
=> Automated cherry pick of #984: fix(sangfor): add sangfor const

pkg/multicloud/qcloud/qcloud.go
=> fix(region): qcloud permission

pkg/multicloud/qcloud/qcloud.go
Cherry pick of #986 on release/3.12.
#986: fix(region): qcloud permission
=> Automated cherry pick of #986: fix(region): qcloud permission

pkg/cloudprovider/cloudprovider.go, pkg/multicloud/apsara/apsara.go, pkg/multicloud/apsara/apsaracli/main.go, pkg/multicloud/apsara/provider/provider.go, pkg/multicloud/cmx/shell/helper.go, pkg/multicloud/hcso/bucket.go, pkg/multicloud/hcso/hcso.go, pkg/multicloud/hcso/hcsocli/main.go, pkg/multicloud/hcso/huawei.go, pkg/multicloud/hcso/provider/provider.go, pkg/multicloud/oracle/ocli/main.go, pkg/multicloud/oracle/oracle.go, pkg/multicloud/oracle/provider/provider.go
Cherry pick of #989 on release/3.12.
#989: fix(oracle): region optional input
=> Automated cherry pick of #989: fix(oracle): region optional input

pkg/multicloud/qcloud/natgateway.go
=> fix(qcloud): natgateway api upgrade

pkg/multicloud/qcloud/natgateway.go
Cherry pick of #991 on release/3.12.
#991: fix(qcloud): natgateway api upgrade
=> Automated cherry pick of #991: fix(qcloud): natgateway api upgrade

pkg/multicloud/qcloud/qcloud.go
=> fix(qcloud): nat capability sync

go.mod, go.sum, pkg/multicloud/qcloud/image.go, vendor/modules.txt, vendor/yunion.io/x/pkg/util/imagetools/imagetools.go
=> fix(qcloud) tencent os dist

pkg/multicloud/google/securitygroup.go, pkg/multicloud/qcloud/securitygroup.go
=> fix(qcloud): security group rule create

pkg/multicloud/google/securitygroup.go, pkg/multicloud/qcloud/securitygroup.go
Cherry pick of #1005 on release/3.12.
#1005: fix(qcloud): security group rule create
=> Automated cherry pick of #1005: fix(qcloud): security group rule create

pkg/multicloud/google/eip.go, pkg/multicloud/google/globaleip.go
=> fix(gcp): eip list without internal ip

pkg/multicloud/google/eip.go, pkg/multicloud/google/globaleip.go
Cherry pick of #1013 on release/3.12.
#1013: fix(gcp): eip list without internal ip
=> Automated cherry pick of #1013: fix(gcp): eip list without internal ip

pkg/multicloud/google/globalloadbalancer_listener.go
=> fix(google): avoid panic

pkg/multicloud/google/globalloadbalancer_listener.go
Cherry pick of #1016 on release/3.12.
#1016: fix(google): avoid panic
=> Automated cherry pick of #1016: fix(google): avoid panic

pkg/multicloud/esxi/devtools.go, pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/mobase.go, pkg/multicloud/esxi/shell/images.go, pkg/multicloud/esxi/storage.go, pkg/multicloud/esxi/virtualmachine.go
Cherry pick of #920 on release/3.11.
#920: fix(esxi): upload iso image
=> Automated cherry pick of #920: fix(esxi): upload iso image

pkg/multicloud/huawei/storage.go
=> fix(huawei): sata storage sold out

pkg/multicloud/huawei/storage.go
Cherry pick of #1020 on release/3.12.
#1020: fix(huawei): sata storage sold out
=> Automated cherry pick of #1020: fix(huawei): sata storage sold out

pkg/multicloud/qcloud/loadbalancer_backend.go, pkg/multicloud/qcloud/loadbalancer_backendgroup.go
=> fix(qcloud): avoid duplicate backends

pkg/multicloud/qcloud/loadbalancer_backend.go, pkg/multicloud/qcloud/loadbalancer_backendgroup.go
Cherry pick of #1010 on release/3.12.
#1010: fix(qcloud): avoid duplicate backends
=> Automated cherry pick of #1010: fix(qcloud): avoid duplicate backends

pkg/multicloud/google/globalloadbalancer.go, pkg/multicloud/google/globalloadbalancer_components.go
=> fix(google): avoid sync lb panic

pkg/multicloud/google/globalloadbalancer.go, pkg/multicloud/google/globalloadbalancer_components.go
Cherry pick of #1024 on release/3.12.
#1024: fix(google): avoid sync lb panic
=> Automated cherry pick of #1024: fix(google): avoid sync lb panic

pkg/multicloud/qcloud/host.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/instancetype.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/region.go, pkg/multicloud/qcloud/shell/zone.go, pkg/multicloud/qcloud/zone.go
=> fix(qcloud): removed zone resource sync

pkg/multicloud/qcloud/host.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/instancetype.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/region.go, pkg/multicloud/qcloud/shell/zone.go, pkg/multicloud/qcloud/zone.go
Cherry pick of #1026 on release/3.12.
#1026: fix(qcloud): removed zone resource sync
=> Automated cherry pick of #1026: fix(qcloud): removed zone resource sync

pkg/multicloud/huawei/huawei.go
=> fix(huawei): support huawei intl account query balance

pkg/multicloud/huawei/huawei.go
Cherry pick of #1030 on release/3.12.
#1030: fix(huawei): support huawei intl account query balance
=> Automated cherry pick of #1030: fix(huawei): support huawei intl account query balance

pkg/multicloud/proxmox/host.go, pkg/multicloud/proxmox/instance.go
=> fix(pve): supports cpu architecture differentiation

pkg/multicloud/qcloud/loadbalancer_backend.go
=> fix(qcloud): lb backend ip sync

pkg/multicloud/huawei/huawei.go
=> fix(huawei): more details huawei error info

pkg/multicloud/huawei/huawei.go
Cherry pick of #1042 on release/3.12.
#1042: fix(huawei): more details huawei error info
=> Automated cherry pick of #1042: fix(huawei): more details huawei error info

pkg/multicloud/objectstore/objectstore.go
fix: ceph reuse http connection (reported by GDYT)
- release/3.12
- release/3.11
- release/3.10
=> fix: ceph reuse http connection (reported by GDYT)

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/dns_domain_record.go, pkg/multicloud/aliyun/gtm.go, pkg/multicloud/aliyun/gtm3.go, pkg/multicloud/aliyun/private_zone_record.go, pkg/multicloud/aliyun/shell/dns_domain.go, pkg/multicloud/aliyun/shell/gtm.go, pkg/multicloud/aliyun/shell/gtm3.go, pkg/multicloud/aws/aws_request.go, pkg/multicloud/aws/dns_traffic_policy.go, pkg/multicloud/aws/dnsrecord.go, pkg/multicloud/aws/shell/dns_traffic_policy.go, pkg/multicloud/qcloud/dnspod_record.go
=> fix(aws): add dns traffic policy api

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/dns_domain_record.go, pkg/multicloud/aliyun/gtm.go, pkg/multicloud/aliyun/gtm3.go, pkg/multicloud/aliyun/private_zone_record.go, pkg/multicloud/aliyun/shell/dns_domain.go, pkg/multicloud/aliyun/shell/gtm.go, pkg/multicloud/aliyun/shell/gtm3.go, pkg/multicloud/aws/aws_request.go, pkg/multicloud/aws/dns_traffic_policy.go, pkg/multicloud/aws/dnsrecord.go, pkg/multicloud/aws/shell/dns_traffic_policy.go, pkg/multicloud/qcloud/dnspod_record.go
Cherry pick of #1044 on release/3.11.
#1044: fix(aws): add dns traffic policy api
=> Automated cherry pick of #1044: fix(aws): add dns traffic policy api

pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/saml_provider.go
=> fix(huawei): error code

pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/saml_provider.go
Cherry pick of #1050 on release/3.12.
#1050: fix(huawei): error code
=> Automated cherry pick of #1050: fix(huawei): error code

pkg/multicloud/aws/aws.go, pkg/multicloud/aws/iam_group.go, pkg/multicloud/aws/iam_policy.go, pkg/multicloud/aws/iam_role.go, pkg/multicloud/aws/iam_user.go, pkg/multicloud/qcloud/shell/cam_group.go
Cherry pick of #1054 on release/3.12.
#1054: fix(aws): policy sync
=> Automated cherry pick of #1054: fix(aws): policy sync

pkg/multicloud/aws/iam_group.go
=> fix: aws group create

pkg/multicloud/aws/iam_group.go
Cherry pick of #1057 on release/3.12.
#1057: fix: aws group create
=> Automated cherry pick of #1057: fix: aws group create

pkg/multicloud/aws/monitor.go, pkg/multicloud/google/monitor.go
=> fix(aws): metric value

pkg/multicloud/aws/monitor.go, pkg/multicloud/google/monitor.go
Cherry pick of #1060 on release/3.12.
#1060: fix(aws): metric value
=> Automated cherry pick of #1060: fix(aws): metric value

pkg/multicloud/openstack/securitygroup.go
=> fix(openstack): secgroup vpc id

pkg/multicloud/aws/instance.go, pkg/multicloud/aws/utils.go
=> fix(aws): aws disk tag with server

pkg/multicloud/aws/instance.go, pkg/multicloud/aws/utils.go
Cherry pick of #1074 on release/3.12.
#1074: fix(aws): aws disk tag with server
=> Automated cherry pick of #1074: fix(aws): aws disk tag with server

pkg/multicloud/google/instance.go
=> fix(gcp): disk tag with server

pkg/multicloud/google/instance.go
Cherry pick of #1077 on release/3.11.
#1077: fix(gcp): disk tag with server
=> Automated cherry pick of #1077: fix(gcp): disk tag with server

pkg/multicloud/cephfs/client.go
=> fix(cephfs): support http

pkg/multicloud/cephfs/client.go
Cherry pick of #1080 on release/3.12.
#1080: fix(cephfs): support http
=> Automated cherry pick of #1080: fix(cephfs): support http

pkg/cloudprovider/waf.go
=> fix: update enum doc

pkg/cloudprovider/waf.go
Cherry pick of #1086 on release/3.12.
#1086: fix: update enum doc
=> Automated cherry pick of #1086: fix: update enum doc

pkg/multicloud/qcloud/loadbalancer_listener.go
=> fix(qcloud): lb listener health check type

pkg/multicloud/huawei/huawei.go
=> fix(huawei): skip empty response

pkg/multicloud/huawei/huawei.go
Cherry pick of #1092 on release/3.12.
#1092: fix(huawei): skip empty response
=> Automated cherry pick of #1092: fix(huawei): skip empty response

pkg/multicloud/qcloud/loadbalancer_listener.go, pkg/multicloud/qcloud/loadbalancer_listenerrule.go
=> fix(qcloud): lb listener rule create

pkg/multicloud/qcloud/loadbalancer_listener.go, pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Cherry pick of #1095 on release/3.11.
#1095: fix(qcloud): lb listener rule create
=> Automated cherry pick of #1095: fix(qcloud): lb listener rule create

pkg/cloudprovider/mount_target.go, pkg/cloudprovider/resources.go, pkg/multicloud/cephfs/dirs.go, pkg/multicloud/cephfs/shell/cephfs.go, pkg/multicloud/nas_base.go
=> fix(cephfs): support set quota

pkg/multicloud/ucloud/instance.go
=> fix(ucloud): avoid panic when sync vm tags

pkg/multicloud/ucloud/instance.go
Cherry pick of #1099 on release/3.12.
#1099: fix(ucloud): avoid panic when sync vm tags
=> Automated cherry pick of #1099: fix(ucloud): avoid panic when sync vm tags

pkg/multicloud/ctyun/eip.go, pkg/multicloud/ctyun/instance.go
=> fix(ctyun): prepaid status

pkg/multicloud/ctyun/eip.go, pkg/multicloud/ctyun/instance.go
Cherry pick of #1102 on release/3.11.
#1102: fix(ctyun): prepaid status
=> Automated cherry pick of #1102: fix(ctyun): prepaid status

pkg/multicloud/qcloud/host.go
=> fix(qcloud): skip check qcloud net

pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/storagecache.go
=> fix(esxi): disable swap

pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/storagecache.go
Cherry pick of #1106 on release/3.11.
#1106: fix(esxi): disable swap
=> Automated cherry pick of #1106: fix(esxi): disable swap

pkg/multicloud/google/instance.go
=> fix(gcp): validate gcp disk name length

pkg/multicloud/google/instance.go
Cherry pick of #1109 on release/3.12.
#1109: fix(gcp): validate gcp disk name length
=> Automated cherry pick of #1109: fix(gcp): validate gcp disk name length

pkg/apis/compute/cloudaccount_const.go, pkg/multicloud/zstack/provider/provider.go
Cherry pick of #1112 on release/3.12.
#1112: fix: remove dstack
=> Automated cherry pick of #1112: fix: remove dstack

pkg/multicloud/azure/host.go
=> fix(azure): azure nic delete

pkg/multicloud/azure/host.go
Cherry pick of #1116 on release/3.12.
#1116: fix(azure): azure nic delete
=> Automated cherry pick of #1116: fix(azure): azure nic delete

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go, pkg/apis/compute/storage_const.go
=> fix(zettakit): add zettakit const

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go, pkg/apis/compute/storage_const.go
Cherry pick of #1123 on release/3.12.
#1123: fix(zettakit): add zettakit const
=> Automated cherry pick of #1123: fix(zettakit): add zettakit const

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go
=> fix(uis): add uis const

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go
Cherry pick of #1125 on release/3.12.
#1125: fix(uis): add uis const
=> Automated cherry pick of #1125: fix(uis): add uis const

pkg/cloudprovider/resources.go, pkg/multicloud/host_base.go, pkg/multicloud/instance_base.go, pkg/multicloud/remotefile/instance.go
=> fix: support isolate device sync

pkg/cloudprovider/instance.go
=> fix: add isolate device params

go.mod, go.sum, vendor/modules.txt, vendor/yunion.io/x/jsonutils/jsonutils.go
fix: update vendor 20241204
- release/3.11.9
- release/3.12
- master
/cc @ioito
=> fix: update vendor 20241204

go.mod, go.sum, vendor/modules.txt, vendor/yunion.io/x/jsonutils/jsonutils.go
Cherry pick of #1130 on release/3.11.9.
#1130: fix: update vendor 20241204
=> Automated cherry pick of #1130: fix: update vendor 20241204

pkg/multicloud/qcloud/qcloud.go
=> fix(qcloud): cred balance

pkg/multicloud/qcloud/qcloud.go
Cherry pick of #1132 on release/3.11.9.
#1132: fix(qcloud): cred balance
=> Automated cherry pick of #1132: fix(qcloud): cred balance

pkg/multicloud/ksyun/instances.go
=> fix(ksyun): vm status

pkg/multicloud/ksyun/instances.go
Cherry pick of #1135 on release/3.11.9.
#1135: fix(ksyun): vm status
=> Automated cherry pick of #1135: fix(ksyun): vm status

pkg/cloudprovider/instance.go
=> fix: add vnc cookie

go.mod, go.sum, pkg/multicloud/objectstore/buckets.go, pkg/multicloud/objectstore/shell.go, vendor/modules.txt, vendor/yunion.io/x/jsonutils/jsonutils.go, vendor/yunion.io/x/s3cli/api-s3-datatypes.go
Cherry pick of #1140 on master.
#1140: fix: ignore put object acl error
=> Automated cherry pick of #1140: fix: ignore put object acl error

go.mod, go.sum, pkg/multicloud/objectstore/buckets.go, pkg/multicloud/objectstore/shell.go, vendor/modules.txt, vendor/yunion.io/x/s3cli/api-s3-datatypes.go
fix: ignore put object acl error
- release/3.11
- master
=> fix: ignore put object acl error

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go
=> fix: add cas const

pkg/multicloud/qcloud/rds_mysql.go
=> fix(qcloud): rds cpu option

pkg/multicloud/qcloud/rds_mysql.go
Cherry pick of #1144 on release/3.11.
#1144: fix(qcloud): rds cpu option
=> Automated cherry pick of #1144: fix(qcloud): rds cpu option

pkg/multicloud/volcengine/volcengine.go
=> fix(volc): volcengine account id

pkg/multicloud/zstack/zstack.go
=> fix(zstack): zstack auth url error

pkg/multicloud/zstack/zstack.go
Cherry pick of #1147 on master.
#1147: fix(zstack): zstack auth url error
=> Automated cherry pick of #1147: fix(zstack): zstack auth url error

pkg/multicloud/objectstore/objectstore.go, pkg/multicloud/objectstore/s3cli/main.go
fix: s3 cli support set sign version
- release/3.11
/cc @zexi @ioito @wanyaoqi
=> fix: s3 cli support set sign version

pkg/multicloud/objectstore/objectstore.go, pkg/multicloud/objectstore/s3cli/main.go
Cherry pick of #1151 on release/3.12.
#1151: fix: s3 cli support set sign version
=> Automated cherry pick of #1151: fix: s3 cli support set sign version

pkg/multicloud/objectstore/provider/provider.go
fix s3 provider support sign algorithm version
- release/3.11
/cc @ioito @wanyaoqi @zexi
=> fix s3 provider support sign algorithm version

pkg/multicloud/objectstore/provider/provider.go
Cherry pick of #1154 on release/3.12.
#1154: fix s3 provider support sign algorithm version
=> Automated cherry pick of #1154: fix s3 provider support sign algorithm version

pkg/multicloud/volcengine/region.go
=> fix(volc): region name

pkg/multicloud/volcengine/region.go
Cherry pick of #1157 on release/3.11.
#1157: fix(volc): region name
=> Automated cherry pick of #1157: fix(volc): region name

pkg/multicloud/ksyun/instances.go, pkg/multicloud/ksyun/region.go
Cherry pick of #1159 on release/3.11.
#1159: fix(ksyun): vm filter
=> Automated cherry pick of #1159: fix(ksyun): vm filter

pkg/multicloud/volcengine/region.go
Cherry pick of #1161 on release/3.11.
#1161: fix(volc): region name
=> Automated cherry pick of #1161: fix(volc): region name

pkg/multicloud/volcengine/region.go
Cherry pick of #1163 on release/3.11.
#1163: fix(volc): region name
=> Automated cherry pick of #1163: fix(volc): region name

pkg/cloudprovider/objectstore.go, pkg/multicloud/objectstore/shell.go
fix: download/upload/copy large objects in parallel
- release/3.11
=> fix: download/upload/copy large objects in parallel

pkg/multicloud/aliyun/storage.go
=> fix(aliyun): storage medium type

pkg/multicloud/aliyun/storage.go
Cherry pick of #1171 on release/3.11.
#1171: fix(aliyun): storage medium type
=> Automated cherry pick of #1171: fix(aliyun): storage medium type

pkg/multicloud/aliyun/tag_base.go
=> fix(aliyun): update aliyun sys tag

pkg/multicloud/aliyun/tag_base.go
Cherry pick of #1173 on release/3.11.
#1173: fix(aliyun): update aliyun sys tag
=> Automated cherry pick of #1173: fix(aliyun): update aliyun sys tag

pkg/multicloud/esxi/storage.go, pkg/multicloud/esxi/template.go
=> fix(esxi): skip not found host by storage

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/instance.go, pkg/multicloud/aliyun/shell/instance.go, pkg/multicloud/billing_base.go, pkg/multicloud/hcso/modelarts.go, pkg/multicloud/huawei/modelarts_pool.go, pkg/multicloud/qcloud/instance.go, pkg/multicloud/qcloud/shell/instance.go
Cherry pick of #1175 on release/3.11.
#1175: fix(aliyun): support change vm billing type
=> Automated cherry pick of #1175: fix(aliyun): support change vm billing type

pkg/multicloud/aliyun/instance.go
=> fix(region): change billing type auto renew

pkg/multicloud/aliyun/instance.go
Cherry pick of #1181 on release/3.11.
#1181: fix(region): change billing type auto renew
=> Automated cherry pick of #1181: fix(region): change billing type auto renew

pkg/multicloud/cephfs/client.go
=> fix(cephfs): avoid panic

pkg/multicloud/esxi/devtools.go, pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/shell/virtualmachine.go, pkg/multicloud/esxi/vdisk.go, pkg/multicloud/esxi/virtualmachine.go
=> fix(esxi): set vm bios by image

pkg/multicloud/esxi/devtools.go, pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/shell/virtualmachine.go, pkg/multicloud/esxi/vdisk.go, pkg/multicloud/esxi/virtualmachine.go
Cherry pick of #1189 on release/3.11.
#1189: fix(esxi): set vm bios by image
=> Automated cherry pick of #1189: fix(esxi): set vm bios by image

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/ram_user.go, pkg/multicloud/aws/iam_user.go, pkg/multicloud/clouduser.go, pkg/multicloud/hcso/clouduser.go, pkg/multicloud/huawei/clouduser.go, pkg/multicloud/huawei/shell/clouduser.go, pkg/multicloud/qcloud/cam_user.go, pkg/multicloud/volcengine/user.go
=> fix(clouduser): support enable and disable

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/ram_user.go, pkg/multicloud/aws/iam_user.go, pkg/multicloud/clouduser.go, pkg/multicloud/hcso/clouduser.go, pkg/multicloud/huawei/clouduser.go, pkg/multicloud/huawei/shell/clouduser.go, pkg/multicloud/qcloud/cam_user.go, pkg/multicloud/volcengine/user.go
Cherry pick of #1184 on release/3.11.
#1184: fix(clouduser): support enable and disable
=> Automated cherry pick of #1184: fix(clouduser): support enable and disable

pkg/multicloud/qcloud/waf.go
=> fix(qcloud): waf instance id

pkg/multicloud/qcloud/waf.go
This reverts commit f82d639056693d0e4cfe6589b8334bed16b05b99.
- release/3.11
=> Revert "fix(qcloud): waf instance id"

pkg/multicloud/qcloud/waf.go
=> fix(qcloud): waf domain id

pkg/multicloud/azure/azure_v2.go, pkg/multicloud/azure/reservation.go, pkg/multicloud/azure/shell/reservation.go
=> fix(azure): add reservation list

pkg/multicloud/azure/azure_v2.go, pkg/multicloud/azure/reservation.go, pkg/multicloud/azure/shell/reservation.go
Cherry pick of #1206 on release/3.11.
#1206: fix(azure): add reservation list
=> Automated cherry pick of #1206: fix(azure): add reservation list

pkg/multicloud/azure/monitor.go
=> fix(azure): monitor metric

pkg/multicloud/azure/monitor.go
Cherry pick of #1209 on release/3.11.10.
#1209: fix(azure): monitor metric
=> Automated cherry pick of #1209: fix(azure): monitor metric

go.mod, go.sum, pkg/cloudprovider/objectstore.go, vendor/modules.txt, vendor/yunion.io/x/pkg/util/httputils/httputils.go, vendor/yunion.io/x/pkg/util/qemuimgfmt/fmt.go, vendor/yunion.io/x/pkg/util/streamutils/streamutils.go, vendor/yunion.io/x/pkg/utils/tags.go
fix: objectstore download with progresser
NONE
=> fix: objectstore download with progresser

pkg/cloudprovider/clouduser.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/ram_user.go, pkg/multicloud/aliyun/shell/ram_user.go, pkg/multicloud/aws/iam_user.go, pkg/multicloud/aws/shell/iam_user.go, pkg/multicloud/clouduser.go, pkg/multicloud/huawei/clouduser.go, pkg/multicloud/qcloud/cam_user.go, pkg/multicloud/volcengine/user.go
=> fix(region): enable user with more params

pkg/cloudprovider/clouduser.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/ram_user.go, pkg/multicloud/aliyun/shell/ram_user.go, pkg/multicloud/aws/iam_user.go, pkg/multicloud/aws/shell/iam_user.go, pkg/multicloud/clouduser.go, pkg/multicloud/huawei/clouduser.go, pkg/multicloud/qcloud/cam_user.go, pkg/multicloud/volcengine/user.go
Cherry pick of #1212 on release/3.11.
#1212: fix(region): enable user with more params
=> Automated cherry pick of #1212: fix(region): enable user with more params

go.mod, go.sum, vendor/modules.txt, vendor/yunion.io/x/pkg/util/httputils/httputils.go, vendor/yunion.io/x/pkg/util/qemuimgfmt/fmt.go, vendor/yunion.io/x/pkg/util/streamutils/streamutils.go, vendor/yunion.io/x/pkg/utils/tags.go
Hotfix/qj update vendor 20250325
- release/3.11
- release/3.11.10
=> fix: update vendor 20250325

go.mod, go.sum, vendor/modules.txt, vendor/yunion.io/x/pkg/util/streamutils/streamutils.go
Cherry pick of #1219 on master.
#1219: fix: update vendor 20250325
=> Automated cherry pick of #1219: fix: update vendor 20250325

pkg/cloudprovider/objectstore.go
fix: use streampipe2 to stream
NONE
/cc @zexi
=> fix: use streampipe2 to stream

pkg/cloudprovider/resources.go
=> fix: add isolated device share

pkg/multicloud/esxi/host.go
=> fix(esxi): ignore no default gateway host nic

pkg/multicloud/esxi/host.go
=> fix(esxi): optimized hostip sync

pkg/multicloud/huawei/monitor.go
=> fix(huawei): windows metric query

pkg/multicloud/huawei/monitor.go
Cherry pick of #1228 on release/3.11.
#1228: fix(huawei): windows metric query
=> Automated cherry pick of #1228: fix(huawei): windows metric query

pkg/multicloud/esxi/host.go
Cherry pick of #1230 on release/3.11.
#1230: fix(esxi): optimized hostip sync
=> Automated cherry pick of #1230: fix(esxi): optimized hostip sync

pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/mobase.go
=> fix(esxi): host access ip sync

pkg/multicloud/esxi/host.go, pkg/multicloud/esxi/mobase.go
Cherry pick of #1232 on release/3.11.
#1232: fix(esxi): host access ip sync
=> Automated cherry pick of #1232: fix(esxi): host access ip sync

pkg/multicloud/aliyun/instance.go
=> fix(region): vm auto renew

pkg/multicloud/aliyun/instance.go
Cherry pick of #1234 on master.
#1234: fix(region): vm auto renew
=> Automated cherry pick of #1234: fix(region): vm auto renew

pkg/multicloud/proxmox/instance.go
=> fix(pve): nic ip sync

pkg/multicloud/proxmox/instance.go
Cherry pick of #1236 on release/3.11.
#1236: fix(pve): nic ip sync
=> Automated cherry pick of #1236: fix(pve): nic ip sync

pkg/multicloud/aliyun/disk.go
=> fix(aliyun): resize disk online

pkg/multicloud/aliyun/disk.go
Cherry pick of #1238 on release/3.11.
#1238: fix(aliyun): resize disk online
=> Automated cherry pick of #1238: fix(aliyun): resize disk online

pkg/multicloud/aws/image.go, pkg/multicloud/aws/instance.go
=> fix(aws): avoid Invalid device name /dev/sda error

pkg/apis/compute/cloudaccount_const.go, pkg/multicloud/aliyun/shell/dns_domain.go
=> fix: add cloudflare const

pkg/apis/compute/cloudaccount_const.go, pkg/multicloud/aliyun/shell/dns_domain.go
Cherry pick of #1244 on release/4.0.
#1244: fix: add cloudflare const
=> Automated cherry pick of #1244: fix: add cloudflare const

pkg/cloudprovider/dnszone.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/dns_domain_record.go, pkg/multicloud/aliyun/private_zone_record.go, pkg/multicloud/aws/dnsrecord.go, pkg/multicloud/dns_record_base.go, pkg/multicloud/qcloud/dnspod_record.go
Cherry pick of #1246 on release/4.0.
#1246: fix: dns zone proxied
=> Automated cherry pick of #1246: fix: dns zone proxied

pkg/multicloud/aws/image.go
Cherry pick of #1248 on release/3.11.
#1248: fix(region): aws image dist
=> Automated cherry pick of #1248: fix(region): aws image dist

pkg/multicloud/aliyun/disk.go
=> fix(aliyun): change billing type

pkg/multicloud/aliyun/disk.go
Cherry pick of #1251 on release/4.0.
#1251: fix(aliyun): change billing type
=> Automated cherry pick of #1251: fix(aliyun): change billing type

pkg/multicloud/aws/instance.go
=> fix(aws): attach disk validate device name

pkg/multicloud/aws/instance.go
Cherry pick of #1254 on release/3.11.
#1254: fix(aws): attach disk validate device name
=> Automated cherry pick of #1254: fix(aws): attach disk validate device name

pkg/cloudprovider/objectstore.go
fix: failed to download zero-sized object
- release/4.0
=> fix: failed to download zero-sized object

pkg/multicloud/huawei/huawei.go, pkg/multicloud/huawei/shell/business.go
=> fix(huawei): query month bill

pkg/apis/compute/storage_const.go
=> fix(qcloud): storage const

pkg/apis/compute/storage_const.go
Cherry pick of #1260 on release/3.11.
#1260: fix(qcloud): storage const
=> Automated cherry pick of #1260: fix(qcloud): storage const

pkg/multicloud/qcloud/storage.go
=> fix(qcloud): storage type hssd use system disk

pkg/multicloud/aws/disk.go, pkg/multicloud/aws/instance.go
=> fix(aws): rebuild root

pkg/multicloud/aws/disk.go, pkg/multicloud/aws/instance.go
Cherry pick of #1267 on release/3.11.
#1267: fix(aws): rebuild root
=> Automated cherry pick of #1267: fix(aws): rebuild root

pkg/apis/compute/waf_instance.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aws/waf_rules.go, pkg/multicloud/azure/waf.go
=> fix(waf): add waf rule type

pkg/multicloud/qcloud/bucket.go, pkg/multicloud/qcloud/qcloud.go, pkg/multicloud/qcloud/shell/sts.go, pkg/multicloud/qcloud/storagecache.go
Cherry pick of #1275 on release/4.0.
#1275: fix(qcloud): qcloud organization account
=> Automated cherry pick of #1275: fix(qcloud): qcloud organization account

pkg/multicloud/aws/storagecache.go
Cherry pick of #1277 on release/3.11.
#1277: fix(aws): avoid batch role create
=> Automated cherry pick of #1277: fix(aws): avoid batch role create

pkg/multicloud/aliyun/loadbalancerbackend.go, pkg/multicloud/aliyun/loadbalancerhttplistener.go, pkg/multicloud/aliyun/loadbalancerhttpslistener.go, pkg/multicloud/aliyun/loadbalancerlistenerrule.go, pkg/multicloud/aliyun/shell/loadbalancerlistenerrule.go
=> fix(aliyun): lb backend ip

pkg/multicloud/aliyun/loadbalancerbackend.go, pkg/multicloud/aliyun/loadbalancerhttplistener.go, pkg/multicloud/aliyun/loadbalancerhttpslistener.go, pkg/multicloud/aliyun/loadbalancerlistenerrule.go, pkg/multicloud/aliyun/shell/loadbalancerlistenerrule.go
Cherry pick of #1280 on release/4.0.
#1280: fix(aliyun): lb backend ip
=> Automated cherry pick of #1280: fix(aliyun): lb backend ip

pkg/cloudprovider/resources.go, pkg/cloudprovider/waf.go, pkg/multicloud/aliyun/waf_domain.go, pkg/multicloud/aws/waf_rules.go, pkg/multicloud/azure/waf.go
Cherry pick of #1273 on release/4.0.
#1273: fix: add waf field
=> Automated cherry pick of #1273: fix: add waf field

pkg/multicloud/aws/loadbalancerbackend.go, pkg/multicloud/aws/shell/backendgroup.go, pkg/multicloud/aws/shell/lb.go
=> fix(aws): lb backend id

pkg/multicloud/aws/loadbalancerlistener.go
=> fix(aws): lb listener group id

pkg/multicloud/aws/loadbalancerlistener.go
Cherry pick of #1289 on release/3.11.
#1289: fix(aws): lb listener group id
=> Automated cherry pick of #1289: fix(aws): lb listener group id

pkg/cloudprovider/resources.go, pkg/multicloud/google/loadbalancer_backend.go, pkg/multicloud/google/region.go, pkg/multicloud/google/shell/region.go, pkg/multicloud/hcso/loadbalancer_backendgroup.go, pkg/multicloud/huawei/loadbalancer_backendgroup.go
=> fix(google): lb backend sync

pkg/cloudprovider/resources.go, pkg/multicloud/google/loadbalancer_backend.go, pkg/multicloud/google/region.go, pkg/multicloud/google/shell/region.go, pkg/multicloud/hcso/loadbalancer_backendgroup.go, pkg/multicloud/huawei/loadbalancer_backendgroup.go
Cherry pick of #1292 on release/4.0.
#1292: fix(google): lb backend sync
=> Automated cherry pick of #1292: fix(google): lb backend sync

pkg/multicloud/aliyun/loadbalancerbackend.go
Cherry pick of #1295 on release/4.0.
#1295: fix(aliyun): lb backend
=> Automated cherry pick of #1295: fix(aliyun): lb backend

pkg/multicloud/google/eip.go
=> fix(gcp): eip filter by ip

pkg/multicloud/google/eip.go
Cherry pick of #1301 on release/4.0.
#1301: fix(gcp): eip filter by ip
=> Automated cherry pick of #1301: fix(gcp): eip filter by ip

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/loadbalancer.go, pkg/multicloud/apsara/loadbalancer.go, pkg/multicloud/aws/eip.go, pkg/multicloud/aws/loadbalancer.go, pkg/multicloud/azure/loadbalancer.go, pkg/multicloud/google/globalloadbalancer.go, pkg/multicloud/google/loadbalancer.go, pkg/multicloud/hcso/loadbalancer.go, pkg/multicloud/huawei/loadbalancer.go, pkg/multicloud/loadbalancer_base.go, pkg/multicloud/openstack/instance.go, pkg/multicloud/openstack/loadbalbacer.go, pkg/multicloud/qcloud/loadbalancer.go, pkg/multicloud/remotefile/loadbalancer.go
Cherry pick of #1299 on release/4.0.
#1299: fix(region): lb eips
=> Automated cherry pick of #1299: fix(region): lb eips

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/sslcertificate.go, pkg/multicloud/certificate_base.go, pkg/multicloud/huawei/sslcertificate.go, pkg/multicloud/qcloud/certificate.go
=> fix: certificate dns zone id

pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/qcloud/qcloud.go
=> fix(aliyun): sub account

pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/qcloud/qcloud.go
Cherry pick of #1306 on release/4.0.
#1306: fix(aliyun): sub account
=> Automated cherry pick of #1306: fix(aliyun): sub account

pkg/apis/compute/storage_const.go, pkg/multicloud/esxi/storage.go
=> fix(esxi): add pmem storage type

pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/aliyun/provider/provider.go
=> fix(aliyun): dns zone sync

pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/aliyun/provider/provider.go
Cherry pick of #1312 on release/4.0.
#1312: fix(aliyun): dns zone sync
=> Automated cherry pick of #1312: fix(aliyun): dns zone sync

pkg/multicloud/aliyun/provider/provider.go
=> fix(aliyun): get dns zone by id

pkg/multicloud/aliyun/provider/provider.go
Cherry pick of #1316 on release/4.0.
#1316: fix(aliyun): get dns zone by id
=> Automated cherry pick of #1316: fix(aliyun): get dns zone by id

pkg/multicloud/qcloud/loadbalancer.go, pkg/multicloud/qcloud/loadbalancer_backend.go, pkg/multicloud/qcloud/loadbalancer_backendgroup.go, pkg/multicloud/qcloud/loadbalancer_listenerrule.go
Cherry pick of #1319 on release/4.0.
#1319: fix(qcloud): lb backend group sync
=> Automated cherry pick of #1319: fix(qcloud): lb backend group sync

pkg/cloudprovider/cdn.go, pkg/cloudprovider/resources.go, pkg/multicloud/aws/cdn.go, pkg/multicloud/cdn_domain_base.go, pkg/multicloud/huawei/cdn.go, pkg/multicloud/qcloud/cdn.go
Cherry pick of #1324 on release/4.0.
#1324: fix: add cdn attribute
=> Automated cherry pick of #1324: fix: add cdn attribute

pkg/cloudprovider/cdn.go
Cherry pick of #1327 on release/4.0.
#1327: fix: cdn clean cache options
=> Automated cherry pick of #1327: fix: cdn clean cache options

pkg/cloudprovider/cdn.go, pkg/multicloud/aliyun/shell/cen_route.go, pkg/multicloud/aliyun/shell/dbinstance.go, pkg/multicloud/aliyun/shell/oss.go, pkg/multicloud/aliyun/shell/routetable.go, pkg/multicloud/aliyun/shell/snapshot.go
=> fix: misc code warnning

pkg/cloudprovider/aigateway.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/consts.go, pkg/cloudprovider/resources.go
=> fix: add ai gateway interface

pkg/cloudprovider/aigateway.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/consts.go, pkg/cloudprovider/resources.go
Cherry pick of #1334 on release/4.0.0.
#1334: fix: add ai gateway interface
=> Automated cherry pick of #1334: fix: add ai gateway interface

pkg/cloudprovider/cloudprovider.go
=> fix: add ai gateway

pkg/cloudprovider/dnszone.go, pkg/multicloud/aliyun/dns_domain_record.go
Cherry pick of #1340 on release/3.11.
#1340: fix(aliyun): dns line
=> Automated cherry pick of #1340: fix(aliyun): dns line

pkg/cloudprovider/dnszone.go, pkg/multicloud/aliyun/dns_domain.go, pkg/multicloud/aliyun/provider/provider.go, pkg/multicloud/aliyun/shell/dns_domain.go, pkg/multicloud/qcloud/dnspod_domain.go, pkg/multicloud/qcloud/provider/provider.go
Cherry pick of #1344 on release/4.0.
#1344: fix(aliyun): dns product type
=> Automated cherry pick of #1344: fix(aliyun): dns product type

pkg/cloudprovider/resources.go
=> fix: resolve conflict

pkg/multicloud/esxi/virtualmachine.go
=> fix(esxi): 重装系统保证系统盘排在首位

pkg/multicloud/esxi/virtualmachine.go
Cherry pick of #1350 on release/4.0.
#1350: fix(esxi): 重装系统保证系统盘排在首位
=> Automated cherry pick of #1350: fix(esxi): 重装系统保证系统盘排在首位

pkg/multicloud/aliyun/mongodb.go, pkg/multicloud/aliyun/shell/mongodb.go
Cherry pick of #1354 on release/4.0.0.
#1354: fix(aliyun): mongodb ip addr
=> Automated cherry pick of #1354: fix(aliyun): mongodb ip addr

pkg/multicloud/aliyun/dns_domain_record.go
Cherry pick of #1358 on release/4.0.0.
#1358: fix(aliyun): dns record line
=> Automated cherry pick of #1358: fix(aliyun): dns record line

pkg/cloudprovider/cdn.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/disk.go, pkg/cloudprovider/endpoints.go, pkg/cloudprovider/geoinfo.go, pkg/cloudprovider/i18n.go, pkg/cloudprovider/instance.go, pkg/cloudprovider/retry.go, pkg/cloudprovider/route_table.go, pkg/cloudprovider/securitygroup.go, pkg/cloudprovider/subaccount.go, pkg/cloudprovider/transport.go, pkg/cloudprovider/waf.go, pkg/cloudprovider/waitstatus.go
Cherry pick of #1363 on release/4.0.
#1363: fix: fmt code
=> Automated cherry pick of #1363: fix: fmt code

pkg/cloudprovider/disk.go, pkg/multicloud/aliyun/disk.go, pkg/multicloud/aliyun/storage.go, pkg/multicloud/aws/disk.go, pkg/multicloud/aws/shell/disk.go, pkg/multicloud/aws/storage.go, pkg/multicloud/azure/disk.go, pkg/multicloud/azure/shell/disk.go, pkg/multicloud/azure/storage.go, pkg/multicloud/google/disk.go, pkg/multicloud/google/instance.go, pkg/multicloud/google/shell/disk.go, pkg/multicloud/google/storage.go, pkg/multicloud/huawei/disk.go, pkg/multicloud/huawei/shell/disk.go, pkg/multicloud/huawei/storage.go, pkg/multicloud/qcloud/disk.go, pkg/multicloud/qcloud/shell/disk.go, pkg/multicloud/qcloud/storage.go, pkg/multicloud/ucloud/disk.go, pkg/multicloud/ucloud/storage.go, pkg/multicloud/volcengine/disk.go, pkg/multicloud/volcengine/shell/disk.go, pkg/multicloud/volcengine/storage.go
=> fix(region): create disk with tags

pkg/cloudprovider/disk.go, pkg/multicloud/aliyun/disk.go, pkg/multicloud/aliyun/storage.go, pkg/multicloud/aws/disk.go, pkg/multicloud/aws/shell/disk.go, pkg/multicloud/aws/storage.go, pkg/multicloud/azure/disk.go, pkg/multicloud/azure/shell/disk.go, pkg/multicloud/azure/storage.go, pkg/multicloud/google/disk.go, pkg/multicloud/google/instance.go, pkg/multicloud/google/shell/disk.go, pkg/multicloud/google/storage.go, pkg/multicloud/huawei/disk.go, pkg/multicloud/huawei/shell/disk.go, pkg/multicloud/huawei/storage.go, pkg/multicloud/qcloud/disk.go, pkg/multicloud/qcloud/shell/disk.go, pkg/multicloud/qcloud/storage.go, pkg/multicloud/ucloud/disk.go, pkg/multicloud/ucloud/storage.go, pkg/multicloud/volcengine/disk.go, pkg/multicloud/volcengine/shell/disk.go, pkg/multicloud/volcengine/storage.go
Cherry pick of #1368 on release/4.0.0.
#1368: fix(region): create disk with tags
=> Automated cherry pick of #1368: fix(region): create disk with tags

pkg/multicloud/google/eip.go, pkg/multicloud/google/loadbalancer.go, pkg/multicloud/google/loadbalancer_components.go, pkg/multicloud/google/shell/loadbalancer.go
=> fix(gcp): lb eip sync

pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/resources.go, pkg/cloudprovider/ssl.go, pkg/multicloud/aliyun/sslcertificate.go, pkg/multicloud/huawei/sslcertificate.go, pkg/multicloud/qcloud/certificate.go
=> fix: ssl create

pkg/multicloud/esxi/storage.go, pkg/multicloud/esxi/virtualmachine.go
Cherry pick of #1376 on release/3.11.11.
#1376: fix(esxi): add delete vm debug info
=> Automated cherry pick of #1376: fix(esxi): add delete vm debug info

pkg/cloudprovider/ssl.go
=> fix: add zone id for ssl create

pkg/multicloud/google/eip.go
=> fix(gcp): eip associate type

pkg/cloudprovider/resources.go, pkg/cloudprovider/ssl.go, pkg/multicloud/certificate_base.go
=> fix: support delete ssl

pkg/cloudprovider/resources.go, pkg/cloudprovider/ssl.go, pkg/multicloud/certificate_base.go
Cherry pick of #1390 on release/4.0.
#1390: fix: support delete ssl
=> Automated cherry pick of #1390: fix: support delete ssl

pkg/multicloud/google/bucket.go
=> fix(gcp): image upload

pkg/multicloud/google/bucket.go
Cherry pick of #1396 on release/4.0.
#1396: fix(gcp): image upload
=> Automated cherry pick of #1396: fix(gcp): image upload

pkg/multicloud/huawei/instance.go
Cherry pick of #1401 on release/4.0.0.
#1401: fix(huawei): huawei vm list
=> Automated cherry pick of #1401: fix(huawei): huawei vm list

pkg/multicloud/cucloud/cucloud.go, pkg/multicloud/cucloud/disk.go, pkg/multicloud/cucloud/host.go, pkg/multicloud/cucloud/instance.go, pkg/multicloud/cucloud/instancenic.go, pkg/multicloud/cucloud/network.go, pkg/multicloud/cucloud/region.go, pkg/multicloud/cucloud/security_group.go, pkg/multicloud/cucloud/shell/disk.go, pkg/multicloud/cucloud/shell/instance.go, pkg/multicloud/cucloud/shell/network.go, pkg/multicloud/cucloud/shell/security_group.go, pkg/multicloud/cucloud/shell/storage.go, pkg/multicloud/cucloud/shell/vpc.go, pkg/multicloud/cucloud/shell/zone.go, pkg/multicloud/cucloud/storage.go, pkg/multicloud/cucloud/vpc.go, pkg/multicloud/cucloud/wire.go, pkg/multicloud/cucloud/zone.go
Cherry pick of #1406 on release/4.0.0.
#1406: fix: cucloud vpc
=> Automated cherry pick of #1406: fix: cucloud vpc

pkg/multicloud/google/disk.go, pkg/multicloud/google/eip.go, pkg/multicloud/google/globalnetwork.go, pkg/multicloud/google/instance.go, pkg/multicloud/google/securitygroup.go, pkg/multicloud/google/vpc.go
Cherry pick of #1409 on release/4.0.
#1409: fix(gcp): resource name
=> Automated cherry pick of #1409: fix(gcp): resource name

pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/aliyun/mongodb_backup.go, pkg/multicloud/aliyun/shell/mongodb.go, pkg/multicloud/aws/cdn.go
=> fix(aliyun): mongodb cluster backup

pkg/multicloud/aliyun/aliyun.go, pkg/multicloud/aliyun/mongodb_backup.go, pkg/multicloud/aliyun/shell/mongodb.go, pkg/multicloud/aws/cdn.go
Cherry pick of #1413 on release/4.0.0.
#1413: fix(aliyun): mongodb cluster backup
=> Automated cherry pick of #1413: fix(aliyun): mongodb cluster backup

pkg/apis/compute/loadbalancer_const.go, pkg/cloudprovider/loadbalancerbackend.go
=> fix: add lb backend type

pkg/cloudprovider/loadbalancerbackendgroup.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/alblistener.go, pkg/multicloud/aliyun/albservergroup.go, pkg/multicloud/aliyun/loadbalancerhttplistener.go, pkg/multicloud/aliyun/loadbalancerhttpslistener.go, pkg/multicloud/aliyun/loadbalancertcplistener.go, pkg/multicloud/aliyun/loadbalancerudplistener.go, pkg/multicloud/aliyun/nlblistener.go, pkg/multicloud/apsara/loadbalancerhttplistener.go, pkg/multicloud/apsara/loadbalancerhttpslistener.go, pkg/multicloud/apsara/loadbalancertcplistener.go, pkg/multicloud/apsara/loadbalancerudplistener.go, pkg/multicloud/aws/loadbalancerlistener.go, pkg/multicloud/azure/loadbalancer_http_listener.go, pkg/multicloud/azure/loadbalancerlistener.go, pkg/multicloud/google/globalloadbalancer_listener.go, pkg/multicloud/google/loadbalancer_listener.go, pkg/multicloud/hcso/loadbalancer_listener.go, pkg/multicloud/huawei/loadbalancer_listener.go, pkg/multicloud/lb_backendgroup_base.go, pkg/multicloud/no_lb_region.go, pkg/multicloud/openstack/loadbalancerlistener.go, pkg/multicloud/openstack/loadbalbacer.go, pkg/multicloud/qcloud/loadbalancer_listener.go, pkg/multicloud/region_base.go
=> fix: add health check

pkg/cloudprovider/loadbalancerbackendgroup.go, pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/alblistener.go, pkg/multicloud/aliyun/albservergroup.go, pkg/multicloud/aliyun/loadbalancerhttplistener.go, pkg/multicloud/aliyun/loadbalancerhttpslistener.go, pkg/multicloud/aliyun/loadbalancertcplistener.go, pkg/multicloud/aliyun/loadbalancerudplistener.go, pkg/multicloud/aliyun/nlblistener.go, pkg/multicloud/apsara/loadbalancerhttplistener.go, pkg/multicloud/apsara/loadbalancerhttpslistener.go, pkg/multicloud/apsara/loadbalancertcplistener.go, pkg/multicloud/apsara/loadbalancerudplistener.go, pkg/multicloud/aws/loadbalancerlistener.go, pkg/multicloud/azure/loadbalancer_http_listener.go, pkg/multicloud/azure/loadbalancerlistener.go, pkg/multicloud/google/globalloadbalancer_listener.go, pkg/multicloud/google/loadbalancer_listener.go, pkg/multicloud/hcso/loadbalancer_listener.go, pkg/multicloud/huawei/loadbalancer_listener.go, pkg/multicloud/lb_backendgroup_base.go, pkg/multicloud/no_lb_region.go, pkg/multicloud/openstack/loadbalancerlistener.go, pkg/multicloud/openstack/loadbalbacer.go, pkg/multicloud/qcloud/loadbalancer_listener.go, pkg/multicloud/region_base.go
Cherry pick of #1421 on release/4.0.
#1421: fix: add health check
=> Automated cherry pick of #1421: fix: add health check

pkg/multicloud/aliyun/disk.go, pkg/multicloud/aws/disk.go, pkg/multicloud/qcloud/disk.go
=> fix(aliyun): support set disk tag

pkg/multicloud/aliyun/disk.go, pkg/multicloud/aws/disk.go, pkg/multicloud/qcloud/disk.go
Cherry pick of #1423 on release/4.0.
#1423: fix(aliyun): support set disk tag
=> Automated cherry pick of #1423: fix(aliyun): support set disk tag

pkg/multicloud/esxi/provider/provider.go
Cherry pick of #1426 on release/4.0.
#1426: fix(esxi): allow update vmware account
=> Automated cherry pick of #1426: fix(esxi): allow update vmware account

pkg/multicloud/esxi/virtualmachine.go
=> fix(esxi): delete esxi vm

pkg/cloudprovider/resources.go, pkg/multicloud/aliyun/dns_domain.go, pkg/multicloud/aliyun/private_zone.go, pkg/multicloud/aws/dnszone.go, pkg/multicloud/dns_zone_base.go, pkg/multicloud/qcloud/dnspod_domain.go
=> fix(region): dns name server

pkg/multicloud/aliyun/eip.go
Cherry pick of #1440 on release/4.0.
#1440: fix(aliyun): eip associate type
=> Automated cherry pick of #1440: fix(aliyun): eip associate type

pkg/cloudprovider/cdn.go
=> fix: add opts for cdn custom hostname

pkg/multicloud/aws/mfa.go, pkg/multicloud/aws/shell/mfa.go
=> fix(aws): add aws mfa cli

pkg/multicloud/qcloud/loadbalancer_backend.go
=> fix(qcloud): lb backend sync

pkg/multicloud/qcloud/loadbalancer_backend.go
Cherry pick of #1446 on release/4.0.
#1446: fix(qcloud): lb backend sync
=> Automated cherry pick of #1446: fix(qcloud): lb backend sync

pkg/multicloud/aws/loadbalancercert.go, pkg/multicloud/aws/loadbalancerlistener.go, pkg/multicloud/aws/loadbalancerlistenerrule.go, pkg/multicloud/aws/shell/lb.go
=> fix(aws): lb listener rule

pkg/multicloud/aws/loadbalancercert.go, pkg/multicloud/aws/loadbalancerlistener.go, pkg/multicloud/aws/loadbalancerlistenerrule.go, pkg/multicloud/aws/shell/lb.go
Cherry pick of #1450 on release/3.11.
#1450: fix(aws): lb listener rule
=> Automated cherry pick of #1450: fix(aws): lb listener rule

pkg/multicloud/aliyun/loadbalancerlistenerrule.go
Cherry pick of #1453 on release/3.11.
#1453: fix(aliyun): lb listener rule
=> Automated cherry pick of #1453: fix(aliyun): lb listener rule

pkg/cloudprovider/objectstore.go
Cherry pick of #1456 on release/4.0.0.
#1456: fix: miss out errors of multipart objects
=> Automated cherry pick of #1456: fix: miss out errors of multipart objects

pkg/apis/compute/cloudregions_const.go, pkg/apis/compute/regiondata.go, pkg/multicloud/aws/latitude_and_longitude.go, pkg/multicloud/aws/region.go, pkg/multicloud/google/latitude_and_longitude.go
Cherry pick of #1467 on release/4.0.
#1467: fix(aws): add region name
=> Automated cherry pick of #1467: fix(aws): add region name

pkg/multicloud/aws/dbinstance_gloable_cluster.go, pkg/multicloud/aws/shell/dbinstance.go
=> fix(aws): add cli for global rds cluster

pkg/multicloud/qcloud/rds_mysql.go
Cherry pick of #1473 on release/3.11.
#1473: fix(qcloud): sync qcloud storage type
=> Automated cherry pick of #1473: fix(qcloud): sync qcloud storage type

pkg/multicloud/aws/dbinstance.go
=> fix(aws): rds category

pkg/multicloud/aliyun/elastic_search_instance_types.go
=> fix(aliyun): es instance type

pkg/multicloud/aliyun/elastic_search_instance_types.go
Cherry pick of #1484 on release/3.11.
#1484: fix(aliyun): es instance type
=> Automated cherry pick of #1484: fix(aliyun): es instance type

pkg/multicloud/aliyun/mongodb.go
=> fix(aliyun): mongodb shared count

pkg/multicloud/esxi/virtualmachine.go
Cherry pick of #1487 on release/3.11.
#1487: fix(esxi): root image path
=> Automated cherry pick of #1487: fix(esxi): root image path

pkg/multicloud/aliyun/mongodb.go
Cherry pick of #1490 on release/3.11.
#1490: fix(aliyun): mongodb shared count
=> Automated cherry pick of #1490: fix(aliyun): mongodb shared count

pkg/multicloud/google/region.go
=> fix(gcp): vm sync

pkg/multicloud/google/region.go
Cherry pick of #1493 on release/3.11.
#1493: fix(gcp): vm sync
=> Automated cherry pick of #1493: fix(gcp): vm sync

pkg/cloudprovider/metrics.go, pkg/multicloud/qcloud/monitor.go, pkg/multicloud/qcloud/shell/monitor.go
Cherry pick of #1498 on release/3.11.
#1498: fix(qcloud): add qcloud disk usage metric
=> Automated cherry pick of #1498: fix(qcloud): add qcloud disk usage metric

pkg/multicloud/aliyun/mongodb.go
=> fix(aliyun): mongodb kind code sync

pkg/multicloud/aliyun/mongodb.go
Cherry pick of #1501 on release/4.0.
#1501: fix(aliyun): mongodb kind code sync
=> Automated cherry pick of #1501: fix(aliyun): mongodb kind code sync

pkg/cloudprovider/resources.go, pkg/multicloud/host_base.go
=> fix: add host ipmi info sync

pkg/multicloud/google/instance.go, pkg/multicloud/google/shell/instance.go
=> fix(gcp): delete vm with deletion protection

pkg/multicloud/google/instance.go, pkg/multicloud/google/shell/instance.go
Cherry pick of #1505 on release/3.11.
#1505: fix(gcp): delete vm with deletion protection
=> Automated cherry pick of #1505: fix(gcp): delete vm with deletion protection

pkg/apis/compute/storage_const.go, pkg/multicloud/google/instance.go
=> fix(gcp): add gcp storage const

pkg/apis/compute/storage_const.go, pkg/multicloud/google/instance.go
Cherry pick of #1508 on release/4.0.
#1508: fix(gcp): add gcp storage const
=> Automated cherry pick of #1508: fix(gcp): add gcp storage const

pkg/apis/compute/storage_const.go, pkg/multicloud/google/instance.go
Cherry pick of #1511 on release/4.0.
#1511: fix(gcp): add pd extreme storage
=> Automated cherry pick of #1511: fix(gcp): add pd extreme storage

pkg/multicloud/aws/dbinstance_cluster.go
=> fix(aws): rds endpoint

pkg/multicloud/aws/dbinstance_cluster.go
Cherry pick of #1523 on release/4.0.
#1523: fix(aws): rds endpoint
=> Automated cherry pick of #1523: fix(aws): rds endpoint

pkg/multicloud/aws/dbinstance_cluster.go, pkg/multicloud/aws/dbinstance_cluster_snapshots.go, pkg/multicloud/aws/dbinstance_snapshot.go, pkg/multicloud/aws/shell/dbinstance.go
Cherry pick of #1525 on release/4.0.
#1525: fix(aws): rds cluster snapshot
=> Automated cherry pick of #1525: fix(aws): rds cluster snapshot

pkg/multicloud/google/instance.go
=> fix(gcp): vm create net params

pkg/multicloud/google/instance.go
Cherry pick of #1528 on release/3.11.
#1528: fix(gcp): vm create net params
=> Automated cherry pick of #1528: fix(gcp): vm create net params

pkg/multicloud/qcloud/dbinstance.go, pkg/multicloud/qcloud/rds_sqlserver.go, pkg/multicloud/qcloud/shell/rds_sqlserver.go, pkg/multicloud/qcloud/tag_base.go
=> fix(qcloud): sql server

pkg/multicloud/qcloud/dbinstance.go, pkg/multicloud/qcloud/rds_sqlserver.go, pkg/multicloud/qcloud/shell/rds_sqlserver.go, pkg/multicloud/qcloud/tag_base.go
Cherry pick of #1527 on release/4.0.
#1527: fix(qcloud): sql server
=> Automated cherry pick of #1527: fix(qcloud): sql server

pkg/multicloud/qcloud/monitor.go
=> fix(qcloud): add sql server monitor

pkg/multicloud/qcloud/monitor.go
Cherry pick of #1533 on release/3.11.
#1533: fix(qcloud): add sql server monitor
=> Automated cherry pick of #1533: fix(qcloud): add sql server monitor

pkg/multicloud/qcloud/qcloud.go
Cherry pick of #1536 on release/4.0.
#1536: fix(qcloud): sub account sync
=> Automated cherry pick of #1536: fix(qcloud): sub account sync

pkg/multicloud/objectstore/objectstore.go
Cherry pick of #1541 on release/4.0.
#1541: fix(s3): add set bucket lifecycle
=> Automated cherry pick of #1541: fix(s3): add set bucket lifecycle

pkg/multicloud/aliyun/aliyun.go
=> fix(aliyun): bucket sync

pkg/multicloud/aliyun/aliyun.go
Cherry pick of #1548 on release/4.0.
#1548: fix(aliyun): bucket sync
=> Automated cherry pick of #1548: fix(aliyun): bucket sync

pkg/apis/compute/cloudaccount_const.go, pkg/apis/compute/guest_const.go, pkg/apis/compute/host_const.go, pkg/apis/compute/storage_const.go
Cherry pick of #1552 on release/4.0.
#1552: fix: support cnware
=> Automated cherry pick of #1552: fix: support cnware

pkg/apis/compute/storage_const.go, pkg/cloudprovider/instance.go, pkg/multicloud/ksyun/disks.go, pkg/multicloud/ksyun/eip.go, pkg/multicloud/ksyun/host.go, pkg/multicloud/ksyun/image.go, pkg/multicloud/ksyun/instancenic.go, pkg/multicloud/ksyun/instances.go, pkg/multicloud/ksyun/keypair.go, pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/network.go, pkg/multicloud/ksyun/project.go, pkg/multicloud/ksyun/provider/provider.go, pkg/multicloud/ksyun/region.go, pkg/multicloud/ksyun/secgroup_rules.go, pkg/multicloud/ksyun/securitygroup.go, pkg/multicloud/ksyun/shell/disks.go, pkg/multicloud/ksyun/shell/eip.go, pkg/multicloud/ksyun/shell/image.go, pkg/multicloud/ksyun/shell/instances.go, pkg/multicloud/ksyun/shell/keypair.go, pkg/multicloud/ksyun/shell/network.go, pkg/multicloud/ksyun/shell/securitygroup.go, pkg/multicloud/ksyun/shell/snapshots.go, pkg/multicloud/ksyun/snapshot.go, pkg/multicloud/ksyun/storagecache.go, pkg/multicloud/ksyun/storages.go, pkg/multicloud/ksyun/vpc.go, pkg/multicloud/ksyun/wire.go
Cherry pick of #1547 on release/3.11.
#1547: fix(ksyun): support ksyun operation
=> Automated cherry pick of #1547: fix(ksyun): support ksyun operation

pkg/multicloud/huawei/bucket.go
Cherry pick of #1557 on release/4.0.
#1557: fix(huawei): bucket policy principal
=> Automated cherry pick of #1557: fix(huawei): bucket policy principal

pkg/multicloud/ksyun/host.go, pkg/multicloud/ksyun/keypair.go, pkg/multicloud/ksyun/ksyun.go
=> fix(ksyun): keypair import

pkg/multicloud/ksyun/host.go, pkg/multicloud/ksyun/keypair.go, pkg/multicloud/ksyun/ksyun.go
Cherry pick of #1564 on release/3.11.
#1564: fix(ksyun): keypair import
=> Automated cherry pick of #1564: fix(ksyun): keypair import

pkg/cloudprovider/instance.go, pkg/multicloud/ksyun/instances.go
Cherry pick of #1567 on release/4.0.
#1567: fix(ksyun): vm vnc
=> Automated cherry pick of #1567: fix(ksyun): vm vnc

pkg/multicloud/qcloud/qcloud.go
=> fix(qcloud): event lookup readonly

pkg/apis/compute/storage_const.go, pkg/multicloud/ksyun/instancetype.go, pkg/multicloud/ksyun/shell/instancetype.go, pkg/multicloud/ksyun/storages.go
Cherry pick of #1561 on release/3.11.12.
#1561: fix(ksyun): add auto pl storage type
=> Automated cherry pick of #1561: fix(ksyun): add auto pl storage type

pkg/multicloud/qcloud/monitor.go
Cherry pick of #1580 on release/3.11.
#1580: fix(qcloud): metric period 60s
=> Automated cherry pick of #1580: fix(qcloud): metric period 60s

pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/monitor.go
=> fix(ksyun): metric data

pkg/multicloud/ksyun/ksyun.go, pkg/multicloud/ksyun/monitor.go
Cherry pick of #1584 on release/4.0.
#1584: fix(ksyun): metric data
=> Automated cherry pick of #1584: fix(ksyun): metric data

pkg/multicloud/ksyun/snapshot.go
=> fix(ksyun): snapshot sync

pkg/multicloud/ksyun/shell/disks.go, pkg/multicloud/ksyun/shell/storage.go, pkg/multicloud/ksyun/storages.go, pkg/multicloud/ksyun/zone.go
=> fix(ksyun): storage sync

pkg/multicloud/ksyun/shell/disks.go, pkg/multicloud/ksyun/shell/storage.go, pkg/multicloud/ksyun/storages.go, pkg/multicloud/ksyun/zone.go
Cherry pick of #1592 on release/4.0.
#1592: fix(ksyun): storage sync
=> Automated cherry pick of #1592: fix(ksyun): storage sync
